LudovicoPiero/dotfiles

flake.lock

| Commit                                                                                            | Message                                 |
| ------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`7ad1c417`](https://github.com/numtide/devshell/commit/7ad1c417c87e98e56dcef7ecd0e0a2f2e5669d51) | `` perl: use makeFullPerlPath (#284) `` |

chore(flake/devshell): `1aed986e` -> `7ad1c417`

---

flake.lock

| Commit                                                                                          | Message                                        |
| ----------------------------------------------------------------------------------------------- | ---------------------------------------------- |
| [`b52e938a`](https://github.com/chaotic-cx/nyx/commit/b52e938ad0203d20cfaf69ecbe367b3e01d4164d) | `` Bump 20231124-1 (#449) ``                   |
| [`c3806922`](https://github.com/chaotic-cx/nyx/commit/c3806922fb8a494de9a0e39ef9916ee4784adafb) | `` Bump 20231123-3 (#448) ``                   |
| [`de4f2859`](https://github.com/chaotic-cx/nyx/commit/de4f2859a06a7c26565c0eb8bd9481764e59be98) | `` nixpkgs: bump to 20231123 ``                |
| …

chore(flake/chaotic): `554e3f61` -> `b52e938a`

---

flake.lock

| Commit                                                                                                     | Message                                                                              |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`5d4161ea`](https://github.com/privatevoid-net/nix-super/commit/5d4161ea25080b3cb95e159f4895be8bccf52a61) | `` fix build ``                                                                      |
| [`b1ab592f`](https://github.com/privatevoid-net/nix-super/commit/b1ab592f28f08da5dc7c060e5c3b19dc66dbc111) | `` Use the StorePath-based cache interface ``                                        |
| …

chore(flake/nix-super): `e5a5fbc0` -> `4f4d3a53`

---

flake.lock

| [`6a73c040`](https://github.com/nix-community/NUR/commit/6a73c040a4b9cf6c8c2a11dddd3d98e8f56a7b70) | `` automatic update `` |
| [`3b34dcf5`](https://github.com/nix-community/NUR/commit/3b34dcf501cf8490dd94c7b8303aae0260d280be) | `` automatic update `` |
| [`f14d91bf`](https://github.com/nix-community/NUR/commit/f14d91bf1ba6d86dfb96543ff450785b08842b7a) | `` automatic update `` |
| [`72ffcf71`](https://github.com/nix-community/NUR/commit/72ffcf71bf98be49a626d870395be6a8d9e632a8) | `` automatic update `` |
| …

chore(flake/nur): `2bd179e3` -> `6a73c040`

---

flake.lock

| Commit                                                                                                      | Message                                           |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`8cedd63e`](https://github.com/nix-community/home-manager/commit/8cedd63eede4c22deb192f1721dd67e7460e1ebe) | `` fish: support flexible abbreviations ``        |
| [`e1f3b36a`](https://github.com/nix-community/home-manager/commit/e1f3b36ab01573fd35cae57d21f45d520433df61) | `` home-manager: set unstable release to 24.05 `` |
| [`aeb2232d`](https://github.com/nix-community/home-manager/commit/aeb2232d7a32530d3448318790534d196bf9427a) | `` home-manager: set stable …

chore(flake/home-manager): `1aabb0a3` -> `8cedd63e`

---

flake.lock

| Commit                                                                                         | Message                                                                                    |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`38664f70`](https://github.com/NixOS/nixpkgs/commit/38664f70d14626d7bc44a159a075ce5202824665) | `` rl-2311: Add release notes on lib ``                                                    |
| [`0b59886c`](https://github.com/NixOS/nixpkgs/commit/0b59886c20b7a5ad4f8da5809b9f4ef93bff0d9a) | `` global: 6.6.10 -> 6.6.11 ``                                                             |
| …

chore(flake/unstable): `37e6adc9` -> `f974988b`

---

flake.lock

| Commit                                                                                         | Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`4aab9009`](https://github.com/NixOS/nixpkgs/commit/4aab9009126c82084e4541d0a72d0acc5ad2ef04) | `` php80: 8.0.29 -> 8.0.30 ``                                                |
| [`95911a6e`](https://github.com/NixOS/nixpkgs/commit/95911a6e13de135754bfe8d917509e105212e2ab) | `` php82: 8.2.12 -> 8.2.13 ``                                                |
| [`f8000dee`](https://github.com/NixOS/nixpkgs/commit/f8000dee3a3e3ed96d13a90273b08dd7e …

chore(flake/stable): `53127ebc` -> `3b8ca944`

---

flake.lock

| [`f6375add`](https://github.com/Gerg-L/spicetify-nix/commit/f6375add8e79bed9f2c1e94e36c48fb313023294) | `` big rework in progress ``     |
| [`bbaa4e74`](https://github.com/Gerg-L/spicetify-nix/commit/bbaa4e74ebe5ca657f6b7b045e723eae65944868) | `` CI update 2023-11-24 (#89) `` |
| [`b6f75fc4`](https://github.com/Gerg-L/spicetify-nix/commit/b6f75fc4e2a9d53145b439d5e6ac9a94493c1e0e) | `` CI update 2023-11-23 (#88) `` |

chore(flake/spicetify-nix): `af4e84d4` -> `f6375add`

---

flake.lock

| Commit                                                                                         | Message                                                                       |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`d2f4d3b7`](https://github.com/NixOS/nixpkgs/commit/d2f4d3b7aff7efd236f0651bbb7f21fa395ca7af) | `` apt: 2.7.6 -> 2.7.7 ``                                                     |
| [`2ef00f3e`](https://github.com/NixOS/nixpkgs/commit/2ef00f3e0babd0200e6d01c1948e96a6926241e7) | `` libpkgconf: 2.0.3 -> 2.1.0 ``                                              |
| [`7351284f`](https://github.com/NixOS/nixpkgs/commit/7351284f4ca77e370c98e2cd56ae3 …

chore(flake/master): `9456f455` -> `d2f4d3b7`

---

flake.lock

| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`d79cf0af`](https://github.com/hyprwm/Hyprland/commit/d79cf0afe26fd6503a47c17a524d45742bf2461a) | `` renderer: fix software cursors on nvidia ``                                |
| [`334d0ae3`](https://github.com/hyprwm/Hyprland/commit/334d0ae31b9b192b6d8c35a40bc83f9076d22b9d) | `` monitor: fix transform matrix calculations for transformed ``              |
| [`be3d6352`](https://github.com/hyprwm/Hyprland/commit/be3d635265331543b37 …

chore(flake/hyprland): `d417370b` -> `d79cf0af`

---

flake.lock

| Commit                                                                                            | Message                 |
| ------------------------------------------------------------------------------------------------- | ----------------------- |
| [`e1d062ff`](https://github.com/srid/nixos-flake/commit/e1d062ff029c0c34816c4d1664a8199f7b36339e) | `` readme: add Zulip `` |

chore(flake/nixos-flake): `9d53b301` -> `e1d062ff`

---

flake.lock

| Commit                                                                                         | Message                                                                |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`7c37839a`](https://github.com/NixOS/nixpkgs/commit/7c37839a447a5754af6fe060c70ca52a7a12db1b) | `` buildMozillaMach: fix crashes due to statically linked libstdc++ `` |

chore(flake/stable): `3b8ca944` -> `1216a5ba`

---

flake.lock

| Commit                                                                                         | Message                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------- |
| [`25e6e027`](https://github.com/NixOS/nixpkgs/commit/25e6e0273ee50dad1a7fb664d9797905549bb055) | `` apptainer: 1.2.4 -> 1.2.5 `` |

chore(flake/master): `d2f4d3b7` -> `fdbeeb35`

---

flake.lock

| Commit                                                                                         | Message                                                                       |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`d2f4d3b7`](https://github.com/NixOS/nixpkgs/commit/d2f4d3b7aff7efd236f0651bbb7f21fa395ca7af) | `` apt: 2.7.6 -> 2.7.7 ``                                                     |
| [`2ef00f3e`](https://github.com/NixOS/nixpkgs/commit/2ef00f3e0babd0200e6d01c1948e96a6926241e7) | `` libpkgconf: 2.0.3 -> 2.1.0 ``                                              |
| [`7351284f`](https://github.com/NixOS/nixpkgs/commit/7351284f4ca77e370c98e2cd56ae3 …

chore(flake/master): `9456f455` -> `fdbeeb35`

---

flake.lock

| [`e51798a8`](https://github.com/nix-community/NUR/commit/e51798a838e6e49a8c3f0a58054c973829e2f806) | `` automatic update `` |
| [`7ddd84ac`](https://github.com/nix-community/NUR/commit/7ddd84acfc35469739ebddbaa2f58f9eebd60869) | `` automatic update `` |
| [`ebf2c682`](https://github.com/nix-community/NUR/commit/ebf2c68214f10ee5b9372ae4960a7b54af514bd3) | `` automatic update `` |

chore(flake/nur): `6a73c040` -> `e51798a8`

---

flake.lock

| Commit                                                                                         | Message                                                                                                   |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- |
| [`ac12ef04`](https://github.com/NixOS/nixpkgs/commit/ac12ef04f77369c53cac744fb5d9fe729f9a9989) | `` lefthook: migrate to by-name ``                                                                        |
| [`144f5dcb`](https://github.com/NixOS/nixpkgs/commit/144f5dcb198ecbd8e03bd3192fd3d550cbb717df) | `` libpkgconf: migrate to by-name `` …

chore(flake/unstable): `f974988b` -> `1b99d72c`

---

flake.lock

| Commit                                                                                         | Message                                                                                                   |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- |
| [`82c1f488`](https://github.com/NixOS/nixpkgs/commit/82c1f488b87eeedcf583fd9ae8cb2ada7d496d5d) | `` noweb: 2.12 -> 2.13 ``                                                                                 |
| [`811294e5`](https://github.com/NixOS/nixpkgs/commit/811294e5f07c03a4fe8e76a0a052c4b4dd5929c4) | `` usql: fix build with clang 12+ `` …

chore(flake/master): `fdbeeb35` -> `dc584735`

---

flake.lock

| Commit                                                                                           | Message                                                                    |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`512a5973`](https://github.com/hyprwm/Hyprland/commit/512a59731b2e579b66325d0e9ce770919eecd685) | `` config: default special_scale_factor to 1 ``                            |
| [`a6eba919`](https://github.com/hyprwm/Hyprland/commit/a6eba919356b08a2a403a52c1e5e020734411668) | `` opengl: require introspection on mirroring ``                           |
| [`745b9985`](https://github.com/hyprwm/Hyprland/commit/745b998587fc39db6e3f77caa54074d …

chore(flake/hyprland): `d79cf0af` -> `512a5973`

---

flake.lock

| [`145de74c`](https://github.com/nix-community/NUR/commit/145de74c6f8ccbd62c6ea4d9b9d8e45ee8382f23) | `` automatic update `` |
| [`1e4badf8`](https://github.com/nix-community/NUR/commit/1e4badf8f18a90273efbca61061851a508a9ac18) | `` automatic update `` |
| [`fc44d5d4`](https://github.com/nix-community/NUR/commit/fc44d5d4a552505f0b585d861512b3ae3365688b) | `` automatic update `` |
| [`a4842789`](https://github.com/nix-community/NUR/commit/a484278909b1360587e1053e5b2cbb55ac343778) | `` automatic update `` |
| …

chore(flake/nur): `e51798a8` -> `145de74c`

---

flake.lock

| [`92780bd2`](https://github.com/nix-community/NUR/commit/92780bd20e4fa0526f63e0136fb6f3bbeac6bf9a) | `` automatic update `` |

chore(flake/nur): `145de74c` -> `92780bd2`

---

flake.lock

| [`81dff537`](https://github.com/Gerg-L/spicetify-nix/commit/81dff537de4a0ae776bbb92f5c62a3625719d4ab) | `` CI update 2023-11-25 (#90) `` |

chore(flake/spicetify-nix): `f6375add` -> `81dff537`

---

flake.lock

| Commit                                                                                         | Message                                                  |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`e705fd12`](https://github.com/NixOS/nixpkgs/commit/e705fd12d20a6e2ec97d8a94ffd8886dd90a8954) | `` Revert "python311Packages.pikepdf: 8.4.0 -> 8.7.1" `` |
| [`1a804fb5`](https://github.com/NixOS/nixpkgs/commit/1a804fb5139501993045e20fe7d65ab9520d19ea) | `` sqlc: 1.23.0 -> 1.24.0 ``                             |
| [`96ca1291`](https://github.com/NixOS/nixpkgs/commit/96ca129160463ac44cf385a7a2070b037f686494) | `` emacsPackages.hotfuzz: build dynamic library ``       |
| …

chore(flake/master): `dc584735` -> `86a8472d`

---

flake.lock

| [`24bed8be`](https://github.com/nix-community/NUR/commit/24bed8be0a3ffb70bf517ae06b35ebf5c8d2fd16) | `` automatic update `` |
| [`fb3bc75b`](https://github.com/nix-community/NUR/commit/fb3bc75bb1dc92d0f61ebc3530c8ab8deda83abc) | `` automatic update `` |
| [`981600da`](https://github.com/nix-community/NUR/commit/981600da923af46f6e2f1728b0c167262f25247c) | `` automatic update `` |
| [`2644c4a3`](https://github.com/nix-community/NUR/commit/2644c4a32642a32ea01dc63fd780404c21c82d7a) | `` automatic update `` |
| …

chore(flake/nur): `92780bd2` -> `24bed8be`

---

flake.lock

| Commit                                                                                           | Message                                                     |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------- |
| [`b281d864`](https://github.com/hyprwm/Hyprland/commit/b281d8647a557f51977c25cb6c0d2f818fe4e4e4) | `` screencopy: use new isNvidia() for format ``             |
| [`15b282ee`](https://github.com/hyprwm/Hyprland/commit/15b282ee0c8b48724b7d068aa95bb1133fdda2d7) | `` opengl: fix window introspection check ``                |
| [`6f733292`](https://github.com/hyprwm/Hyprland/commit/6f733292bf2dae2adf1e7524546e140a93824033) | `` renderer: nvidia checks and use glFinish on …

chore(flake/hyprland): `512a5973` -> `b281d864`

---

flake.lock

| Commit                                                                                         | Message                                                                   |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------- |
| [`68a2749b`](https://github.com/NixOS/nixpkgs/commit/68a2749b5bbdb351b5a07a6a0e9270424898b495) | `` instawow: init at 3.1.0 ``                                             |
| [`679cb8ff`](https://github.com/NixOS/nixpkgs/commit/679cb8ff4db11edf3ac27b188f75a3cc55909cd5) | `` nushellPlugins: update for nu 0.87.1 and build on hydra ``             |
| [`f7263685`](https://github.com/NixOS/nixpkgs/commit/f7263685dfbab3b1f0ea1c7933bf9f225474ad4b) | …

chore(flake/master): `86a8472d` -> `e66223d4`

---

flake.lock

| [`50e08054`](https://github.com/Gerg-L/spicetify-nix/commit/50e08054cb8734babaa4589e15c7677a42a20bc7) | `` CI update 2023-11-26 (#91) `` |

chore(flake/spicetify-nix): `81dff537` -> `50e08054`

---

flake.lock

| Commit                                                                                         | Message                                                                                          |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| [`173b74db`](https://github.com/NixOS/nixpkgs/commit/173b74db07f26344f3517716edd4bff6987b512d) | `` jellyfin: 10.8.11 -> 10.8.12 ``                                                               |
| [`6ccd57c4`](https://github.com/NixOS/nixpkgs/commit/6ccd57c4c6f2b63362935165829fc38d04703155) | `` python311Packages.minikerberos: 0.4.2 -> 0.4.3 ``                                             |
| …

chore(flake/unstable): `1b99d72c` -> `173b74db`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`99ca26d4`](https://github.com/hyprwm/Hyprland/commit/99ca26d4eb84e0071264713902e5b287fcab392e) | `` hooksystem: fix missed log include ``                              |
| [`e416ab74`](https://github.com/hyprwm/Hyprland/commit/e416ab740d224bddb865191a028ea1016d7be31e) | `` config: log info about logs before loading vars ``                 |
| [`7a0a5666`](https://github.com/hyprwm/Hyprland/commit/7a0a5666d565a3ef892a7ab433a5007dd1cc72dd) | `` …

chore(flake/hyprland): `b281d864` -> `99ca26d4`

---

flake.lock

| Commit                                                                                             | Message                      |
| -------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`f69fe2f3`](https://github.com/nix-community/NUR/commit/f69fe2f32f963f16b2abeeb941866a0273142af7) | `` automatic update ``       |
| [`764f0e8f`](https://github.com/nix-community/NUR/commit/764f0e8fee3edcc6c8a6b3f6bfa21b105365a5bf) | `` automatic update ``       |
| [`734c11c4`](https://github.com/nix-community/NUR/commit/734c11c46ead41333c95b789774a88c0854af521) | `` automatic update ``       |
| [`a122c9db`](https://github.com/nix-community/NUR/commit/a122c9db8f724bbe8fd90ac3970ce1b75d929d19) | `` automatic update `` …

chore(flake/nur): `24bed8be` -> `f69fe2f3`

---

flake.lock

| Commit                                                                                          | Message                                                           |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`b1edbf5c`](https://github.com/Mic92/sops-nix/commit/b1edbf5c0464b4cced90a3ba6f999e671f0af631) | `` update vendorHash ``                                           |
| [`f9442c47`](https://github.com/Mic92/sops-nix/commit/f9442c477d6d606176417b45d35f1b6e675b60f6) | `` build(deps): bump golang.org/x/crypto from 0.15.0 to 0.16.0 `` |
| [`4be58d80`](https://github.com/Mic92/sops-nix/commit/4be58d802693d7def8622ff34d36714f8db40371) | `` flake.lock: Update `` …

chore(flake/sops-nix): `49a87c6c` -> `b1edbf5c`

---

flake.lock

| Commit                                                                                         | Message                                                                                       |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`9e6f9c6d`](https://github.com/NixOS/nixpkgs/commit/9e6f9c6d8325d92c5a4e680d8b1ed2495d6f3942) | `` nixos/sourcehut: remove usages of 'with lib;' ``                                           |
| [`ba6817ed`](https://github.com/NixOS/nixpkgs/commit/ba6817ed2260282021072ce79bdd820ea9190502) | `` nixos/sourcehut: add myself as maintainer ``                                               |
| …

chore(flake/unstable): `173b74db` -> `9e6f9c6d`

---

flake.lock

| Commit                                                                                         | Message                                                                     |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`10ee18ca`](https://github.com/NixOS/nixpkgs/commit/10ee18ca9265cada45acfc7a6d7644cd22b82465) | `` certbot: 2.6.0 -> 2.7.4 (#267710) ``                                     |
| [`21672ccd`](https://github.com/NixOS/nixpkgs/commit/21672ccd691ebd2f18fa6b41446389c069adfdbb) | `` firefox-devedition-unwrapped: 121.0b3 -> 121.0b4 ``                      |
| [`2438f55f`](https://github.com/NixOS/nixpkgs/commit/2438f55f0989f1be60b292ef82fa1568b1b89 …

chore(flake/master): `e66223d4` -> `3f83e9f1`

---

flake.lock

| Commit                                                                                         | Message                                                                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`024e4447`](https://github.com/NixOS/nixpkgs/commit/024e4447a42868b4c8f3ac8b3e6a2da83c682de1) | `` paraview: fix strlcat symbol provided by glibc 2.38 ``                       |
| [`8ae2bf1e`](https://github.com/NixOS/nixpkgs/commit/8ae2bf1e607cbdbb5cef93d9ebe8cbc55ff2bdd3) | `` dconf2nix: 0.0.12 -> 0.1.1 ``                                                |
| [`627dda7f`](https://github.com/NixOS/nixpkgs/commit/627dda7f87a1a6ec2a39b …

chore(flake/unstable): `9e6f9c6d` -> `024e4447`

---

flake.lock

| Commit                                                                                          | Message                                    |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`65e567a8`](https://github.com/hyprwm/contrib/commit/65e567a81176d39be7ce6513d1af23954f00cbec) | `` Nix: add aarch64-linux support (#75) `` |

chore(flake/hyprland-contrib): `11bbb96e` -> `65e567a8`

---

flake.lock

| [`54e5c118`](https://github.com/nix-community/NUR/commit/54e5c1183d178322e0dd79ebba7551ccb543b6b6) | `` automatic update `` |
| [`4771f0ad`](https://github.com/nix-community/NUR/commit/4771f0ad93cde5b847e840ce5ac27cee4e85a8c1) | `` automatic update `` |
| [`d5926575`](https://github.com/nix-community/NUR/commit/d5926575eed2a8f8851fbe2c46f2c6c705f437cb) | `` automatic update `` |
| [`d6f93721`](https://github.com/nix-community/NUR/commit/d6f93721ade604ab02a42276ecf94e79edfbd07d) | `` automatic update `` |
| …

chore(flake/nur): `f69fe2f3` -> `54e5c118`

---

flake.lock

| Commit                                                                                         | Message                                                                           |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`9ad22d35`](https://github.com/NixOS/nixpkgs/commit/9ad22d35b67cf3bb03ffd56e96f38bcdbb9163a0) | `` Revert "nixos/switch-to-configuration: remove explicit tmpfiles invocation" `` |
| [`76c5738e`](https://github.com/NixOS/nixpkgs/commit/76c5738ef231b19072cd7b1c0fa6d65cb61b1208) | `` coqPackages.mathcomp-word: 2.1 → {2.2, 3.0} ``                                 |
| [`c4ffc839`](https://github.com/NixOS/nixpkgs/commit/c4ffc83975e38 …

chore(flake/unstable): `024e4447` -> `e2fa3d60`

---

flake.lock

| Commit                                                                                      | Message                                      |
| ------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`d78dd6f5`](https://github.com/viperML/nh/commit/d78dd6f5ebe3f763e31affead8eb58317cc8b6f2) | `` fix version diffing for fresh installs `` |

chore(flake/nh): `23d21975` -> `4298c924`

---

flake.lock

| Commit                                                                                          | Message                                                    |
| ----------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`1bca2465`](https://github.com/chaotic-cx/nyx/commit/1bca2465c2d9b5c3daa530e0f97761fb60803480) | `` mesa32_git: no need to revert patch anymore (#459) ``   |
| [`99533bf5`](https://github.com/chaotic-cx/nyx/commit/99533bf57b7233691bb6991ecf45401dda3bff36) | `` Bump 20231129-2 (#458) ``                               |
| [`e97a5e22`](https://github.com/chaotic-cx/nyx/commit/e97a5e22c5d309017461861e9d7e6a1df6daea30) | `` Bump 20231129-1 (#457) `` …

chore(flake/chaotic): `61cdc7fb` -> `1bca2465`

---

flake.lock

| [`c9b1d9bd`](https://github.com/Gerg-L/spicetify-nix/commit/c9b1d9bd7e62609e0ad9f672a2bff8a419bcb02c) | `` CI update 2023-11-30 (#95) `` |
| [`24d7702e`](https://github.com/Gerg-L/spicetify-nix/commit/24d7702ee33e76f1251afcaaca497cf18d93e229) | `` big rework in progress ``     |
| [`609b30df`](https://github.com/Gerg-L/spicetify-nix/commit/609b30dfeff884856e9c0306cf6454d98015fd7f) | `` CI update 2023-11-29 (#94) `` |
| [`18ffbec4`](https://github.com/Gerg-L/spicetify-nix/commit/18ffbec4127889e0de6661de8ec39dc9f …

chore(flake/spicetify-nix): `50e08054` -> `c9b1d9bd`

---

flake.lock

| [`f6c7b0f6`](https://github.com/Gerg-L/spicetify-nix/commit/f6c7b0f6e122bfba280967dfa2af156f55633574) | `` big rework in progress ``     |
| [`929a196e`](https://github.com/Gerg-L/spicetify-nix/commit/929a196e565affbda822b2bb9bd09e5099e42cfb) | `` remade repo ``                |
| [`caae7310`](https://github.com/Gerg-L/spicetify-nix/commit/caae7310c895dfd4e69171f99927c6dec015b6fe) | `` CI update 2023-11-30 (#95) `` |

chore(flake/spicetify-nix): `c9b1d9bd` -> `f6c7b0f6`

---

flake.lock

| Commit                                                                                         | Message                                                                        |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| [`d3ccd1aa`](https://github.com/NixOS/nixpkgs/commit/d3ccd1aa2fc906dd71d44b29dc9b7817c05cfa03) | `` nixos/sysctl: Move changelog entry for yama ``                              |
| [`9c4dd01d`](https://github.com/NixOS/nixpkgs/commit/9c4dd01dea631e494d46885a0a8f64bd7bbbbefc) | `` screenly-cli: init at 0.2.3 ``                                              |
| [`bb9f1fc4`](https://github.com/NixOS/nixpkgs/commit/bb9f1fc46e188a24e4f1abe34 …

chore(flake/unstable): `e2fa3d60` -> `3934dbde`

---

flake.lock

| Commit                                                                                         | Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`2123ab85`](https://github.com/NixOS/nixpkgs/commit/2123ab85ed9a371bc9a088f3bfb45cd65ff0285f) | `` ledfx: add python-{mbedtls,osc} dependency ``                             |
| [`3c99c6c9`](https://github.com/NixOS/nixpkgs/commit/3c99c6c99343afc4b7c30a441fd1a94324e9d7ac) | `` python3Packages.python-mbedtls: init at 2.8.0 ``                          |
| [`73c42a12`](https://github.com/NixOS/nixpkgs/commit/73c42a12538c2cd57ad99bfdb832487f8 …

chore(flake/master): `3f83e9f1` -> `54c8a156`

---

flake.lock

| Commit                                                                                      | Message                                                   |
| ------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`c192a4a9`](https://github.com/viperML/nh/commit/c192a4a937ed3ab974e14c09b90092b226188281) | `` fix ci ``                                              |
| [`fa217e61`](https://github.com/viperML/nh/commit/fa217e618f6a35a0c485b3759427d2cdaf798a98) | `` fix ci ``                                              |
| [`b55bc82a`](https://github.com/viperML/nh/commit/b55bc82aa0839fed2e91e69c1694f8d2a2ef7074) | `` fix ci ``                                              |
| …

chore(flake/nh): `4298c924` -> `c192a4a9`

---

flake.lock

| Commit                                                                                          | Message                                    |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`72d65d0d`](https://github.com/chaotic-cx/nyx/commit/72d65d0d42004971334c3f4c4297d2504e6438a2) | `` linux_cachyos: 6.6.2 -> 6.6.3 (#461) `` |
| [`289e85bc`](https://github.com/chaotic-cx/nyx/commit/289e85bc21519120065d7cf1cb524b5323211838) | `` nixpkgs: bump to 20231202 ``            |

chore(flake/chaotic): `45d2aa68` -> `72d65d0d`

---

flake.lock

| Commit                                                                                         | Message                                                                                                 |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| [`97312082`](https://github.com/NixOS/nixpkgs/commit/973120823b5824d426b97a7e9e027191b22f33ac) | `` lib.systems.elaborate: fix passing `rust` (more) (#271707) ``                                        |
| [`0616776a`](https://github.com/NixOS/nixpkgs/commit/0616776a5e4072e9455e3966d1fce58feefa7a58) | `` fastgron: 0.6.4 -> 0.6.5 `` …

chore(flake/master): `54c8a156` -> `d491c9db`

---

flake.lock

| Commit                                                                                                | Message                         |
| ----------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`afe1e6b2`](https://github.com/Gerg-L/spicetify-nix/commit/afe1e6b206b45395a97391f09b62dc6d1b95896f) | `` CI update 2023-12-03 (#7) `` |

chore(flake/spicetify-nix): `58f597db` -> `afe1e6b2`

---

flake.lock

| Commit                                                                                         | Message                                                                                                 |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| [`3987aeec`](https://github.com/NixOS/nixpkgs/commit/3987aeec024ad4e9147e14227dc15599f03d83d8) | `` rmfakecloud.ui: migrate to prefetch-yarn-deps ``                                                     |
| [`ec3ae8dd`](https://github.com/NixOS/nixpkgs/commit/ec3ae8ddf699f31aced16ec9e0ef74bef689a9c3) | `` pulumi: 3.90.1 -> 3.93.0 `` …

chore(flake/unstable): `3771eeac` -> `0b62f5ad`

---

flake.lock

| Commit                                                                                           | Message                                                                        |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------ |
| [`68783d90`](https://github.com/hyprwm/Hyprland/commit/68783d904d850df65887adb1bab7eff59943c1ac) | `` screencopy: use buffer format for glReadPixels ``                           |
| [`5d100bdc`](https://github.com/hyprwm/Hyprland/commit/5d100bdcbbd87bac74935eae6b7d7aed25620323) | `` opengl: clear layer fade fbs in ~dtor ``                                    |
| [`45d3fbb8`](https://github.com/hyprwm/Hyprland/commit/45d3fbb8d8409b2 …

chore(flake/hyprland): `99ca26d4` -> `68783d90`

---

flake.lock

| Commit                                                                                                      | Message                                           |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`ac721691`](https://github.com/nix-community/home-manager/commit/ac7216918cd65f3824ba7817dea8f22e61221eaf) | `` firefox: fix folders not showing in toolbar `` |

chore(flake/home-manager): `948703f3` -> `ac721691`

---

flake.lock

| Commit                                                                                            | Message                                                                |
| ------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`44ddedcb`](https://github.com/numtide/devshell/commit/44ddedcbcfc2d52a76b64fb6122f209881bd3e1e) | `` build(deps): bump cachix/install-nix-action from 23 to 24 (#285) `` |

chore(flake/devshell): `c3bd7791` -> `44ddedcb`

---

flake.lock

| Commit                                                                                           | Message                                                                   |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------- |
| [`8bd86cf3`](https://github.com/hyprwm/Hyprland/commit/8bd86cf37e245088433156796f1bc72542ca09ad) | `` hyprctl: order commands alphabetically (#4061) ``                      |
| [`cfd94c5b`](https://github.com/hyprwm/Hyprland/commit/cfd94c5b30719c1c512b0d0ef4366a0cb64793e0) | `` input: Stop propagating axis events after valid binds (#4059) ``       |
| [`ab66fa43`](https://github.com/hyprwm/Hyprland/commit/ab66fa430efd1e8b9b6a0220b896998215f …

chore(flake/hyprland): `3bb9c7c5` -> `8bd86cf3`

---

flake.lock

| Commit                                                                                         | Message                                                                                            |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| [`e1567f2e`](https://github.com/NixOS/nixpkgs/commit/e1567f2ee091ca3f43b4b41c143c29d0032adf29) | `` yggdrasil: 0.5.2 → 0.5.4 ``                                                                     |
| [`a0841222`](https://github.com/NixOS/nixpkgs/commit/a08412222dad0a4cbd6d41e405779b54a6001652) | `` home-assistant-custom-lovelace-modules.mini-media-player: 1.16.5 -> 1.16.6 ``                   | …

chore(flake/unstable): `d08f6384` -> `9ed8ade7`

---

flake.lock

| Commit                                                                                                     | Message                                     |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`661b025c`](https://github.com/privatevoid-net/nix-super/commit/661b025c79eac08beda593ede47b41b2052e8ebf) | `` libexpr: really forceValue everything `` |

chore(flake/nix-super): `cb968c09` -> `661b025c`

---

flake.lock

| [`d854884a`](https://github.com/nix-community/NUR/commit/d854884a8c7d2014ff44a27cfe9cac8dd78cc7ea) | `` automatic update `` |
| [`748792dd`](https://github.com/nix-community/NUR/commit/748792dd53008a084e877fd530e0701693291186) | `` automatic update `` |
| [`1a57d132`](https://github.com/nix-community/NUR/commit/1a57d132af8e014fb4c2f30588ab61b3655d665e) | `` automatic update `` |
| [`4ca441c5`](https://github.com/nix-community/NUR/commit/4ca441c58bbfaa1728c4a5b4115f79569f6ff186) | `` automatic update `` |
| …

chore(flake/nur): `34c38401` -> `d854884a`

---

flake.lock

| Commit                                                                                           | Message                                                                 |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`11d1c504`](https://github.com/hyprwm/Hyprland/commit/11d1c50420cdeaa5426b837a6479455f47368f29) | `` windowrules: add focus param ``                                      |
| [`288f1863`](https://github.com/hyprwm/Hyprland/commit/288f1863f0b6886e0cdf85d16bb2460bb042acf2) | `` hyprctl: allow instances without HIS ``                              |
| [`6fb1b89b`](https://github.com/hyprwm/Hyprland/commit/6fb1b89b982eea26ecae75b93f1742537c4f31ae) …

chore(flake/hyprland): `a794eecd` -> `11d1c504`

---

flake.lock

| [`eeb0b84c`](https://github.com/nix-community/NUR/commit/eeb0b84c55657be1575872467aa5a40835af2dcd) | `` automatic update `` |
| [`e4ce6fcf`](https://github.com/nix-community/NUR/commit/e4ce6fcfff92c0491d45607195e96bc8297341b2) | `` automatic update `` |

chore(flake/nur): `d854884a` -> `eeb0b84c`

---

flake.lock

| [`52fa6b83`](https://github.com/Gerg-L/spicetify-nix/commit/52fa6b8355e8fd1dc3cf1371017d0e84de84fb81) | `` CI update 2023-12-10 (#14) `` |
| [`6514d0d4`](https://github.com/Gerg-L/spicetify-nix/commit/6514d0d42e5bad8e0d73debed8e10f27c0c61a47) | `` CI update 2023-12-09 (#13) `` |

chore(flake/spicetify-nix): `79d06a59` -> `52fa6b83`

---

flake.lock

| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`167f2ed3`](https://github.com/hyprwm/Hyprland/commit/167f2ed3b2bb18ceeabb831ac80b655ef8e16867) | `` border: fix failed assert on small windows ``                     |
| [`d02ba422`](https://github.com/hyprwm/Hyprland/commit/d02ba422daae97498ffe6cdf84914b74ddf1fd44) | `` hyprpm: guard empty command ``                                    |
| [`359baa02`](https://github.com/hyprwm/Hyprland/commit/359baa02147f0ff91c8c5156c5e83b6ec6976525) | `` ci: use …

chore(flake/hyprland): `0c10b8ab` -> `167f2ed3`

---

flake.lock

| [`fcb86262`](https://github.com/chaotic-cx/nyx/commit/fcb86262e7bcd5dcbe165e5959aad80064cd82f6) | `` nixpkgs: bump to 20231210 `` |

chore(flake/chaotic): `d16bc3c5` -> `fcb86262`

---

flake.lock

| [`46e1aa64`](https://github.com/nix-community/NUR/commit/46e1aa641b2a4109132b6071c1374cf2690643ef) | `` automatic update `` |
| [`bc19da80`](https://github.com/nix-community/NUR/commit/bc19da80d49164d27953c60e804095094a74e0c4) | `` automatic update `` |
| [`7c966e4b`](https://github.com/nix-community/NUR/commit/7c966e4b321b0cb4c3ca407007c783d1ec998dfd) | `` automatic update `` |

chore(flake/nur): `e45022e0` -> `46e1aa64`

---

flake.lock

| [`6fd5db51`](https://github.com/Gerg-L/spicetify-nix/commit/6fd5db51fce0804b0dd0d2957e82ca64eea60f11) | `` CI update 2023-12-12 (#16) `` |

chore(flake/spicetify-nix): `41edd889` -> `6fd5db51`

---

flake.lock

| Commit                                                                                          | Message                                   |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`7369da9b`](https://github.com/chaotic-cx/nyx/commit/7369da9bf46df08ec2d4793f72e7000d511864e4) | `` Bump 20231213-1 (#483) ``              |
| [`57ab5f5b`](https://github.com/chaotic-cx/nyx/commit/57ab5f5b29b5f8f09b52eb64f8ac85651c569804) | `` nixpkgs: bump to 20231212 ``           |
| [`e22c855e`](https://github.com/chaotic-cx/nyx/commit/e22c855e000c91e9f469bbd406e5e3ae125d47f8) | `` ci: fully eval aarch64-linux (#482) `` |
| [`8961d944`](https://github.com/chaotic-cx/nyx/commit/8961d94486bc9cdf22f52029 …

chore(flake/chaotic): `29cd0da2` -> `7369da9b`

---

flake.lock

| Commit                                                                                         | Message                                                                                                 |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| [`224b3a5a`](https://github.com/NixOS/nixpkgs/commit/224b3a5ad9a960e4a6e3cd59233c1616164c5ef5) | `` jextract: 2023-04-14 -> 2023-11-27 (JDK 21) (#271127) ``                                             |
| [`8c2e8010`](https://github.com/NixOS/nixpkgs/commit/8c2e8010a01f71292980cdf233de932adac3012a) | `` grpc: add jaxlib in passthru.tests `` …

chore(flake/nixpkgs): `120a26f8` -> `224b3a5a`

---

flake.lock

| [`8cf518b0`](https://github.com/nix-community/NUR/commit/8cf518b0011e34505344cc78732a977d1d4ea453) | `` automatic update `` |
| [`8eb5a04d`](https://github.com/nix-community/NUR/commit/8eb5a04d6ea6c65a0a58f2c8a994c92be0506b31) | `` automatic update `` |
| [`7f334741`](https://github.com/nix-community/NUR/commit/7f334741c3e99cbdeb76db62c81065138513d9e2) | `` automatic update `` |
| [`cd3d310a`](https://github.com/nix-community/NUR/commit/cd3d310adf9a6dfa381942e68665e29aae6c096e) | `` automatic update `` |
| …

chore(flake/nur): `cf183d15` -> `8cf518b0`

---

flake.lock

| Commit                                                                                         | Message                                                                                             |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| [`db1680d1`](https://github.com/NixOS/nixpkgs/commit/db1680d1d644c71972fb110833f7f96096c61d7f) | `` gh: 2.40.0 -> 2.40.1 ``                                                                          |
| [`cb37959f`](https://github.com/NixOS/nixpkgs/commit/cb37959f992f27388f16c8aae30d573446ab57d4) | `` miller: copy manpage to $man `` …

chore(flake/nixpkgs): `224b3a5a` -> `02357add`

---

flake.lock

| Commit                                                                                          | Message                                            |
| ----------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`5425e55c`](https://github.com/chaotic-cx/nyx/commit/5425e55c64a1739ebe35cb3f431868c1a5f1ad1c) | `` qtile_git: init with qtile-extras_git (#487) `` |
| [`d2491a98`](https://github.com/chaotic-cx/nyx/commit/d2491a98eb35fe3501388b87436a2956437f783c) | `` Bump 20231215-1 (#486) ``                       |

chore(flake/chaotic): `ea53eaf3` -> `5425e55c`

---

flake.lock

| Commit                                                                                             | Message                     |
| -------------------------------------------------------------------------------------------------- | --------------------------- |
| [`1d374446`](https://github.com/nix-community/NUR/commit/1d37444620523278aa163bb9e30104f5d1152061) | `` automatic update ``      |
| [`be5bda3f`](https://github.com/nix-community/NUR/commit/be5bda3f758c794fb3b56578b628a1f219d8aa2f) | `` automatic update ``      |
| [`7228b6c8`](https://github.com/nix-community/NUR/commit/7228b6c8a670781c9a0fbc9ec99211e672e99554) | `` automatic update ``      |
| [`9297adf9`](https://github.com/nix-community/NUR/commit/9297adf98ec59a92f1867bfc695f350373968e38) | `` automatic update ``      |
| …

chore(flake/nur): `8cf518b0` -> `1d374446`

---

flake.lock

| Commit                                                                                         | Message                                                                                                    |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------- |
| [`44f2f5ce`](https://github.com/NixOS/nixpkgs/commit/44f2f5ce5aaf6ae3ae0c82ffec74e2d235c68535) | `` klipper: unstable-2023-11-16 -> unstable-2023-12-13 (#274602) ``                                        |
| [`944cd0b0`](https://github.com/NixOS/nixpkgs/commit/944cd0b02acc79dc0c14252e116c637024d20525) | `` knot-dns: fixup build on darwin `` …

chore(flake/nixpkgs): `02357add` -> `7d692982`

---

flake.lock

| Commit                                                                                                      | Message                                         |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`e9b9ecef`](https://github.com/nix-community/home-manager/commit/e9b9ecef4295a835ab073814f100498716b05a96) | `` gtk: fix GTK 4 theme being ignored ``        |
| [`5b339866`](https://github.com/nix-community/home-manager/commit/5b3398668b2b7f41607cf77fc9f1cb6402716882) | `` fish: Fix babelization of hm-session-vars `` |
| [`07754e93`](https://github.com/nix-community/home-manager/commit/07754e935a5e6f07f73e43c214f4f24f8ef82117) | `` docs: add considerate as maintainer …

chore(flake/home-manager): `0e2e443f` -> `e9b9ecef`

---

flake.lock

| Commit                                                                                         | Message                                                                                                |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------ |
| [`6946f33a`](https://github.com/NixOS/nixpkgs/commit/6946f33a2e0666ad09aaf8eb51c31c2028c3664a) | `` luaPackages.nlua: init at 0.1 ``                                                                    |
| [`8e9d4495`](https://github.com/NixOS/nixpkgs/commit/8e9d4495c78515277aa43d579610ef3750f59e2c) | `` luarocks-packages-updater: silence some warnings `` …

chore(flake/nixpkgs): `7d692982` -> `3a16c644`

---

flake.lock

| Commit                                                                                             | Message                    |
| -------------------------------------------------------------------------------------------------- | -------------------------- |
| [`a986d4b1`](https://github.com/nix-community/NUR/commit/a986d4b19eb2436c3bebb7d05a755b5786ee9993) | `` automatic update ``     |
| [`e3f15013`](https://github.com/nix-community/NUR/commit/e3f15013fb1597e3cf88325f93035bfc7c4dc129) | `` automatic update ``     |
| [`12386cbc`](https://github.com/nix-community/NUR/commit/12386cbc26ffc94b73ace5f47e6b640674862544) | `` automatic update ``     |
| [`d8d0a4bd`](https://github.com/nix-community/NUR/commit/d8d0a4bdc7b0eb5562df998a7c95ead6780afb00) | `` automatic update ``     |
| …

chore(flake/nur): `784c8293` -> `a986d4b1`

---

flake.lock

| Commit                                                                                           | Message                                                                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------- |
| [`ef445093`](https://github.com/hyprwm/Hyprland/commit/ef445093f9fbd9a41a91914ef45e6499b3afa54d) | `` internal: convert uname fields to strings before logging ``                   |
| [`11fd3741`](https://github.com/hyprwm/Hyprland/commit/11fd37418c8520d9e9ac49856502d1f7d67fae08) | `` renderer: fix null cursor surface sets being ignored ``                       |
| [`0c74df4f`](https://github.com/hyprwm/Hyprland/commit/0c74df4 …

chore(flake/hyprland): `b1b8d732` -> `ef445093`

---

flake.lock

| [`d63d8a56`](https://github.com/nix-community/NUR/commit/d63d8a56df30124ebbf1b746a68fa1fe232e1a3c) | `` automatic update `` |
| [`708a3cce`](https://github.com/nix-community/NUR/commit/708a3ccec178943b779b86e9f483fdc4fd75fee7) | `` automatic update `` |
| [`613dcbe6`](https://github.com/nix-community/NUR/commit/613dcbe6a9fb7b24910b28a866e6f8d340106a84) | `` automatic update `` |
| [`b495f967`](https://github.com/nix-community/NUR/commit/b495f96757696e896c541c7a3a69ca03d44ddae7) | `` automatic update `` |
| …

chore(flake/nur): `a986d4b1` -> `d63d8a56`

---

flake.lock

| [`33308800`](https://github.com/NixOS/nixpkgs/commit/333088006cc26591250fd1e2b8cc972855aa9c4b) | `` pkgsLLVM.llvmPackages.compiler-rt: fix for RISC-V ``                    |
| [`8b5ecc55`](https://github.com/NixOS/nixpkgs/commit/8b5ecc55e1801f3db13bde4d558c9a4a572530b0) | `` clang-tools: 14.0.6 -> 16.0.6 ``                                        |
| [`c4b3e4f5`](https://github.com/NixOS/nixpkgs/commit/c4b3e4f5f89b2d5a96a0280e81eaa880c91b075a) …

chore(flake/nixpkgs): `3a16c644` -> `fa5e0f2e`

---

flake.lock

| Commit                                                                                          | Message                                               |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`d496c55f`](https://github.com/chaotic-cx/nyx/commit/d496c55f7c6a3b7e00ba7e3c3a426799f11748db) | `` Bump 20231219-2 (#495) ``                          |
| [`5c29c53b`](https://github.com/chaotic-cx/nyx/commit/5c29c53b19400faa54ca1ee319e754a54dfe4e87) | `` ci/full-bump: allow skipping building sometimes `` |
| [`6930a843`](https://github.com/chaotic-cx/nyx/commit/6930a843c0407d316e7742a0ae3ab297682fde05) | `` Bump 20231219-1 (#494) ``                          |
| …

chore(flake/chaotic): `3662460d` -> `d496c55f`

---

flake.lock

| Commit                                                                                               | Message                       |
| ---------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`29613752`](https://github.com/numtide/treefmt-nix/commit/2961375283668d867e64129c22af532de8e77734) | `` add swift-format (#142) `` |

chore(flake/treefmt-nix): `d06b70e5` -> `29613752`

---

flake.lock

| Commit                                                                                                      | Message                                                  |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`efc177c1`](https://github.com/nix-community/home-manager/commit/efc177c15f2a8bb063aeb250fe3c7c21e1de265e) | `` sapling: add module ``                                |
| [`ebeeef94`](https://github.com/nix-community/home-manager/commit/ebeeef94ab0cba72ca3b3a89b98658dcc1296c11) | `` docs: fix typo in nix-flakes.md ``                    |
| [`e8aaced7`](https://github.com/nix-community/home-manager/commit/e8aaced73ebaf6bfa8e3c6ab0a19cb184bc4d798) | `` …

chore(flake/home-manager): `e9b9ecef` -> `efc177c1`

---

flake.lock

| Commit                                                                                      | Message                            |
| ------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`37b0d469`](https://github.com/viperML/nh/commit/37b0d469a328a5b5969eacdf137f1e6b86c75a1d) | `` bump version again, check ci `` |

chore(flake/nh): `bd225f25` -> `37b0d469`

---

flake.lock

| [`26ad54b4`](https://github.com/Gerg-L/spicetify-nix/commit/26ad54b46a0573f295ab32ad38716ec96bf3b664) | `` CI update 2023-12-20 (#23) `` |

chore(flake/spicetify-nix): `914a0262` -> `26ad54b4`

---

flake.lock

| [`cc008520`](https://github.com/nix-community/NUR/commit/cc0085209a3d80939926f623ce03491e175126ea) | `` automatic update `` |
| [`048e584a`](https://github.com/nix-community/NUR/commit/048e584a141528a23afd6f766f4eba3e1b86c4c3) | `` automatic update `` |
| [`e6c1cb82`](https://github.com/nix-community/NUR/commit/e6c1cb825ecb0e9b22d1fd1e7951283d4bb11bb3) | `` automatic update `` |
| [`bd0d1ee7`](https://github.com/nix-community/NUR/commit/bd0d1ee76ad572396fa2f24472cb2912f2172703) | `` automatic update `` |
| …

chore(flake/nur): `d63d8a56` -> `cc008520`

---

flake.lock

| [`eef232c5`](https://github.com/nix-community/NUR/commit/eef232c53c6ebf77ff116a330047f541b6a941b6) | `` automatic update `` |
| [`5e5fc963`](https://github.com/nix-community/NUR/commit/5e5fc9633fb8157b82a0ceab57d2077ce1c8a454) | `` automatic update `` |
| [`c44685fc`](https://github.com/nix-community/NUR/commit/c44685fcc602f336fc88e8e136db39f3a1e9f51c) | `` automatic update `` |
| [`bbf1ea20`](https://github.com/nix-community/NUR/commit/bbf1ea20193bd5f8a643f3cd1dceda72be110e75) | `` automatic update `` |
| …

chore(flake/nur): `cc008520` -> `eef232c5`

---

flake.lock

| [`d163d7d0`](https://github.com/Gerg-L/spicetify-nix/commit/d163d7d0aaf0e467ac1fd40dc80e1f92849a8c9b) | `` CI update 2023-12-25 (#28) `` |

chore(flake/spicetify-nix): `ba6e4b47` -> `d163d7d0`

---

flake.lock

| [`cf0ae650`](https://github.com/nix-community/NUR/commit/cf0ae650c1a4f524a2b0e6856b18090271ab6c45) | `` automatic update `` |
| [`8bd85177`](https://github.com/nix-community/NUR/commit/8bd851779dbd15b260068fad890c8b0466499646) | `` automatic update `` |
| [`d53544ee`](https://github.com/nix-community/NUR/commit/d53544ee0290e290d2a6e1ea0b0493b49fa17ae4) | `` automatic update `` |
| [`25f99a7b`](https://github.com/nix-community/NUR/commit/25f99a7b75ed5193d0c8c4a467d7a4e005431347) | `` automatic update `` |
| …

chore(flake/nur): `46403c0c` -> `cf0ae650`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`b25b0643`](https://github.com/hyprwm/Hyprland/commit/b25b06430ba82ebd1977ad75b6cb1b86dd07cb8b) | `` groupbar: add egl context to refreshGroupBarGradients() (#4238) `` |
| [`5aab4a96`](https://github.com/hyprwm/Hyprland/commit/5aab4a96e3c01cce181b42d51140f7ed4e555d8b) | `` dispatchers: add tiled/floating to cyclenext ``                    |
| [`ff75f991`](https://github.com/hyprwm/Hyprland/commit/ff75f991a50d9e82bb4ee4cacace551225ef2038) | `` …

chore(flake/hyprland): `f013acc6` -> `b25b0643`

---

flake.lock

| Commit                                                                                                      | Message                                      |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`80679ea5`](https://github.com/nix-community/home-manager/commit/80679ea5074ab7190c4cce478c600057cfb5edae) | `` flake.lock: Update ``                     |
| [`015a36e9`](https://github.com/nix-community/home-manager/commit/015a36e9c737d97356eb1627d4d7c7bd84976b85) | `` oh-my-posh: enable nushell integration `` |
| [`d5a917ba`](https://github.com/nix-community/home-manager/commit/d5a917bab40daf4e5f82cd27162b8a6656d3beab) | `` Translate using Weblate (French) ``       |

chore(flake/home-manager): `16fcb967` -> `80679ea5`

---

flake.lock

| [`19c254d7`](https://github.com/nix-community/NUR/commit/19c254d7cbbc4977a0b1d4d8c17b3e4051d67a0e) | `` automatic update `` |
| [`99f14007`](https://github.com/nix-community/NUR/commit/99f1400741982af3ad7f13e21bfb9d7c9d6a6dc5) | `` automatic update `` |
| [`62220a13`](https://github.com/nix-community/NUR/commit/62220a1319013776c2f8aadda5d9c1047444862d) | `` automatic update `` |
| [`19aac52b`](https://github.com/nix-community/NUR/commit/19aac52be07bb798edd26840451ed32d77000205) | `` automatic update `` |
| …

chore(flake/nur): `cf0ae650` -> `19c254d7`

---

flake.lock

| Commit                                                                                           | Message                                   |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------- |
| [`4f99e805`](https://github.com/hyprwm/Hyprland/commit/4f99e805b900b72f5e2bed54a1a44d10c8d54771) | `` flake.lock: update ``                  |
| [`e2d04ae5`](https://github.com/hyprwm/Hyprland/commit/e2d04ae503ffc0c9f98d6ad5177d561f1af14636) | `` renderer: add option to blur popups `` |

chore(flake/hyprland): `b25b0643` -> `4f99e805`

---

flake.lock

| [`59425032`](https://github.com/nix-community/NUR/commit/5942503289336c3f00348f16dea95e54e4b43b42) | `` automatic update `` |
| [`9f82e437`](https://github.com/nix-community/NUR/commit/9f82e4376347bcd5be44dce39d45231e0618f642) | `` automatic update `` |
| [`1c3043eb`](https://github.com/nix-community/NUR/commit/1c3043ebc64237b37979a9878fb95c6eb7bb39a8) | `` automatic update `` |
| [`4c682e65`](https://github.com/nix-community/NUR/commit/4c682e6595400dd3cec580b326823cc0ddc48c38) | `` automatic update `` |
| …

chore(flake/nur): `19c254d7` -> `59425032`

---

flake.lock

| Commit                                                                                                       | Message              |
| ------------------------------------------------------------------------------------------------------------ | -------------------- |
| [`9147a422`](https://github.com/nix-community/emacs-overlay/commit/9147a4227e3db2c461dac05f9e0e7c586f852fb9) | `` Updated elpa ``   |
| [`d69ed241`](https://github.com/nix-community/emacs-overlay/commit/d69ed24198fbb8fc49deb92c727d1efc662b700f) | `` Updated nongnu `` |

chore(flake/emacs-overlay): `1c1dd489` -> `9147a422`

---

flake.lock

| Commit                                                                                                      | Message                                                              |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`3d599bd6`](https://github.com/nix-community/impermanence/commit/3d599bd65eb383bc36191ba39ed6084674b0d7b2) | `` Partial revert of 8d16ac97980b3641078dd7c11337bfaa77b45789 ``     |
| [`8d16ac97`](https://github.com/nix-community/impermanence/commit/8d16ac97980b3641078dd7c11337bfaa77b45789) | `` lib: Remove sanitizeName, replace usage with escapeSystemdPath `` |

chore(flake/impermanence): `123e9420` -> `3d599bd6`

---

flake.lock

| [`76bf3c9f`](https://github.com/nix-community/NUR/commit/76bf3c9fef2bf7bc97d9126c5866fb6c7939ca9a) | `` automatic update `` |
| [`d0e27ec3`](https://github.com/nix-community/NUR/commit/d0e27ec3d4fd51824f429a3828d071a556dbb413) | `` automatic update `` |
| [`18dafae6`](https://github.com/nix-community/NUR/commit/18dafae6daed11a4cba0b0ad3ff20094d2e6727d) | `` automatic update `` |
| [`52f3f4ea`](https://github.com/nix-community/NUR/commit/52f3f4ea1d6b27123b6cba210eb5e65c3e34500a) | `` automatic update `` |
| …

chore(flake/nur): `59425032` -> `76bf3c9f`

---

flake.lock

| Commit                                                                                           | Message                                              |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`2c2ff4b6`](https://github.com/hyprwm/Hyprland/commit/2c2ff4b61b774915089229ec43d4e05b690d38bd) | `` hyprctl: check only ISDEBUG in version (#3702) `` |

chore(flake/hyprland): `4f99e805` -> `2c2ff4b6`

---

flake.lock

| [`1da8a8ce`](https://github.com/chaotic-cx/nyx/commit/1da8a8ce3f56121920fb04ecbe5d49c60631052c) | `` Bump 20231226-1 (#507) `` |

chore(flake/chaotic): `778e166a` -> `1da8a8ce`

---

flake.lock

| Commit                                                                                          | Message                                                                  |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`80d0d925`](https://github.com/chaotic-cx/nyx/commit/80d0d925101f84a36db5c2b85cb69266e0d95391) | `` build(deps): bump actions/deploy-pages from 3 to 4 (#505) ``          |
| [`c3a9eeba`](https://github.com/chaotic-cx/nyx/commit/c3a9eeba64cd36b536728a88de4f4eee9228d5b0) | `` build(deps): bump actions/upload-pages-artifact from 2 to 3 (#506) `` |

chore(flake/chaotic): `1da8a8ce` -> `80d0d925`

---

flake.lock

| Commit                                                                                                       | Message            |
| ------------------------------------------------------------------------------------------------------------ | ------------------ |
| [`cf14f3f6`](https://github.com/nix-community/emacs-overlay/commit/cf14f3f673227631fda56daf01d87e983da76efb) | `` Updated elpa `` |

chore(flake/emacs-overlay): `9147a422` -> `cf14f3f6`

---

flake.lock

| [`a17e7841`](https://github.com/nix-community/NUR/commit/a17e7841c4d587aa3cb579b0fc156055b3dad82f) | `` automatic update `` |
| [`042eb455`](https://github.com/nix-community/NUR/commit/042eb455bd997f3e42d9cc375e040eedeee09bf1) | `` automatic update `` |
| [`14b7a9bb`](https://github.com/nix-community/NUR/commit/14b7a9bbe4279629c3474da4a1b5278f6f59bfcc) | `` automatic update `` |
| [`240f5923`](https://github.com/nix-community/NUR/commit/240f59239abdb11caf595230bf654c9c6b5c3ae2) | `` automatic update `` |
| …

chore(flake/nur): `76bf3c9f` -> `a17e7841`

---

flake.lock

| [`cbdb2d1a`](https://github.com/Gerg-L/spicetify-nix/commit/cbdb2d1ae3babf15cf3dbd575ab0aa277c8d944d) | `` CI update 2023-12-27 (#29) `` |

chore(flake/spicetify-nix): `d163d7d0` -> `cbdb2d1a`

---

flake.lock

| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`6cd82d94`](https://github.com/hyprwm/Hyprland/commit/6cd82d948f93be98d0fe5516722a9228f22315d1) | `` input: don't steal mouseDown from LS (#4260) ``                   |
| [`1ecd173c`](https://github.com/hyprwm/Hyprland/commit/1ecd173c7a77b5443473c03e32a119ff5b5a094b) | `` groupbar: remove extra border size from groupbars (#4262) ``      |
| [`7474c819`](https://github.com/hyprwm/Hyprland/commit/7474c819587a138b458e898847fbce93e1dd1d65) | `` …

chore(flake/hyprland): `191fa587` -> `6cd82d94`

---

flake.lock

| [`995ac3a4`](https://github.com/nix-community/emacs-overlay/commit/995ac3a4535431f4236df0e7e0b1c0f669cdb02d) | `` Updated flake inputs `` |
| [`c84fbd9b`](https://github.com/nix-community/emacs-overlay/commit/c84fbd9be553628e6295efb1cdb8c9d261e5bdff) | `` Updated elpa ``         |

chore(flake/emacs-overlay): `cf14f3f6` -> `995ac3a4`

---

flake.lock

| [`8d246efc`](https://github.com/nix-community/NUR/commit/8d246efce3b379865a4a745eec421c00d1a0cbb2) | `` automatic update `` |
| [`1830a38c`](https://github.com/nix-community/NUR/commit/1830a38cc171d76d5e86ca12ab1d70b23beb6110) | `` automatic update `` |
| [`19f42c15`](https://github.com/nix-community/NUR/commit/19f42c15735b6ba7a74b9fec2f56bd27fd0ffc29) | `` automatic update `` |
| [`ce591652`](https://github.com/nix-community/NUR/commit/ce59165220f83fe5eeb5e9ffbe2a6dfa5221ea5b) | `` automatic update `` |
| …

chore(flake/nur): `a17e7841` -> `8d246efc`

---

flake.lock

| Commit                                                                                                      | Message                                           |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`45854459`](https://github.com/nix-community/home-manager/commit/458544594ba7f0333cf5718045ee7a8eaf5de433) | `` gpg-agent: don't set a default for pinentry `` |
| [`2939d490`](https://github.com/nix-community/home-manager/commit/2939d490366251d9ed5a0bd938275c590a1d6fa6) | `` gh: test for existence of hosts file ``        |
| [`d1d95084`](https://github.com/nix-community/home-manager/commit/d1d950841d230490f308f5fcf8c0d4f2bd3f24a7) | `` gh: include version in …

chore(flake/home-manager): `80679ea5` -> `45854459`

---

flake.lock

| Commit                                                                                          | Message                                 |
| ----------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`40bd292c`](https://github.com/chaotic-cx/nyx/commit/40bd292c8593bbb0fc642fd283a9e2adaeeeabcb) | `` river_git: return to wlroots_0_16 `` |
| [`10ad0dea`](https://github.com/chaotic-cx/nyx/commit/10ad0dea4067e606810bfd258e4ee7135961d34f) | `` wlroots_git: update postOverrides `` |
| [`958f0d8f`](https://github.com/chaotic-cx/nyx/commit/958f0d8f09cee3b973d7dc54f24838595f2ed4f1) | `` nixpkgs: bump to 20231227 ``         |

chore(flake/chaotic): `80d0d925` -> `40bd292c`

---

flake.lock

| [`eacde6f9`](https://github.com/nix-community/NUR/commit/eacde6f9403222e20a511995f87cb30b3d445b10) | `` automatic update `` |
| [`ddd1a3db`](https://github.com/nix-community/NUR/commit/ddd1a3db18697d791c26c5f372948c1afe769e62) | `` automatic update `` |
| [`544f12df`](https://github.com/nix-community/NUR/commit/544f12dfd015f630784a654d31f2dcbad6af3d0d) | `` automatic update `` |
| [`9f98452a`](https://github.com/nix-community/NUR/commit/9f98452a12d5214423cd26a9b2d1c713654b1312) | `` automatic update `` |
| …

chore(flake/nur): `8d246efc` -> `eacde6f9`

---

flake.lock

| Commit                                                                                                       | Message            |
| ------------------------------------------------------------------------------------------------------------ | ------------------ |
| [`d72b6439`](https://github.com/nix-community/emacs-overlay/commit/d72b6439873ce66a1183d1b28e00a173e8a63ed7) | `` Updated elpa `` |

chore(flake/emacs-overlay): `995ac3a4` -> `d72b6439`

---

flake.lock

| [`de9b2c75`](https://github.com/nix-community/NUR/commit/de9b2c75516c957d9bcb8dbe37a8579147ce1fb2) | `` automatic update `` |
| [`c87af07c`](https://github.com/nix-community/NUR/commit/c87af07ce867559cc69406350b6b83a7b015bd25) | `` automatic update `` |
| [`0976440a`](https://github.com/nix-community/NUR/commit/0976440a978762424e00b29fc3896be286f7dcc4) | `` automatic update `` |
| [`9b29b6af`](https://github.com/nix-community/NUR/commit/9b29b6af5a3189c253f3d558942b6947e61be44b) | `` automatic update `` |
| …

chore(flake/nur): `eacde6f9` -> `de9b2c75`

---

flake.lock

| [`c5559571`](https://github.com/nix-community/NUR/commit/c55595716339a31cc05473395203f1444d546f3f) | `` automatic update `` |
| [`cee45814`](https://github.com/nix-community/NUR/commit/cee4581467953d2c1be3e57450fb0023d52f342e) | `` automatic update `` |
| [`d52c3b8e`](https://github.com/nix-community/NUR/commit/d52c3b8e906cc63efe311ae6277867f7b68f3bca) | `` automatic update `` |
| [`e8be9903`](https://github.com/nix-community/NUR/commit/e8be990308f12ae81ecf8a64df7ae1e015420911) | `` automatic update `` |
| …

chore(flake/nur): `de9b2c75` -> `c5559571`

---

flake.lock

| Commit                                                                                                      | Message                                                 |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`77c698fa`](https://github.com/nix-community/home-manager/commit/77c698fa4b3081b6019ad77d1bfedf06dbbde0db) | `` zsh: add support for zproof ``                       |
| [`30f9cdd6`](https://github.com/nix-community/home-manager/commit/30f9cdd69d1486a3d5cddaaabef7288d8ed389ee) | `` oh-my-posh: fix test under Darwin ``                 |
| [`ba6b7501`](https://github.com/nix-community/home-manager/commit/ba6b75011b44e85b1b755b6c423f85d0817645f7) | `` …

chore(flake/home-manager): `45854459` -> `77c698fa`

---

flake.lock

| Commit                                                                                          | Message                                     |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`028a52d8`](https://github.com/chaotic-cx/nyx/commit/028a52d83d609039bffe2c0f756e33f9b1faf1ee) | `` Bump 20231228-2 (#511) ``                |
| [`4e76c508`](https://github.com/chaotic-cx/nyx/commit/4e76c5089e39ce8b2bd26b981d8029b444a5e74b) | `` builder: create NYX_WD if necessary ``   |
| [`58e115d0`](https://github.com/chaotic-cx/nyx/commit/58e115d0a106fc110a2ec4e0ab3b687e1e77c920) | `` input-leap_git: new desktop unit name `` |
| [`8222f780`](https://github.com/chaotic-cx/nyx/commit/8222f780b56d18 …

chore(flake/chaotic): `40bd292c` -> `028a52d8`

---

flake.lock

| Commit                                                                                                       | Message                              |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------ |
| [`5205fb0c`](https://github.com/nix-community/emacs-overlay/commit/5205fb0c0ac5dfdb3f468b7581cd4fd4e289a4d9) | `` Updated elpa ``                   |
| [`71ccac2c`](https://github.com/nix-community/emacs-overlay/commit/71ccac2c15e3cef22b64de400df51132dbd45fd7) | `` Update github action version ``   |
| [`12a5452d`](https://github.com/nix-community/emacs-overlay/commit/12a5452d0edc6cb0e11391c069aef5538ebed31c) | `` Update nixpkgs-stable to 23.11 `` |
| …

chore(flake/emacs-overlay): `d72b6439` -> `a405e8be`

---

flake.lock

| [`df301563`](https://github.com/Gerg-L/spicetify-nix/commit/df301563422ac89c98985b90eb077f0a359d57c6) | `` CI update 2023-12-28 (#30) `` |

chore(flake/spicetify-nix): `cbdb2d1a` -> `df301563`

---

flake.lock

| [`4a8f8f53`](https://github.com/nix-community/NUR/commit/4a8f8f5355cb9d3334d311cb25fc6ab641b501dc) | `` automatic update `` |
| [`d33b3175`](https://github.com/nix-community/NUR/commit/d33b31759dd8e3bb431529c0937eb3692c09fa9a) | `` automatic update `` |
| [`89aaaf04`](https://github.com/nix-community/NUR/commit/89aaaf04fadc7ccfc0eedd64a07caead0cc724f4) | `` automatic update `` |
| [`a2d1b337`](https://github.com/nix-community/NUR/commit/a2d1b337dff56fdcd367543c81b83fd3691cd1d2) | `` automatic update `` |
| …

chore(flake/nur): `c5559571` -> `4a8f8f53`

---

flake.lock

| [`5d7c4dc2`](https://github.com/chaotic-cx/nyx/commit/5d7c4dc2cf946473179e4af3d1dea0320a730643) | `` Bump 20231229-1 (#512) `` |

chore(flake/chaotic): `028a52d8` -> `5d7c4dc2`

---

flake.lock

| [`e9e995a2`](https://github.com/nix-community/emacs-overlay/commit/e9e995a2f582217b7c4efe38415fafbbc06274d2) | `` Updated elpa ``         |
| [`86bc6834`](https://github.com/nix-community/emacs-overlay/commit/86bc6834b2e1adffca92c6faf0431c1a453cb73f) | `` Updated nongnu ``       |
| [`a99d70ad`](https://github.com/nix-community/emacs-overlay/commit/a99d70addcc094dfb2c93d74073850c11c0b5a7f) | `` Updated elpa ``         |
| [`ceea404c`](https://github.com/nix-community/emacs-overlay/commit/ceea404cfe880edf74592 …

chore(flake/emacs-overlay): `a405e8be` -> `e9e995a2`

---

flake.lock

| [`97bf8b7c`](https://github.com/Gerg-L/spicetify-nix/commit/97bf8b7cf56ed4e87fbdfe948d6d807bd378e0b2) | `` CI update 2023-12-29 (#31) `` |

chore(flake/spicetify-nix): `df301563` -> `97bf8b7c`

---

flake.lock

| Commit                                                                                                      | Message                                   |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`2aff324c`](https://github.com/nix-community/home-manager/commit/2aff324cf65f5f98f89d878c056b779466b17db8) | `` bemenu: add module ``                  |
| [`c48ae40d`](https://github.com/nix-community/home-manager/commit/c48ae40dbbb9193b4766c020bca116e127455ab9) | `` Translate using Weblate (German) ``    |
| [`df7f29a2`](https://github.com/nix-community/home-manager/commit/df7f29a231a483c88cbd00608db99634f854a8e1) | `` zoxide: fix use with recent Nushell `` |

chore(flake/home-manager): `77c698fa` -> `2aff324c`

---

flake.lock

| [`dbf41b39`](https://github.com/nix-community/emacs-overlay/commit/dbf41b3900117bb836118f7d3144bae6878a1c5e) | `` Updated elpa ``         |
| [`abc8913c`](https://github.com/nix-community/emacs-overlay/commit/abc8913c8eb39cca83df7a878195f284af88e3ee) | `` Updated flake inputs `` |
| [`285a626f`](https://github.com/nix-community/emacs-overlay/commit/285a626fe34c40d6f3e3f63f69f4ceb0cfc29e80) | `` Updated elpa ``         |

chore(flake/emacs-overlay): `e9e995a2` -> `dbf41b39`

---

flake.lock

| [`30100476`](https://github.com/Gerg-L/spicetify-nix/commit/301004764cf564cb82717e0b90936c6f92d863ac) | `` CI update 2023-12-30 (#32) `` |

chore(flake/spicetify-nix): `97bf8b7c` -> `30100476`

---

flake.lock

| Commit                                                                                          | Message                                           |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`f2d920f8`](https://github.com/chaotic-cx/nyx/commit/f2d920f8cbb50eb0f5f1ce7f7f29e5302da3df9d) | `` Bump 20231230-2 (#516) ``                      |
| [`a0a792ad`](https://github.com/chaotic-cx/nyx/commit/a0a792ad7050a49a29bf41bcfa918f5ad857eef5) | `` makeMicroarch: propagate pkgs.config (#515) `` |
| [`7aae2712`](https://github.com/chaotic-cx/nyx/commit/7aae2712f6cc7cdcd4bf9b289f7e061142bdb2b2) | `` nixpkgs: bump to 20231230 ``                   |

chore(flake/chaotic): `5d7c4dc2` -> `f2d920f8`

---

flake.lock

| [`3eaaeef7`](https://github.com/nix-community/emacs-overlay/commit/3eaaeef710b852dc55ef09b85cc438ca8c7f58b8) | `` Updated elpa ``         |
| [`e8ccf1b1`](https://github.com/nix-community/emacs-overlay/commit/e8ccf1b1586e022c8d5ac8667ae78c475f328061) | `` Updated nongnu ``       |
| [`3aa0c5fc`](https://github.com/nix-community/emacs-overlay/commit/3aa0c5fc7e1960258e5894fab855b8d7dc7809bb) | `` Updated flake inputs `` |
| [`fae6a53b`](https://github.com/nix-community/emacs-overlay/commit/fae6a53b30177995da026 …

chore(flake/emacs-overlay): `dbf41b39` -> `3eaaeef7`

---

flake.lock

| [`74bee334`](https://github.com/nix-community/NUR/commit/74bee334e8d3cadfe11fefea2ae426e0c25246d7) | `` automatic update `` |
| [`e3a2c227`](https://github.com/nix-community/NUR/commit/e3a2c227b7de1a72acd98028d8c0cb6f3e2cec60) | `` automatic update `` |
| [`482be435`](https://github.com/nix-community/NUR/commit/482be435861d41bbd09d9184ad15b29227d08e9a) | `` automatic update `` |
| [`007a7cfd`](https://github.com/nix-community/NUR/commit/007a7cfd5ce34ae23ff23b643e8f10c7c83ad5c1) | `` automatic update `` |
| …

chore(flake/nur): `4a8f8f53` -> `74bee334`

---

flake.lock

| [`7eca0601`](https://github.com/chaotic-cx/nyx/commit/7eca0601216c908ecaf6202b8fccaf6a70e947a8) | `` Bump 20231231-1 (#518) `` |

chore(flake/chaotic): `f2d920f8` -> `7eca0601`

---

flake.lock

| [`0fb5172a`](https://github.com/Gerg-L/spicetify-nix/commit/0fb5172a1ded159d8558a10d9606bc23cbe9937a) | `` CI update 2023-12-31 (#33) `` |

chore(flake/spicetify-nix): `30100476` -> `0fb5172a`

---

flake.lock

| [`d6510ce1`](https://github.com/nix-community/nix-index-database/commit/d6510ce144f5da7dd9bac667ba3d5a4946c00d11) | `` update packages.nix to release 2023-12-31-030821 `` |
| [`2b2e6047`](https://github.com/nix-community/nix-index-database/commit/2b2e6047a258a5522b2ec8e5e01107bea7ae2d0c) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `f4340c1a` -> `d6510ce1`

---

flake.lock

| [`90bc3134`](https://github.com/Gerg-L/spicetify-nix/commit/90bc31349a51e6e4727ce2db800680eca7980c1e) | `` CI update 2024-01-01 (#34) `` |

chore(flake/spicetify-nix): `0fb5172a` -> `90bc3134`

---

flake.lock

| [`7fd5b5b7`](https://github.com/nix-community/emacs-overlay/commit/7fd5b5b760ea726aa4c7670be7d93623936f9bf3) | `` Updated elpa ``         |
| [`e62cd63f`](https://github.com/nix-community/emacs-overlay/commit/e62cd63fa83d4dd9a81fe3695aa255e1d1d2ddbe) | `` Updated nongnu ``       |
| [`3750376a`](https://github.com/nix-community/emacs-overlay/commit/3750376a60b55eb5f2b62d7e89b34cde0c4f048e) | `` Updated flake inputs `` |
| [`75d58280`](https://github.com/nix-community/emacs-overlay/commit/75d582804c561bb16f726 …

chore(flake/emacs-overlay): `3eaaeef7` -> `7fd5b5b7`

---

flake.lock

| [`94e085b2`](https://github.com/chaotic-cx/nyx/commit/94e085b295da29074f5afd5ca274bc09428948a5) | `` nixpkgs: bump to 20240101 `` |
| [`31aaacef`](https://github.com/chaotic-cx/nyx/commit/31aaacef5779df9fe0615bc9c475f32d8b72d943) | `` Bump 20240101-1 (#519) ``    |

chore(flake/chaotic): `7eca0601` -> `94e085b2`

---

flake.lock

| Commit                                                                                         | Message                                                                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`e79af9e6`](https://github.com/NixOS/nixpkgs/commit/e79af9e68ddaa1c531aaa04eaf7082e3c426e6d5) | `` eigenmath: unstable-2023-12-12 -> unstable-2023-12-31 ``                              |
| [`2207adf4`](https://github.com/NixOS/nixpkgs/commit/2207adf4f7d9fa2535bdf77deccf59f74c102a21) | `` ncpamixer: 1.3.3.3 -> 1.3.7 ``                                                        |
| …

chore(flake/nixpkgs): `eae82ed7` -> `e5af05cb`

---

flake.lock

| Commit                                                                                                      | Message                                          |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`6e91c5df`](https://github.com/nix-community/home-manager/commit/6e91c5df192395753d8e6d55a0352109cb559790) | `` i3blocks: added configuration module ``       |
| [`f06edaf1`](https://github.com/nix-community/home-manager/commit/f06edaf18b119da7bb301eebbf87971bbb9fb162) | `` lorri: unbreak due to too tight sandboxing `` |
| [`b7ef79bc`](https://github.com/nix-community/home-manager/commit/b7ef79bcf47c002bd6ae81a52bd3f233297edbde) | `` Translate using Weblate …

chore(flake/home-manager): `2e8634c2` -> `6e91c5df`

---

flake.lock

| Commit                                                                                               | Message                      |
| ---------------------------------------------------------------------------------------------------- | ---------------------------- |
| [`0a78b7d0`](https://github.com/numtide/treefmt-nix/commit/0a78b7d032850d70d3c48b8122c19efab9cb600b) | `` ci: switch to buildbot `` |
| [`8a2b0b96`](https://github.com/numtide/treefmt-nix/commit/8a2b0b9643b835800a63bebc6b1b24232140c114) | `` nix: fix checks ``        |

chore(flake/treefmt-nix): `29613752` -> `31d9d210`

---

flake.lock

| Commit                                                                                                       | Message                                                                 |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`b61ae954`](https://github.com/nix-community/emacs-overlay/commit/b61ae954d6ccb73f9d650c107e5eef594861d7ee) | `` Revert "Merge pull request #378 from Vonfry/revert/disable-emacs" `` |
| [`8fec7971`](https://github.com/nix-community/emacs-overlay/commit/8fec797146cc0d2b309b2017feae0ae3d39db78c) | `` Revert "Updated emacs" ``                                            |
| …

chore(flake/emacs-overlay): `7fd5b5b7` -> `b61ae954`

---

flake.lock

| Commit                                                                                             | Message                        |
| -------------------------------------------------------------------------------------------------- | ------------------------------ |
| [`c4f5f8be`](https://github.com/nix-community/NUR/commit/c4f5f8beacb9819f19dbae1d1e09c2dfd404d542) | `` automatic update ``         |
| [`73591ab8`](https://github.com/nix-community/NUR/commit/73591ab82b405fb016505209a5976d728bf0bc74) | `` automatic update ``         |
| [`41ca16a8`](https://github.com/nix-community/NUR/commit/41ca16a8bbaf2c9b4987e12cad98629fb5f9cb86) | `` automatic update ``         |
| [`4756ed6d`](https://github.com/nix-community/NUR/commit/4756ed6d2e9ae5b23cc56a03b9871ba0e90134d7) | `` automatic …

chore(flake/nur): `c56ab874` -> `c4f5f8be`

---

flake.lock

| Commit                                                                                         | Message                                                                       |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`6f5773d2`](https://github.com/NixOS/nixpkgs/commit/6f5773d213a50584521986e08ada523fe1b0950e) | `` maintainers: update handle for dixslyf ``                                  |
| [`18a01f3f`](https://github.com/NixOS/nixpkgs/commit/18a01f3fd956de7fc6d32e5e241e949671e7e8bf) | `` haskellPackages: mark builds failing on hydra as broken ``                 |
| [`c60ed181`](https://github.com/NixOS/nixpkgs/commit/c60ed18170048087f93d0305f11e2 …

chore(flake/nixpkgs): `e5af05cb` -> `e2e36d8a`

---

flake.lock

| [`04009b77`](https://github.com/Gerg-L/spicetify-nix/commit/04009b77e3627feeb9491c412fffb8a32c404f7d) | `` CI update 2024-01-02 (#35) `` |

chore(flake/spicetify-nix): `90bc3134` -> `04009b77`

---

flake.lock

| [`9427caa6`](https://github.com/chaotic-cx/nyx/commit/9427caa6c634992766aca88b40abda785b9864c4) | `` Bump 20240102-1 (#520) `` |

chore(flake/chaotic): `94e085b2` -> `9427caa6`

---

flake.lock

| [`67fdb8e2`](https://github.com/Gerg-L/spicetify-nix/commit/67fdb8e2e66e48c2d853d04a907b4fde948e03ac) | `` CI update 2024-01-06 (#39) `` |

chore(flake/spicetify-nix): `a792afa6` -> `67fdb8e2`

---

flake.lock

| Commit                                                                                           | Message                                                   |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------- |
| [`7e033e48`](https://github.com/hyprwm/Hyprland/commit/7e033e48ace5406a9bc442f7d403f9ce3af193f3) | `` make: unbreak with non-GNU ln(1) after 78f9ba9fdd7e `` |
| [`d8dbdc4a`](https://github.com/hyprwm/Hyprland/commit/d8dbdc4a017e051b3dde2e93791e2495722bfa21) | `` main: Fix typo in std::cerr (#4359) ``                 |

chore(flake/hyprland): `d3acf8da` -> `7e033e48`

---

flake.lock

| [`3ada6ddb`](https://github.com/nix-community/emacs-overlay/commit/3ada6ddb60f9313cb2ac977106605e09c857ffec) | `` Updated melpa ``        |
| [`96a2809f`](https://github.com/nix-community/emacs-overlay/commit/96a2809fba7398dec610a5367c219d03dde07bf9) | `` Updated elpa ``         |
| [`4a17d22f`](https://github.com/nix-community/emacs-overlay/commit/4a17d22f425279621da0e9a3060031e5769ede0e) | `` Updated flake inputs `` |
| [`85ac1bf8`](https://github.com/nix-community/emacs-overlay/commit/85ac1bf8543d2e179d774 …

chore(flake/emacs-overlay): `6a88aa2f` -> `3ada6ddb`

---

flake.lock

| [`1ded0078`](https://github.com/nix-community/NUR/commit/1ded0078d049439eb4285c3d12d7e7892331db05) | `` automatic update `` |
| [`a822fe15`](https://github.com/nix-community/NUR/commit/a822fe1504c778894180e69c4e6ec89358781433) | `` automatic update `` |
| [`184fa856`](https://github.com/nix-community/NUR/commit/184fa8562d7c06507315534a2f578b59faae2877) | `` automatic update `` |
| [`031e5677`](https://github.com/nix-community/NUR/commit/031e567712130530a787ef20b9ab4f5a97b0bfeb) | `` automatic update `` |
| …

chore(flake/nur): `bcd4c2a8` -> `1ded0078`

---

flake.lock

| Commit                                                                                         | Message                                                                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`9121ed44`](https://github.com/NixOS/nixpkgs/commit/9121ed447f1f95b1d320e9d586eb72a01a787a8a) | `` python311Packages.dask-awkward: 2023.12.2 -> 2024.1.0 (#278949) ``           |
| [`6b0de30a`](https://github.com/NixOS/nixpkgs/commit/6b0de30acc8b85caf2389468bc6f4428aedde835) | `` tt-rss-theme-feedly: fix license ``                                          |
| [`46796330`](https://github.com/NixOS/nixpkgs/commit/46796330dc624cfb60d69 …

chore(flake/nixpkgs): `7a7cfff8` -> `0fa5a936`

---

flake.lock

| [`a4864705`](https://github.com/chaotic-cx/nyx/commit/a486470595d1c6414865b252dd96d988c0aad8f2) | `` Bump 20240106-1 (#528) `` |
| [`a8173214`](https://github.com/chaotic-cx/nyx/commit/a817321463a1a09b7df4e9c33cf0712a7665134a) | `` Bump 20240105-2 (#527) `` |
| [`94ec7904`](https://github.com/chaotic-cx/nyx/commit/94ec79046323db8cfcd603f289d4bbdd0bc71285) | `` Bump 20240105-1 (#526) `` |

chore(flake/chaotic): `b9df8e79` -> `a4864705`

---

flake.lock

| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`b240704b`](https://github.com/hyprwm/Hyprland/commit/b240704bee1d04eacc27654ea875cf6f15033c7c) | `` renderer: allow rendering multiple fullscreen windows in third fs pass `` |
| [`71166ef4`](https://github.com/hyprwm/Hyprland/commit/71166ef40b5f7640fcddb1951d84f0f086e198d2) | `` subsurfaceTree: update surface tree protocol feedback on map ``           |
| [`252aaaec`](https://github.com/hyprwm/Hyprland/commit/252aaaecfa3b57eb0782217 …

chore(flake/hyprland): `7e033e48` -> `b240704b`

---

flake.lock

| [`4118d09e`](https://github.com/nix-community/emacs-overlay/commit/4118d09e3b6613425c4d48f4aa4b2ed944e5b801) | `` Updated melpa ``        |
| [`dbcecbaa`](https://github.com/nix-community/emacs-overlay/commit/dbcecbaa6f0e7b59851c395a23dad531efe4b17d) | `` Updated flake inputs `` |
| [`58305b28`](https://github.com/nix-community/emacs-overlay/commit/58305b28029922b981f333229500e9ff34896c72) | `` Updated melpa ``        |
| [`2e9e4ff1`](https://github.com/nix-community/emacs-overlay/commit/2e9e4ff10f43677868875 …

chore(flake/emacs-overlay): `3ada6ddb` -> `4118d09e`

---

flake.lock

| Commit                                                                                               | Message                                                  |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`04f25d7b`](https://github.com/numtide/treefmt-nix/commit/04f25d7bec9fb29d2c3bacaa48a3304840000d36) | `` feat(programs): Add biome.js as a formatter (#147) `` |
| [`4e0914b1`](https://github.com/numtide/treefmt-nix/commit/4e0914b128272cd0fc25c2c63c05c1941e638984) | `` add asmfmt (#148) ``                                  |

chore(flake/treefmt-nix): `e434da61` -> `04f25d7b`

---

flake.lock

| [`416f676d`](https://github.com/Gerg-L/spicetify-nix/commit/416f676dae5d98b2c24040f603e5429cfe9f5655) | `` CI update 2024-01-10 (#42) `` |
| [`c261dd07`](https://github.com/Gerg-L/spicetify-nix/commit/c261dd078d06bc8c93a48789f89bd1defb06062a) | `` CI update 2024-01-09 (#41) `` |
| [`22f3ea69`](https://github.com/Gerg-L/spicetify-nix/commit/22f3ea693a75b6a2de7f81e83d37a3946d38850d) | `` CI update 2024-01-08 (#40) `` |

chore(flake/spicetify-nix): `67fdb8e2` -> `416f676d`

---

flake.lock

| Commit                                                                                             | Message                                  |
| -------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`0b34dc4f`](https://github.com/nix-community/NUR/commit/0b34dc4f624fe005afd64627f4a68d39315d650c) | `` automatic update ``                   |
| [`85ccecd5`](https://github.com/nix-community/NUR/commit/85ccecd524665a8ac2a043e9ced63f336476fe94) | `` automatic update ``                   |
| [`d2dc2f25`](https://github.com/nix-community/NUR/commit/d2dc2f25e0ea3ca5409555d4a96f78104b0be173) | `` automatic update ``                   |
| [`6586527c`](https://github.com/nix-community/NUR/commit/6586527c60f …

chore(flake/nur): `1ded0078` -> `0b34dc4f`

---

flake.lock

| [`e567934d`](https://github.com/chaotic-cx/nyx/commit/e567934dc30435bda4d97961423355108dac768d) | `` Bump 20240109-1 (#535) `` |

chore(flake/chaotic): `d53c445e` -> `e567934d`

---

flake.lock

| [`f46800ac`](https://github.com/nix-community/nix-index-database/commit/f46800ac5a6e9f892fe36e50821c5d85794ecc62) | `` update packages.nix to release 2024-01-07-030820 `` |
| [`5243a943`](https://github.com/nix-community/nix-index-database/commit/5243a943a37fa010e9d8f141c07a6870fde1060b) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `d6510ce1` -> `f46800ac`

---

flake.lock

| Commit                                                                                           | Message                                                                         |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------- |
| [`c4da4b02`](https://github.com/hyprwm/Hyprland/commit/c4da4b026deefd58f532353b64e9f17130e760ca) | `` layershell: Fix greedy mouse grab from keyboard_interactive layer (#4401) `` |
| [`babb9c07`](https://github.com/hyprwm/Hyprland/commit/babb9c07b045e21b5549cdcc3096d677e9db35b3) | `` swipe: Prevent hiding current workspace when swiping (#4417) ``              |
| [`6b92144f`](https://github.com/hyprwm/Hyprland/commit/6b92144f151 …

chore(flake/hyprland): `b240704b` -> `c4da4b02`

---

flake.lock

| [`53b4803d`](https://github.com/nix-community/emacs-overlay/commit/53b4803d6cb623b5b4e3540af99e1b356bbc7f30) | `` Updated melpa ``        |
| [`c11eac23`](https://github.com/nix-community/emacs-overlay/commit/c11eac23245ed3571df6eef40831422a3d49ad18) | `` Updated elpa ``         |
| [`8363635c`](https://github.com/nix-community/emacs-overlay/commit/8363635cc3d70d8869e3ead707eb01e03a203f78) | `` Updated melpa ``        |
| [`9e423719`](https://github.com/nix-community/emacs-overlay/commit/9e423719e0c85a4624813 …

chore(flake/emacs-overlay): `4118d09e` -> `53b4803d`

---

flake.lock

| Commit                                                                                                   | Message                                                                         |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`528a7d0c`](https://github.com/hercules-ci/flake-parts/commit/528a7d0cb9668fb633d0ce39fb2255c94e4f8250) | `` transposition: Explain incomplete usage of transposition ``                  |
| [`3a0408e3`](https://github.com/hercules-ci/flake-parts/commit/3a0408e3acf785354d8a9b4074b9d4dbb0a12852) | `` perSystem: Check that inputs'.<name> is a flake, for better error message `` |
| …

chore(flake/flake-parts): `88a2cd81` -> `07f63952`

---

flake.lock

| Commit                                                                                             | Message                       |
| -------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`f07c5379`](https://github.com/nix-community/NUR/commit/f07c53795b11a0fc780d77ae139c063601564b00) | `` automatic update ``        |
| [`9f8b664c`](https://github.com/nix-community/NUR/commit/9f8b664cca8d229db1d3958fcae35be23752ea52) | `` automatic update ``        |
| [`b1010ee8`](https://github.com/nix-community/NUR/commit/b1010ee867feb9da82e005fa4c991d933c6bf918) | `` automatic update ``        |
| [`265ac8e4`](https://github.com/nix-community/NUR/commit/265ac8e4270ed0b5292b528a7fc6fc5b36e3c729) | `` automatic update …

chore(flake/nur): `0b34dc4f` -> `f07c5379`

---

flake.lock

| Commit                                                                                                      | Message                                            |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`f2942f33`](https://github.com/nix-community/home-manager/commit/f2942f3385f1b35cc8a1abb03a45e29c9cb4d3c8) | `` Remove some formatting exceptions ``            |
| [`6217b735`](https://github.com/nix-community/home-manager/commit/6217b735988ef28fa07d9c4be92d06d5573defa3) | `` listenbrainz-mpd: use sdnotify when possible `` |
| [`0912d26b`](https://github.com/nix-community/home-manager/commit/0912d26b30332ae6a90e1b321ff88e80492127dd) | `` gh: only run migration …

chore(flake/home-manager): `93e804e7` -> `f2942f33`

---

flake.lock

| [`c25ae9c0`](https://github.com/Gerg-L/spicetify-nix/commit/c25ae9c05f50e5b75452d47e7380780f1489d15d) | `` CI update 2024-01-11 (#43) `` |

chore(flake/spicetify-nix): `416f676d` -> `c25ae9c0`

---

flake.lock

| Commit                                                                                         | Message                                                                     |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`4f8902a7`](https://github.com/NixOS/nixpkgs/commit/4f8902a71294581033dca051addd6c8f658e5280) | `` python311Packages.mpris-server: 0.8.1 -> 0.4.2; revert python-updates `` |
| [`f7340561`](https://github.com/NixOS/nixpkgs/commit/f734056102ac70e840f624326c582c35298e10a6) | `` stdenv: fix evaluation if !stdenv.cc.hasCC ``                            |
| [`7fcfa4f0`](https://github.com/NixOS/nixpkgs/commit/7fcfa4f0d60cc2b934dfb854ee067e6ce0cda …

chore(flake/nixpkgs): `7bb62b90` -> `a3ada00f`

---

flake.lock

| Commit                                                                                          | Message                                                  |
| ----------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`fe8c91cf`](https://github.com/chaotic-cx/nyx/commit/fe8c91cf0a6dd2ecafee39e838979bdefdc36612) | `` Bump 20240113-1 (#542) ``                             |
| [`a4e9fa07`](https://github.com/chaotic-cx/nyx/commit/a4e9fa0795880c3330d9f86cab466a7402d6d4f5) | `` libdrm_git: match drvName with the original (#541) `` |
| [`f2953305`](https://github.com/chaotic-cx/nyx/commit/f2953305e584b99e322ca9d0a4e53a76ce411e31) | `` Bump 20240112-1 (#540) ``                             |
| …

chore(flake/chaotic): `e567934d` -> `fe8c91cf`

---

flake.lock

| Commit                                                                                                       | Message                                               |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`4baba64e`](https://github.com/nix-community/emacs-overlay/commit/4baba64e8088c2cdbde661d6697d1fff3ba59f6d) | `` Manually update emacs-unstable for 29.2 release `` |
| [`39f23b18`](https://github.com/nix-community/emacs-overlay/commit/39f23b184ca4b191fbef420ba3f6f63a0895d68b) | `` Updated melpa ``                                   |
| [`9aaefc4e`](https://github.com/nix-community/emacs-overlay/commit/9aaefc4e713561e39a642e2a645777528b40fbdb) | `` Updated …

chore(flake/emacs-overlay): `0272f041` -> `4baba64e`

---

flake.lock

| [`4e695604`](https://github.com/nix-community/NUR/commit/4e69560402130d4ab721feac2eab1df26767359c) | `` automatic update `` |
| [`a72a322d`](https://github.com/nix-community/NUR/commit/a72a322d545b162fc45a3668db442356cf39503b) | `` automatic update `` |
| [`9a4b285d`](https://github.com/nix-community/NUR/commit/9a4b285d2da183fad6a7fefa5cd54dc68a20adf0) | `` automatic update `` |
| [`e312882c`](https://github.com/nix-community/NUR/commit/e312882c07d2cbc289e5c60c34a23b2a8cd1c880) | `` automatic update `` |
| …

chore(flake/nur): `679d0b5b` -> `4e695604`

---

flake.lock

| Commit                                                                                           | Message                                                     |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------- |
| [`c4365f20`](https://github.com/hyprwm/Hyprland/commit/c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a) | `` damage: use buffer_damage instead of effective_damage `` |
| [`307dd8f5`](https://github.com/hyprwm/Hyprland/commit/307dd8f511ab51dbf0900d16f29d66db8b619158) | `` input: partially revert #4401 ``                         |
| [`8342bac6`](https://github.com/hyprwm/Hyprland/commit/8342bac697b7abf036ec1c005af695fb8ab99b13) | `` Nix: disable fortify for devshell (#4463) …

chore(flake/hyprland): `3c964a9f` -> `c4365f20`

---

flake.lock

| Commit                                                                                                      | Message                                               |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`b84191db`](https://github.com/nix-community/home-manager/commit/b84191db127c16a92cbdf7f7b9969d58bb456699) | `` gh: add github gist to default credential hosts `` |
| [`d9c86968`](https://github.com/nix-community/home-manager/commit/d9c869681db7171a1ffb6f88489e4a5170fd0fb5) | `` sway: include cursor environment variables ``      |
| [`62856932`](https://github.com/nix-community/home-manager/commit/62856932af0c75c5be7a5ba23441e16a305423b3) | `` gradle: …

chore(flake/home-manager): `37d6eece` -> `b84191db`

---

flake.lock

| Commit                                                                                         | Message                                                                           |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`3d6a5ad6`](https://github.com/NixOS/nixpkgs/commit/3d6a5ad6049b9c55488b501b2a3b439586d7dd5e) | `` systemd-lib: fix automount generation after 9fbf82d9cb48 ``                    |
| [`2fba629f`](https://github.com/NixOS/nixpkgs/commit/2fba629f59f3de8cf773ad5fcac782e62a934faa) | `` coqPackages.QuickChick: 2.0.1 → 2.0.2 ``                                       |
| [`8a9a8c61`](https://github.com/NixOS/nixpkgs/commit/8a9a8c6104fbc …

chore(flake/nixpkgs): `5223d1f8` -> `cefcf19e`

---

flake.lock

| [`b30c6fe8`](https://github.com/Gerg-L/spicetify-nix/commit/b30c6fe8825b9a2b6a60509cdc0d57ba3323776f) | `` CI update 2024-01-18 (#47) `` |
| [`18b4af72`](https://github.com/Gerg-L/spicetify-nix/commit/18b4af72cc019fe973ebb985ee8d9ebd014eeabb) | `` CI update 2024-01-17 (#46) `` |

chore(flake/spicetify-nix): `8ed3356d` -> `b30c6fe8`

---

flake.lock

| [`d2a46921`](https://github.com/chaotic-cx/nyx/commit/d2a46921c9f290ece5fa8faf9b9bf8bc6227f1ac) | `` Bump 20240117-1 (#550) ``    |
| [`35518e29`](https://github.com/chaotic-cx/nyx/commit/35518e2947b9b640ee8a272404917d87dc8e087c) | `` nixpkgs: bump to 20240116 `` |

chore(flake/chaotic): `7bf8c1a4` -> `d2a46921`

---

flake.lock

| [`1de18dc5`](https://github.com/Gerg-L/spicetify-nix/commit/1de18dc5d6a103f07fdf2f2e0d1dc0f549686eab) | `` CI update 2024-01-20 (#49) `` |
| [`b50bfb3e`](https://github.com/Gerg-L/spicetify-nix/commit/b50bfb3efc1b0de2254676b956c10cdfabcb4af8) | `` CI update 2024-01-19 (#48) `` |

chore(flake/spicetify-nix): `b30c6fe8` -> `1de18dc5`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`4d403dac`](https://github.com/hyprwm/Hyprland/commit/4d403dac3244aab217fb9bf17a68e9a009fcadd8) | `` build: protocols: require wayland-protocols >= 1.32 ``             |
| [`f40e382f`](https://github.com/hyprwm/Hyprland/commit/f40e382fc6208d4fe2e53581ea27510cb62417dd) | `` crashreporter: skip first possibly cut off line in log tail ``     |
| [`b86ed02d`](https://github.com/hyprwm/Hyprland/commit/b86ed02d8ae7c955e1f42cc27a19fe18d82c50b7) | `` …

chore(flake/hyprland): `c4365f20` -> `4d403dac`

---

flake.lock

| Commit                                                                                             | Message                              |
| -------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`c39b293f`](https://github.com/nix-community/NUR/commit/c39b293ff897568c488372823230ec46b5b1b841) | `` automatic update ``               |
| [`26884905`](https://github.com/nix-community/NUR/commit/26884905e6e16577275d60f3985861eec185afa4) | `` automatic update ``               |
| [`65380eec`](https://github.com/nix-community/NUR/commit/65380eec6e39c81a064b44d43d706599c9d8320d) | `` automatic update ``               |
| [`eee17bb6`](https://github.com/nix-community/NUR/commit/eee17bb61f9a6dff151a595cbc2d75e …

chore(flake/nur): `4e695604` -> `c39b293f`

---

flake.lock

| Commit                                                                                                       | Message                                                                       |
| ------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`d3944caa`](https://github.com/nix-community/emacs-overlay/commit/d3944caa140aa7ee67b0238ec3a19a910e4a4050) | `` Updated emacs ``                                                           |
| [`e574b56c`](https://github.com/nix-community/emacs-overlay/commit/e574b56c87d7894f1cb14dacf38ff5c4a5082431) | `` elisp: Tangle org-mode files when used with defaultInitFile ``             |
| …

chore(flake/emacs-overlay): `4baba64e` -> `3566704a`

---

flake.lock

| Commit                                                                                                      | Message                                                             |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`9b378afa`](https://github.com/nix-community/home-manager/commit/9b378afae72cb07471e19aefc30e8e05ef2d7a61) | `` hyprland: change plugins settings generation ``                  |
| [`ce4b88c4`](https://github.com/nix-community/home-manager/commit/ce4b88c465d928f4f8b75d0920f1788d5b65ca94) | `` mcfly: add mcfly-fzf integration ``                              |
| [`2064348e`](https://github.com/nix-community/home-manager/commit/2064 …

chore(flake/home-manager): `b84191db` -> `9b378afa`

---

flake.lock

| Commit                                                                                               | Message                                   |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`8cd95da6`](https://github.com/numtide/treefmt-nix/commit/8cd95da6c30852adb2a06c4b6bdacfe8b64a0a35) | `` keep-sorted: init (#150) ``            |
| [`5861b733`](https://github.com/numtide/treefmt-nix/commit/5861b733f22ae4c192c7d207bae515d3bb77a6c0) | `` just: add as formatter ``              |
| [`093ad41d`](https://github.com/numtide/treefmt-nix/commit/093ad41d747c58bb5f6d2f649078febaf05b780c) | `` flake.lock: Update ``                  |
| …

chore(flake/treefmt-nix): `04f25d7b` -> `8cd95da6`

---

flake.lock

| Commit                                                                                         | Message                                                                           |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| [`81d9d36e`](https://github.com/NixOS/nixpkgs/commit/81d9d36ea9176b910425d9bee802f649a1bb2e05) | `` bsync: init at unstable-2023-12-21 ``                                          |
| [`e87c2dd2`](https://github.com/NixOS/nixpkgs/commit/e87c2dd226c07fed4105130bd1d82600338a9329) | `` graalvmCEPackages.truffleruby: 23.1.1 -> 23.1.2 ``                             |
| [`91029222`](https://github.com/NixOS/nixpkgs/commit/910292224c11b …

chore(flake/nixpkgs): `cefcf19e` -> `b4ee3c3c`

---

flake.lock

| Commit                                                                                               | Message                                                    |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [`9d458726`](https://github.com/numtide/treefmt-nix/commit/9d458726fed1cc00e48031bb7214dfa3c16b7a0f) | `` readme: document how to use custom formatters (#151) `` |

chore(flake/treefmt-nix): `8cd95da6` -> `9d458726`

---

flake.lock

| [`61d83fc5`](https://github.com/Gerg-L/spicetify-nix/commit/61d83fc5ab4c982e45c823d60069a1c49b1b2a38) | `` CI update 2024-01-23 (#52) `` |
| [`47cc7ad8`](https://github.com/Gerg-L/spicetify-nix/commit/47cc7ad8f0db7883af86dc180e9456a392b80428) | `` CI update 2024-01-22 (#51) `` |
| [`7af165ab`](https://github.com/Gerg-L/spicetify-nix/commit/7af165abeefa0a36fe4da13c74bc9a57554cf292) | `` CI update 2024-01-21 (#50) `` |

chore(flake/spicetify-nix): `1de18dc5` -> `61d83fc5`

---

flake.lock

| Commit                                                                                                      | Message                                    |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [`3df2a80f`](https://github.com/nix-community/home-manager/commit/3df2a80f3f85f91ea06e5e91071fa74ba92e5084) | `` zoxide: fix nushell 0.89 deprecation `` |
| [`3d0dc78e`](https://github.com/nix-community/home-manager/commit/3d0dc78e80031731240c979d87eed8e090d35439) | `` bemenu: allow floats in settings ``     |
| [`2d47379a`](https://github.com/nix-community/home-manager/commit/2d47379ad591bcb14ca95a90b6964b8305f6c913) | `` flake.lock: Update ``                   |
| …

chore(flake/home-manager): `9b378afa` -> `3df2a80f`

---

flake.lock

| [`8452fbba`](https://github.com/nix-community/NUR/commit/8452fbba02b789b9046356a9546db1a312a04804) | `` automatic update `` |
| [`084c9e5a`](https://github.com/nix-community/NUR/commit/084c9e5ac47b1da166bb485fe1ade830eb525f07) | `` automatic update `` |
| [`dbda804c`](https://github.com/nix-community/NUR/commit/dbda804cf36a64d698b1ef4df35ecabfa45442a6) | `` automatic update `` |
| [`1d21e45d`](https://github.com/nix-community/NUR/commit/1d21e45d0a555e48e3800dfae234c330361bfc08) | `` automatic update `` |
| …

chore(flake/nur): `c39b293f` -> `8452fbba`

---

flake.lock

| Commit                                                                                                    | Message                                              |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`80c76445`](https://github.com/nix-community/lanzaboote/commit/80c76445824791f31838e2626c35f6b139ac8581) | `` chore(deps): lock file maintenance ``             |
| [`7b5a9140`](https://github.com/nix-community/lanzaboote/commit/7b5a91408f14d49a69bd549172f9326a133e6306) | `` Revert "chore(deps): lock file maintenance" ``    |
| [`57e329ff`](https://github.com/nix-community/lanzaboote/commit/57e329ffde6278ab9adc7e2c6f94cd7b2da68807) | `` chore(deps): lock file …

chore(flake/lanzaboote): `5667bbc1` -> `3c3f6d1b`

---

flake.lock

| Commit                                                                                           | Message                                           |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`791e1b96`](https://github.com/hyprwm/Hyprland/commit/791e1b96b3cd12d56648b3ce7ffb0832eba2b37d) | `` internal: minor header cleanup ``              |
| [`02b4a9bd`](https://github.com/hyprwm/Hyprland/commit/02b4a9bdede8ab0336e2e7ac52b39cab36208bb4) | `` compositor: clarify common errors at launch `` |

chore(flake/hyprland): `4d403dac` -> `791e1b96`

---

flake.lock

| [`59ccbc5c`](https://github.com/chaotic-cx/nyx/commit/59ccbc5c133947d988d416c54add6ee62b10cccc) | `` Bump 20240123-1 (#558) ``    |
| [`faad4691`](https://github.com/chaotic-cx/nyx/commit/faad469131e78f786e8a8f5aaf94ed5c91457933) | `` Bump 20240122-1 (#557) ``    |
| [`85687e4e`](https://github.com/chaotic-cx/nyx/commit/85687e4ec7deb6e0aa2a7af1564d14dcb73b35aa) | `` failures: update ``          |
| [`b31ec348`](https://github.com/chaotic-cx/nyx/commit/b31ec348c7ee639a2e5765a35f78247c5e63dee2) | `` nixpkgs: bump to 20240122 …

chore(flake/chaotic): `18e8728c` -> `59ccbc5c`

---

flake.lock

| Commit                                                                                         | Message                                                                                   |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| [`07e7fcc4`](https://github.com/NixOS/nixpkgs/commit/07e7fcc46fcedf1f63c68c33a3b68ef521ebe2cf) | `` nixos/test-driver: black ``                                                            |
| [`c251abe9`](https://github.com/NixOS/nixpkgs/commit/c251abe9b45ec5d7883472586d4ca8d54ed28fb0) | `` virtualbox: Edit description ``                                                        |
| …

chore(flake/nixpkgs): `0e0b1629` -> `7ac72b3e`

---

flake.lock

| Commit                                                                                               | Message                   |
| ---------------------------------------------------------------------------------------------------- | ------------------------- |
| [`dfb3d0ef`](https://github.com/numtide/treefmt-nix/commit/dfb3d0efb0e141b28edd7182613c7ff5a9f87bae) | `` formatjson5: init ``   |
| [`e3282e0b`](https://github.com/numtide/treefmt-nix/commit/e3282e0b197d229a04c2ac1861c0a32c69d0bf83) | `` flake.lock: Update ``  |
| [`3139f18e`](https://github.com/numtide/treefmt-nix/commit/3139f18ee5cf16ea2b291a717c06f1e66df3e908) | `` add fourmolu (#153) `` |
| [`23f601bf`](https://github.com/numtide/treefmt-nix/commit/23f601bfdef75e21fe8854e24a043bb642201794) | `` add cljfmt (#152) ``   |

chore(flake/treefmt-nix): `9d458726` -> `fbef7c77`

---

flake.lock

| Commit                                                                                                       | Message                                                                        |
| ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------ |
| [`d8b97372`](https://github.com/nix-community/emacs-overlay/commit/d8b97372ee6f5024ef715da603e40a62cc1f9703) | `` Updated emacs ``                                                            |
| [`f33d4946`](https://github.com/nix-community/emacs-overlay/commit/f33d4946fa34a82e9c0580ab95813445b6659da3) | `` Updated elpa ``                                                             |
| …

chore(flake/emacs-overlay): `e2953343` -> `d8b97372`

---

flake.lock

| [`f842a134`](https://github.com/Gerg-L/spicetify-nix/commit/f842a1348f7f04e2a93d22bfec81f49923b9b0ec) | `` CI update 2024-01-27 (#56) `` |
| [`9ae31ca7`](https://github.com/Gerg-L/spicetify-nix/commit/9ae31ca7136965be977333b2ada37fb108951993) | `` CI update 2024-01-26 (#55) `` |
| [`c7db5485`](https://github.com/Gerg-L/spicetify-nix/commit/c7db5485125f8138fd3f22f001aeceb77fcca937) | `` CI update 2024-01-25 (#54) `` |
| [`3b33eeb0`](https://github.com/Gerg-L/spicetify-nix/commit/3b33eeb07c539e1bf39cb814187a1539a …

chore(flake/spicetify-nix): `61d83fc5` -> `f842a134`

---

flake.lock

| Commit                                                                                                      | Message                                                      |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`b2f56952`](https://github.com/nix-community/home-manager/commit/b2f56952074cb46e93902ecaabfb04dd93733434) | `` network-manager-applet: add XDG data directory ``         |
| [`690764d2`](https://github.com/nix-community/home-manager/commit/690764d2dcfccf01ddfc9f19220c88182339f40f) | `` firefox: Reimplement FF native messaging ``               |
| [`c7ce343d`](https://github.com/nix-community/home-manager/commit/c7ce343d9bf1a329056a4dd5b32ea8cc …

chore(flake/home-manager): `3df2a80f` -> `b2f56952`

---

flake.lock

| Commit                                                                                          | Message                                                           |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`05858851`](https://github.com/chaotic-cx/nyx/commit/05858851fcf6b687534c4a15d735b87309687cbd) | `` Bump 20240126-1 (#563) ``                                      |
| [`5c1df573`](https://github.com/chaotic-cx/nyx/commit/5c1df57391b39bf0880e7b3b9209e4f37e19fcde) | `` Bump 20240125-1 (#562) ``                                      |
| [`c6b611eb`](https://github.com/chaotic-cx/nyx/commit/c6b611eb70016efec73ec1d669089b8d5b331da1) | `` firefox_nightly: apply …

chore(flake/chaotic): `59ccbc5c` -> `05858851`

---

flake.lock

| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`e65f52bf`](https://github.com/hyprwm/Hyprland/commit/e65f52bf2d6abb001c402c8302ac7003da8cd06d) | `` Makefile: pass PREFIX to CMake ``                                          |
| [`c51b3fb0`](https://github.com/hyprwm/Hyprland/commit/c51b3fb06f48657bcf66a92eca3de04066a9c8ef) | `` events: ignore sending mouse enter to focused if a constraint is active `` |
| [`3ff59e7e`](https://github.com/hyprwm/Hyprland/commit/3ff59e7e1d859daa503 …

chore(flake/hyprland): `df990c80` -> `e65f52bf`

---

flake.lock

| Commit                                                                                                 | Message                                         |
| ------------------------------------------------------------------------------------------------------ | ----------------------------------------------- |
| [`fc080c51`](https://github.com/Misterio77/nix-colors/commit/fc080c51d2a219b40d886870e364243783ed5ca1) | `` deprecate schemeToYAML ``                    |
| [`f84b4255`](https://github.com/Misterio77/nix-colors/commit/f84b4255d2c635c97378af20fa704561b9247435) | `` rename kind to variant, colors to palette `` |
| [`0ed6b055`](https://github.com/Misterio77/nix-colors/commit/0ed6b055c3e033cd6cafaa731fbab0b0f6c1e48c) | `` allow custom logo colors (#46) ``            |
| …

chore(flake/nix-colors): `37227f27` -> `fc080c51`

---

flake.lock

| Commit                                                                                                      | Message                                                   |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`d634c3ab`](https://github.com/nix-community/home-manager/commit/d634c3abafa454551f2083b054cd95c3f287be61) | `` tealdeer: add option to toggle update on activation `` |
| [`4d54c29b`](https://github.com/nix-community/home-manager/commit/4d54c29bce71f8c261513e0662cc573d30f3e33e) | `` home-manager: remove the export of `run` ``            |
| [`ebba24a6`](https://github.com/nix-community/home-manager/commit/ebba24a6fefa3d749291be7192ef817736a10bd1) | …

chore(flake/home-manager): `b2f56952` -> `d634c3ab`

---

flake.lock

| Commit                                                                                         | Message                                                                                            |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| [`b1c8402d`](https://github.com/NixOS/nixpkgs/commit/b1c8402d71da3a61035b05d6f60b423e74a38b74) | `` vscode-extensions.serayuzgur.crates: 0.6.5 -> 0.6.6 ``                                          |
| [`cd5a7a3a`](https://github.com/NixOS/nixpkgs/commit/cd5a7a3ac9594456c63150e5d2fb43f7f4dd3073) | `` python311Packages.types-pyopenssl: 23.3.0.20240106 -> 24.0.0.20240130 ``                        | …

chore(flake/nixpkgs): `7ac72b3e` -> `632751bf`

---

flake.lock

| Commit                                                                                             | Message                                      |
| -------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`84c60a73`](https://github.com/ehllie/ez-configs/commit/84c60a73eba0b5405943580d52b1581de5b1ee7c) | `` systemBuilder: assign default hostName `` |

chore(flake/ez-configs): `fa75b68c` -> `84c60a73`

---

flake.lock

| [`c782f2a4`](https://github.com/nix-community/nix-index-database/commit/c782f2a4f6fc94311ab5ef31df2f1149a1856181) | `` update packages.nix to release 2024-01-28-030920 `` |
| [`2c1a58ea`](https://github.com/nix-community/nix-index-database/commit/2c1a58ea29af0bd3da947c6bb3e7a7704a2f972b) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `f8e04fbc` -> `c782f2a4`

---

flake.lock

| Commit                                                                                               | Message                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------- |
| [`c6153c2a`](https://github.com/numtide/treefmt-nix/commit/c6153c2a3ff4c38d231e3ae99af29b87f1df5901) | `` add csharpier (#155) `` |

chore(flake/treefmt-nix): `fbef7c77` -> `c6153c2a`

---

flake.lock

| Commit                                                                                          | Message                                               |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`204e506f`](https://github.com/chaotic-cx/nyx/commit/204e506f24843d95c415210920160894f1f35fe8) | `` scx: 0.1.5 -> 0.1.6 (#569) ``                      |
| [`557d6de2`](https://github.com/chaotic-cx/nyx/commit/557d6de26fd7c7c058e8d96695a54cd3dda341fa) | `` Bump 20240130-1 (#568) ``                          |
| [`b77fec37`](https://github.com/chaotic-cx/nyx/commit/b77fec371eae96f69cdaec9904307c5ffb921f14) | `` linux_cachyos-server: remove HDR patches (#567) `` |
| …

chore(flake/chaotic): `05858851` -> `204e506f`

---

flake.lock

| Commit                                                                                                   | Message                                          |
| -------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`b60b914a`](https://github.com/hercules-ci/flake-parts/commit/b60b914ac6f706bdb6e55c0eadeffa732a60bd16) | `` dev: Make the test slightly more sensible ``  |
| [`14114c56`](https://github.com/hercules-ci/flake-parts/commit/14114c563acab4cee2828aa8dad9036d617e1ea2) | `` templates: make flake-parts input explicit `` |
| [`238b0dc9`](https://github.com/hercules-ci/flake-parts/commit/238b0dc94b068a32530e8675425d22753d4af343) | `` apps: Add polyfill ``                         | …

chore(flake/flake-parts): `07f63952` -> `60c61400`

---

flake.lock

| [`2d69eefb`](https://github.com/nix-community/emacs-overlay/commit/2d69eefbcadbac97bda477477cd53c0ef815f436) | `` Updated emacs ``        |
| [`33e73c7e`](https://github.com/nix-community/emacs-overlay/commit/33e73c7e349b88ca393b5613c2b230cb82154eac) | `` Updated melpa ``        |
| [`45ee2dda`](https://github.com/nix-community/emacs-overlay/commit/45ee2dda7788c6f6adab331b904495f1fd95ae7e) | `` Updated flake inputs `` |
| [`6ed1948d`](https://github.com/nix-community/emacs-overlay/commit/6ed1948db6bf8b21ba2d2 …

chore(flake/emacs-overlay): `d8b97372` -> `2d69eefb`

---

flake.lock

| [`b65525c6`](https://github.com/Gerg-L/spicetify-nix/commit/b65525c685b8f5fa9651f971326256071132e222) | `` CI update 2024-01-31 (#60) `` |
| [`928165ad`](https://github.com/Gerg-L/spicetify-nix/commit/928165aded4b5f7049cc348c42b23820e304b1ca) | `` CI update 2024-01-30 (#59) `` |
| [`50fee704`](https://github.com/Gerg-L/spicetify-nix/commit/50fee70442296ff6c010493cb2e42f4a2a10a3a9) | `` CI update 2024-01-29 (#58) `` |
| [`dd15db63`](https://github.com/Gerg-L/spicetify-nix/commit/dd15db6383872606db74c85c0f765d3ac …

chore(flake/spicetify-nix): `f842a134` -> `b65525c6`

---

flake.lock

| Commit                                                                                                      | Message                                   |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`cd13c291`](https://github.com/nix-community/impermanence/commit/cd13c2917eaa68e4c49fea0ff9cada45440d7045) | `` Update README.org: fix broken links `` |

chore(flake/impermanence): `033643a4` -> `cd13c291`

---

flake.lock

| [`fab803d7`](https://github.com/nix-community/NUR/commit/fab803d7fa7e066ff6193fe40ba29d2e322835e1) | `` automatic update `` |
| [`7f970ae3`](https://github.com/nix-community/NUR/commit/7f970ae3b784af7e4505ae09780a56a13300a1be) | `` automatic update `` |
| [`9bc44fec`](https://github.com/nix-community/NUR/commit/9bc44feccbc86196b9b6d15e31d4a85efe1abcca) | `` automatic update `` |
| [`72aec480`](https://github.com/nix-community/NUR/commit/72aec4801b982219a2f4b98c41b1b97131917ce0) | `` automatic update `` |
| …

chore(flake/nur): `81804f94` -> `fab803d7`

---

flake.lock

| [`e4f17c81`](https://github.com/nix-community/emacs-overlay/commit/e4f17c81782040f23958ed74f1ab3a56b53df197) | `` Updated emacs ``        |
| [`bdc43452`](https://github.com/nix-community/emacs-overlay/commit/bdc43452fa833f8ea0c78cb6e2bb67e4642e58ca) | `` Updated emacs ``        |
| [`28256189`](https://github.com/nix-community/emacs-overlay/commit/282561890cbd396a3da4a494cd17f71d111f35bf) | `` Updated melpa ``        |
| [`3756fc6f`](https://github.com/nix-community/emacs-overlay/commit/3756fc6fdf12c19fa36bf …

chore(flake/emacs-overlay): `2d69eefb` -> `e4f17c81`

---

flake.lock

| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`7447be82`](https://github.com/hyprwm/Hyprland/commit/7447be822080fac5b8515a177773ec74b4d6c925) | `` hyprpm: fix crash on add plugin ``                                        |
| [`4644de22`](https://github.com/hyprwm/Hyprland/commit/4644de2269b06e60764cc788e39a18f44d1dd9b6) | `` keybinds: fix ignoremods with release ``                                  |
| [`3656045a`](https://github.com/hyprwm/Hyprland/commit/3656045ad88717fbc079c1e …

chore(flake/hyprland): `e65f52bf` -> `7447be82`

---

flake.lock

| [`1059ebf9`](https://github.com/nix-community/NUR/commit/1059ebf9a4a6ba47180c1616195ec807ecef6702) | `` automatic update `` |
| [`be1fa0de`](https://github.com/nix-community/NUR/commit/be1fa0de949b3cb8b79be80dd4cd10f7869bca45) | `` automatic update `` |
| [`6ad802fb`](https://github.com/nix-community/NUR/commit/6ad802fb5e81af60a6ea0c8645aa5a6fa0d7d6dd) | `` automatic update `` |
| [`dc7f899f`](https://github.com/nix-community/NUR/commit/dc7f899faa627af70bab354984ec652275a06af5) | `` automatic update `` |
| …

chore(flake/nur): `fab803d7` -> `1059ebf9`

---

flake.lock

| Commit                                                                                                      | Message                                             |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`4d53427b`](https://github.com/nix-community/home-manager/commit/4d53427bce7bf3d17e699252fd84dc7468afc46e) | `` xfconf: fix config loading ``                    |
| [`2db6a2a4`](https://github.com/nix-community/home-manager/commit/2db6a2a42930ffff0ffd690dec3f2c0b6f4fe66d) | `` docs: add style sheets and `scrubDerivations` `` |

chore(flake/home-manager): `d634c3ab` -> `4d53427b`

---

flake.lock

| [`471e7f90`](https://github.com/Gerg-L/spicetify-nix/commit/471e7f904a728ee3b40a32b3a09987a993c0bfda) | `` CI update 2024-02-02 (#62) `` |
| [`cec37dda`](https://github.com/Gerg-L/spicetify-nix/commit/cec37dda621a26b19716ccbca3f077755ccd12aa) | `` CI update 2024-02-01 (#61) `` |

chore(flake/spicetify-nix): `b65525c6` -> `471e7f90`

---

flake.lock

| Commit                                                                                          | Message                                             |
| ----------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`82f97c8a`](https://github.com/chaotic-cx/nyx/commit/82f97c8aa5b842be752e65933901cb20506a90bf) | `` jovian-chaotic: init (#574) ``                   |
| [`1b521b24`](https://github.com/chaotic-cx/nyx/commit/1b521b242c693d81855005e60ce82bea16e7a298) | `` ci/build: download "contents" separatedly ``     |
| [`28076944`](https://github.com/chaotic-cx/nyx/commit/28076944020e94d24fd3c9fb3566a7792686a882) | `` builder: download "contents" from cachix ``      |
| …

chore(flake/chaotic): `204e506f` -> `82f97c8a`

---

flake.lock

| [`eafd15bf`](https://github.com/Gerg-L/spicetify-nix/commit/eafd15bf5fa3f69609a5a99bc4ed2a529952b1a1) | `` CI update 2024-02-03 (#63) `` |

chore(flake/spicetify-nix): `471e7f90` -> `eafd15bf`

---

flake.lock

| Commit                                                                                                      | Message                                               |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`1ca21064`](https://github.com/nix-community/home-manager/commit/1ca210648a6ca9b957efde5da957f3de6b1f0c45) | `` tests: reduce closure sizes ``                     |
| [`880d9bc2`](https://github.com/nix-community/home-manager/commit/880d9bc2110f7cae59698f715b8ca42cdc53670c) | `` nix: fix generation of nix.conf for nix >= 2.20 `` |

chore(flake/home-manager): `4d53427b` -> `1ca21064`

---

flake.lock

| [`41b0349b`](https://github.com/nix-community/emacs-overlay/commit/41b0349b7219d5128acbf66d753e921f283cf1b2) | `` Updated emacs ``        |
| [`87dec8f9`](https://github.com/nix-community/emacs-overlay/commit/87dec8f92846c69fb17e4bddd66c160bd769cb38) | `` Updated melpa ``        |
| [`4eec5674`](https://github.com/nix-community/emacs-overlay/commit/4eec567404d4f12acd70674cbc3c319cf92fb43f) | `` Updated elpa ``         |
| [`16ca106d`](https://github.com/nix-community/emacs-overlay/commit/16ca106d2a6efab591b74 …

chore(flake/emacs-overlay): `e4f17c81` -> `41b0349b`

---

flake.lock

| [`a30b8d63`](https://github.com/nix-community/NUR/commit/a30b8d6366e36e256e803c14f81da4068bd134c2) | `` automatic update `` |
| [`c21b0244`](https://github.com/nix-community/NUR/commit/c21b0244a519085f2597ec75854ce3671e68e32d) | `` automatic update `` |
| [`2550466d`](https://github.com/nix-community/NUR/commit/2550466d4a700a11b4b1d37f0803eac56a5355a3) | `` automatic update `` |
| [`1932c503`](https://github.com/nix-community/NUR/commit/1932c50322b1c6e191a88da3436c6da6b18eca88) | `` automatic update `` |
| …

chore(flake/nur): `1059ebf9` -> `a30b8d63`

---

flake.lock

| Commit                                                                                           | Message                                                  |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------- |
| [`5d4ff60f`](https://github.com/hyprwm/Hyprland/commit/5d4ff60f535b65dc3db4cd0fb20e44c1f4360769) | `` hyprpm: fix invalid pkg-config path env in build ``   |
| [`504ebe1b`](https://github.com/hyprwm/Hyprland/commit/504ebe1b373726947a44fa2d6a68498d0edb85b6) | `` box: add missing include ``                           |
| [`cf1886ca`](https://github.com/hyprwm/Hyprland/commit/cf1886ca44c78de3424d96fd18023eb0db759af6) | `` renderer: avoid unnecessary gpu resource deletions `` | …

chore(flake/hyprland): `7447be82` -> `5d4ff60f`

---

flake.lock

| [`0b6749ef`](https://github.com/NixOS/nixpkgs/commit/0b6749ef23f500b26ebc207f8a8d2a961964fc96) | `` budgie.budgie-desktop: 10.9 -> 10.9.1 ``                                |
| [`dec6392b`](https://github.com/NixOS/nixpkgs/commit/dec6392bc29e34e23f21451b58f629930c6ddc78) | `` nixos/tests/zigbee2mqtt: test against dummy serial device ``            |
| [`165326d2`](https://github.com/NixOS/nixpkgs/commit/165326d2ca6e8bda65c06fd3166eeacebc703e05) …

chore(flake/nixpkgs): `5c5bca5a` -> `4f301350`

---

flake.lock

| Commit                                                                                         | Message                                                                                                         |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- |
| [`9a113b42`](https://github.com/NixOS/nixpkgs/commit/9a113b42b3b15eafa91a027bd9fb9fd69fa6ed96) | `` nixos/version: add ANSI_COLOR ``                                                                             |
| [`c9223ea4`](https://github.com/NixOS/nixpkgs/commit/c9223ea44c223379f22a091c57700fa378a758df) | `` nwjs: 0.83.0 -> 0.84.0 `` …

chore(flake/nixpkgs): `4f301350` -> `9a113b42`

---

flake.lock

| Commit                                                                                                      | Message                                                   |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`f99eace7`](https://github.com/nix-community/home-manager/commit/f99eace7c167b8a6a0871849493b1c613d0f1b80) | `` jetbrains-remote: add module ``                        |
| [`f65dcd6c`](https://github.com/nix-community/home-manager/commit/f65dcd6c15db0fc2045d56ef8fdf4a03aa52e81f) | `` neomutt: fix crypt_use_gpgme in newer versions ``      |
| [`7b4ea8d8`](https://github.com/nix-community/home-manager/commit/7b4ea8d82fdeaa71ab942a8a8f6f8add8afdfad0) | …

chore(flake/home-manager): `1ca21064` -> `f99eace7`

---

flake.lock

| Commit                                                                                           | Message                                                                             |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------- |
| [`a6ccd361`](https://github.com/hyprwm/Hyprland/commit/a6ccd36147109d5cb2981122595f06ae93999b55) | `` screencopy: move monitor verif check to the proper place ``                      |
| [`3d9ca638`](https://github.com/hyprwm/Hyprland/commit/3d9ca6381df1cdbf1731d7e2b39ea3f7574fce1e) | `` crashreporter: fix logging of function data (#4632) ``                           |
| …

chore(flake/hyprland): `5d4ff60f` -> `a6ccd361`

---

flake.lock

| Commit                                                                                               | Message                     |
| ---------------------------------------------------------------------------------------------------- | --------------------------- |
| [`ac599dab`](https://github.com/numtide/treefmt-nix/commit/ac599dab59a66304eb511af07b3883114f061b9d) | `` docs: fix typo (#157) `` |

chore(flake/treefmt-nix): `c6153c2a` -> `ac599dab`

---

flake.lock

| [`3e3dad28`](https://github.com/nix-community/nix-index-database/commit/3e3dad2808379c522138e2e8b0eb73500721a237) | `` update packages.nix to release 2024-02-04-030719 `` |
| [`e260ddfd`](https://github.com/nix-community/nix-index-database/commit/e260ddfd7ab5d360172870b9dfb0fa15093cdb29) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `c782f2a4` -> `3e3dad28`

---

flake.lock

| Commit                                                                                                       | Message                            |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------- |
| [`ccaf5772`](https://github.com/nix-community/emacs-overlay/commit/ccaf577227e5a64f95c03d66b6ac50879b4a3521) | `` Updated emacs ``                |
| [`b1b55ae0`](https://github.com/nix-community/emacs-overlay/commit/b1b55ae037f900793dcb74d87b18b6ba5d8c5d38) | `` Updated melpa ``                |
| [`d28950bc`](https://github.com/nix-community/emacs-overlay/commit/d28950bce310568129d58b74639e73c7d3e73a78) | `` Updated elpa ``                 |
| …

chore(flake/emacs-overlay): `41b0349b` -> `ccaf5772`

---

flake.lock

| [`fe2db390`](https://github.com/Gerg-L/spicetify-nix/commit/fe2db3900d0fb355a521892cf3c6e45399089fe3) | `` CI update 2024-02-08 (#66) `` |
| [`a96d81b3`](https://github.com/Gerg-L/spicetify-nix/commit/a96d81b3922ff134afbd2ea4963e39564066fb4b) | `` CI update 2024-02-07 (#65) `` |
| [`a0498cce`](https://github.com/Gerg-L/spicetify-nix/commit/a0498ccea68a497b57c0807b1a4787c0526770fa) | `` CI update 2024-02-05 (#64) `` |

chore(flake/spicetify-nix): `eafd15bf` -> `fe2db390`

---

flake.lock

| [`3a315bbd`](https://github.com/nix-community/NUR/commit/3a315bbd42ead8a1bafa90e8c3d14c43c80db912) | `` automatic update `` |
| [`a0e18535`](https://github.com/nix-community/NUR/commit/a0e185354efd1ef8701224bbe1fc68c532436dc1) | `` automatic update `` |
| [`d744fce5`](https://github.com/nix-community/NUR/commit/d744fce52b50d53a3bc77720125f281d6c682f37) | `` automatic update `` |
| [`2f014699`](https://github.com/nix-community/NUR/commit/2f014699cc4a8b9f42b48c9d79f3a69654ae3501) | `` automatic update `` |
| …

chore(flake/nur): `20260b5a` -> `3a315bbd`

---

flake.lock

| [`a04e54da`](https://github.com/Gerg-L/spicetify-nix/commit/a04e54da49a3e0d6d1a8c4a0e5b059c206868198) | `` CI update 2024-02-10 (#68) `` |
| [`abe212ac`](https://github.com/Gerg-L/spicetify-nix/commit/abe212ac652354a6bc519effae917f51e64a1678) | `` CI update 2024-02-09 (#67) `` |

chore(flake/spicetify-nix): `fe2db390` -> `a04e54da`

---

flake.lock

| Commit                                                                                           | Message                                                                  |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------ |
| [`e4bb5fa4`](https://github.com/hyprwm/Hyprland/commit/e4bb5fa4af1a6c36aab1c28651b5403dc4952f93) | `` input: focus monitor on mouse down ``                                 |
| [`cb258c82`](https://github.com/hyprwm/Hyprland/commit/cb258c82f4fa3276ad9b2e2dfc1243e8ee683b2c) | `` assets: update tetrahedra by honkadaloonga ``                         |
| [`658f718f`](https://github.com/hyprwm/Hyprland/commit/658f718fa3b2e08653493a00aeaa670a41d19c8 …

chore(flake/hyprland): `a6ccd361` -> `e4bb5fa4`

---

flake.lock

| Commit                                                                                                      | Message                                                                      |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`bfd0ae29`](https://github.com/nix-community/home-manager/commit/bfd0ae29a86eff4603098683b516c67e22184511) | `` emacs: use `overrideScope` instead of `overrideScope'` ``                 |
| [`d1d6ca9b`](https://github.com/nix-community/home-manager/commit/d1d6ca9b6552fc93032b76661c83061f1cd4e6e8) | `` flake.lock: Update ``                                                     |
| …

chore(flake/home-manager): `f99eace7` -> `bfd0ae29`

---

flake.lock

| Commit                                                                                          | Message                                                                       |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`1b53f92c`](https://github.com/chaotic-cx/nyx/commit/1b53f92c20a7e4d7ca97ad5e06ec0d6ade776450) | `` yuzu-early-access_git: fix env & pin ffmpeg to upstream version ``         |
| [`7df770b0`](https://github.com/chaotic-cx/nyx/commit/7df770b05a6ffc769adee316f3b166a08b24568b) | `` gamescope_git: rebase ``                                                   |
| [`e386edf8`](https://github.com/chaotic-cx/nyx/commit/e386edf84c261fb6bf18b44f …

chore(flake/chaotic): `aba46bb7` -> `1b53f92c`

---

flake.lock

| [`22cce99b`](https://github.com/nix-community/emacs-overlay/commit/22cce99b0abb79c5d00583f6f82e823b2bdb131b) | `` Updated emacs ``        |
| [`98d2b370`](https://github.com/nix-community/emacs-overlay/commit/98d2b3707652c8638046a7578f30924529965b90) | `` Updated melpa ``        |
| [`95acf329`](https://github.com/nix-community/emacs-overlay/commit/95acf3297bda934c1ec5260e18ffea39f05bbf3a) | `` Updated emacs ``        |
| [`06528d90`](https://github.com/nix-community/emacs-overlay/commit/06528d90408b8c86f6d70 …

chore(flake/emacs-overlay): `ccaf5772` -> `22cce99b`

---

flake.lock

| [`0cb43457`](https://github.com/nix-community/nix-index-database/commit/0cb4345704123492e6d1f1068629069413c80de0) | `` update packages.nix to release 2024-02-11-030837 `` |
| [`2fc7cf56`](https://github.com/nix-community/nix-index-database/commit/2fc7cf56050f0d3e1f793cfee0f88f894870035e) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `3e3dad28` -> `0cb43457`

---

flake.lock

| [`3c0112ec`](https://github.com/nix-community/emacs-overlay/commit/3c0112ec21770085a50d24a899d1644bb238cfef) | `` Updated emacs ``        |
| [`ad4a3a32`](https://github.com/nix-community/emacs-overlay/commit/ad4a3a3271d161eedf9e85f851be60b8a361bcf2) | `` Updated melpa ``        |
| [`1e43a6cb`](https://github.com/nix-community/emacs-overlay/commit/1e43a6cba24ba1da009fd358ddde947c9df07afa) | `` Updated emacs ``        |
| [`6e3c4ba0`](https://github.com/nix-community/emacs-overlay/commit/6e3c4ba04fd2db2b3ef73 …

chore(flake/emacs-overlay): `22cce99b` -> `3c0112ec`

---

flake.lock

| [`c0479fde`](https://github.com/Gerg-L/spicetify-nix/commit/c0479fde680d721a750e55a0ccdae52e9641b4d4) | `` CI update 2024-02-11 (#69) `` |

chore(flake/spicetify-nix): `a04e54da` -> `c0479fde`

---

flake.lock

| [`8097ddfa`](https://github.com/nix-community/NUR/commit/8097ddfab1b83c26b2f828c069803e3ee6159bd8) | `` automatic update `` |
| [`7efd32ca`](https://github.com/nix-community/NUR/commit/7efd32ca3874101a3f16c06e5aade38153ca4fc7) | `` automatic update `` |
| [`b1858530`](https://github.com/nix-community/NUR/commit/b1858530c4ecc35c6b6f29319d69aab2948a8912) | `` automatic update `` |
| [`4acc83ad`](https://github.com/nix-community/NUR/commit/4acc83adfbe8844fdab0b3cc916394c4391379ea) | `` automatic update `` |
| …

chore(flake/nur): `3a315bbd` -> `8097ddfa`

---

flake.lock

| Commit                                                                                           | Message                                                                           |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------- |
| [`06087914`](https://github.com/hyprwm/Hyprland/commit/06087914807f88d2a9fc76c8108985f6327598de) | `` dwindle: round wbox before setting ``                                          |
| [`2a002f31`](https://github.com/hyprwm/Hyprland/commit/2a002f31e4077ff6dd20a7116e372712e3b4e7f8) | `` renderer: don't set solitary on present notifications ``                       |
| …

chore(flake/hyprland): `e4bb5fa4` -> `06087914`

---

flake.lock

| [`763c614a`](https://github.com/nix-community/emacs-overlay/commit/763c614a4cce4296941b44dece54390dd108b781) | `` Updated emacs ``        |
| [`b40877f8`](https://github.com/nix-community/emacs-overlay/commit/b40877f8ce5a3c4720e6d1e965bd65d9e9e1be3c) | `` Updated flake inputs `` |
| [`97d761e4`](https://github.com/nix-community/emacs-overlay/commit/97d761e40d1f82a982274fcdbef90c4316669052) | `` Updated emacs ``        |
| [`385de3ad`](https://github.com/nix-community/emacs-overlay/commit/385de3ad948bc01498b69 …

chore(flake/emacs-overlay): `3c0112ec` -> `763c614a`

---

flake.lock

| [`2d8b70d9`](https://github.com/Gerg-L/spicetify-nix/commit/2d8b70d9a078676412fbd40df63f3a556e359446) | `` CI update 2024-02-14 (#72) `` |
| [`1759b6d9`](https://github.com/Gerg-L/spicetify-nix/commit/1759b6d9c2f0b58b59b9973e2ec71d6fc5529594) | `` CI update 2024-02-13 (#71) `` |
| [`892e3522`](https://github.com/Gerg-L/spicetify-nix/commit/892e3522a0220784ee8ba1d2b68c794f0c510cc9) | `` CI update 2024-02-12 (#70) `` |

chore(flake/spicetify-nix): `c0479fde` -> `2d8b70d9`

---

flake.lock

| Commit                                                                                                 | Message                                                |
| ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------ |
| [`b01f0240`](https://github.com/Misterio77/nix-colors/commit/b01f024090d2c4fc3152cd0cf12027a7b8453ba1) | `` Add textMateThemeFromScheme to lib-contrib (#39) `` |

chore(flake/nix-colors): `fc080c51` -> `b01f0240`

---

flake.lock

| [`e8622366`](https://github.com/nix-community/NUR/commit/e8622366c2f04b2c09f00dd781188075ada2cb33) | `` automatic update `` |
| [`56322db4`](https://github.com/nix-community/NUR/commit/56322db4d90c22d91274c173ef21d9aa3df37d8d) | `` automatic update `` |
| [`53747802`](https://github.com/nix-community/NUR/commit/537478022fa6267cc9dc6d5b25a2a1e3fa06f48d) | `` automatic update `` |
| [`aa59c0f6`](https://github.com/nix-community/NUR/commit/aa59c0f62204dedf092ee8a46311a659ea010ea2) | `` automatic update `` |
| …

chore(flake/nur): `8097ddfa` -> `e8622366`

---

flake.lock

| Commit                                                                                                      | Message                                                  |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`043ba285`](https://github.com/nix-community/home-manager/commit/043ba285c6dc20f36441d48525402bcb9743c498) | `` tests: add basic integration tests ``                 |
| [`7889bfb4`](https://github.com/nix-community/home-manager/commit/7889bfb4752b27c83c8ae9ca45f63b77fff7ef7b) | `` home-manager: overrideable URLs in generated flake `` |
| [`354643e6`](https://github.com/nix-community/home-manager/commit/354643e6c1ce0762d498e5e676e7970922c89208) | `` …

chore(flake/home-manager): `bfd0ae29` -> `043ba285`

---

flake.lock

| Commit                                                                                          | Message                                                                   |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------- |
| [`71d83160`](https://github.com/chaotic-cx/nyx/commit/71d83160fc19ac93c9477bbbcef0e21fa3c827ae) | `` Revert "mesa_git: 20240212091947-72886cb -> 20240213094732-29a6beb" `` |
| [`116927dc`](https://github.com/chaotic-cx/nyx/commit/116927dc30e4c60bd4ec2721c6ff8425924eb622) | `` Bump 20240213-1 (#588) ``                                              |
| [`8eda9a93`](https://github.com/chaotic-cx/nyx/commit/8eda9a93237357f6fc188024eff4ee0b32d19d6b …

chore(flake/chaotic): `1b53f92c` -> `71d83160`

---

flake.lock

| Commit                                                                                                     | Message                                                                          |
| ---------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`88d8f741`](https://github.com/privatevoid-net/nix-super/commit/88d8f74152a9f8d94077066f5edecd0127733a38) | `` feat: add reject-flake-config setting to reject all nix config from flakes `` |

chore(flake/nix-super): `661b025c` -> `924eb112`

---

flake.lock

| Commit                                                                                             | Message                         |
| -------------------------------------------------------------------------------------------------- | ------------------------------- |
| [`2593837c`](https://github.com/nix-community/NUR/commit/2593837ca8fc3abd462bac0ac002eec451001418) | `` automatic update ``          |
| [`31ba97e3`](https://github.com/nix-community/NUR/commit/31ba97e37ec8c14f8ec2f2baea1a31f0c9abfb3f) | `` automatic update ``          |
| [`339713c9`](https://github.com/nix-community/NUR/commit/339713c9f42013858739ea18aac30220f22dde08) | `` automatic update ``          |
| [`af0850f5`](https://github.com/nix-community/NUR/commit/af0850f5cf31764f16dd991fa75912ca707ee64d) | `` …

chore(flake/nur): `e8622366` -> `2593837c`

---

flake.lock

| [`4887a3bf`](https://github.com/nix-community/emacs-overlay/commit/4887a3bf368f7ba9fe2640c23ce08646918d4414) | `` Updated emacs ``        |
| [`b0df43bf`](https://github.com/nix-community/emacs-overlay/commit/b0df43bf17931a6b870194770340d268fe7412c2) | `` Updated melpa ``        |
| [`609ba40f`](https://github.com/nix-community/emacs-overlay/commit/609ba40f7e228e70b102c14b084e63445decae0b) | `` Updated elpa ``         |
| [`1572bc00`](https://github.com/nix-community/emacs-overlay/commit/1572bc00e95555e6c4743 …

chore(flake/emacs-overlay): `763c614a` -> `4887a3bf`

---

flake.lock

| Commit                                                                                           | Message                                                                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------- |
| [`fbf5ba87`](https://github.com/hyprwm/Hyprland/commit/fbf5ba87ce57752653f3bebf6e2be090c702836e) | `` shaders: use highp for fragments ``                                           |
| [`a8dae8f5`](https://github.com/hyprwm/Hyprland/commit/a8dae8f5e198327e5de8508d860234089f31e272) | `` socket2: `monitoraddedv2` IPC event for monitor description and id (#4646) `` |
| [`a42b984f`](https://github.com/hyprwm/Hyprland/commit/a42b984 …

chore(flake/hyprland): `06087914` -> `fbf5ba87`

---

flake.lock

| [`ac4a65c0`](https://github.com/Gerg-L/spicetify-nix/commit/ac4a65c0cf78138ef839c9f650a2f35216e68506) | `` CI update 2024-02-16 (#74) `` |
| [`b53c0fe5`](https://github.com/Gerg-L/spicetify-nix/commit/b53c0fe5120400cffb597d799fbe55168539437d) | `` CI update 2024-02-15 (#73) `` |

chore(flake/spicetify-nix): `2d8b70d9` -> `ac4a65c0`

---

flake.lock

| [`a1350f6b`](https://github.com/chaotic-cx/nyx/commit/a1350f6b55e923454d646dbff416e1246786484a) | `` Bump 20240214-1 (#589) `` |

chore(flake/chaotic): `71d83160` -> `a1350f6b`

---

flake.lock

| Commit                                                                                                       | Message              |
| ------------------------------------------------------------------------------------------------------------ | -------------------- |
| [`c3d788a4`](https://github.com/nix-community/emacs-overlay/commit/c3d788a49ce7f930194fa1b8e4afef65a34d6cf3) | `` Updated melpa ``  |
| [`33751916`](https://github.com/nix-community/emacs-overlay/commit/337519167c4ef503a9617a35e95322b10e756f6c) | `` Updated elpa ``   |
| [`c7090a11`](https://github.com/nix-community/emacs-overlay/commit/c7090a11f393071dcfd8a14ef5d803d30f477016) | `` Updated nongnu `` |

chore(flake/emacs-overlay): `4887a3bf` -> `c3d788a4`

---

flake.lock

| [`bacaa8bc`](https://github.com/nix-community/NUR/commit/bacaa8bc5fd5a6b8c22004ea3851d7485c9c40b6) | `` automatic update `` |
| [`8098cc42`](https://github.com/nix-community/NUR/commit/8098cc42a61d691ec6226b4df2915d720895e0af) | `` automatic update `` |
| [`d966121a`](https://github.com/nix-community/NUR/commit/d966121a8014132fc567dcc058f614a478b6826f) | `` automatic update `` |
| [`9b37d872`](https://github.com/nix-community/NUR/commit/9b37d872c4e92ded39283bfa5984eb51a6b3a3a9) | `` automatic update `` |
| …

chore(flake/nur): `2593837c` -> `bacaa8bc`

---

flake.lock

| [`06d03b87`](https://github.com/Gerg-L/spicetify-nix/commit/06d03b879c9a0a6577bec739bf99a551ca0c5f6b) | `` CI update 2024-02-17 (#75) `` |

chore(flake/spicetify-nix): `ac4a65c0` -> `06d03b87`

---

flake.lock

| Commit                                                                                           | Message                                                                   |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------- |
| [`cdcc5aba`](https://github.com/hyprwm/Hyprland/commit/cdcc5aba06f20005842cf966b23af50456dc7142) | `` xwayland: ignore OR activate requests if surface doesn't want focus `` |
| [`e3e7e1fd`](https://github.com/hyprwm/Hyprland/commit/e3e7e1fdda7660a70bd206aa3ed6a45bb4000376) | `` monitor: don't damage twice (#4727) ``                                 |

chore(flake/hyprland): `fbf5ba87` -> `cdcc5aba`

---

flake.lock

| Commit                                                                                         | Message                                                                                                           |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| [`89c71907`](https://github.com/NixOS/nixpkgs/commit/89c719072e83be70b0754e7bf231042fdc95b1aa) | `` kubernetes-helmPlugins.helm-diff: 3.9.2 -> 3.9.4 ``                                                            |
| [`55883724`](https://github.com/NixOS/nixpkgs/commit/5588372485191f4eeae13e91b658598aeaf82be7) | `` renode-unstable: 1.14.0+20240212git8eb88bb9c -> …

chore(flake/nixpkgs): `9a113b42` -> `607312f7`

---

flake.lock

| Commit                                                                                         | Message                                                                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`9ca1e833`](https://github.com/NixOS/nixpkgs/commit/9ca1e833f6e1e7346d941eaa60404f23fccb0a22) | `` python311Packages.google-cloud-access-context-manager: refactor ``                    |
| [`c5da04da`](https://github.com/NixOS/nixpkgs/commit/c5da04da50a60c21889f7d1fc348a43ce9bf1db1) | `` nbtscan: init at 1.7.2-unstable-2022-10-29 ``                                         |
| …

chore(flake/nixpkgs): `607312f7` -> `28d6a724`

---

flake.lock

| Commit                                                                                           | Message                                                                             |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------- |
| [`683a4b07`](https://github.com/hyprwm/Hyprland/commit/683a4b07c514fa3c13cdf09e475283a69fcc7653) | `` rules: ignore static tile/float rules in dynamic gets ``                         |
| [`5261a8df`](https://github.com/hyprwm/Hyprland/commit/5261a8df81c1aad07b582bce82d164801de533b0) | `` keybinds: Add an option to pass a window argument to moveoutofgroup (#4724) ``   |
| …

chore(flake/hyprland): `cdcc5aba` -> `683a4b07`

---

flake.lock

| [`ccc244cf`](https://github.com/nix-community/NUR/commit/ccc244cf9a517cdfccfd6a7a8b47083a5f926a0e) | `` automatic update `` |
| [`8199a4b8`](https://github.com/nix-community/NUR/commit/8199a4b8d5d6074db7b10a725d880630e5c37637) | `` automatic update `` |
| [`0453b074`](https://github.com/nix-community/NUR/commit/0453b0745100cee220ff5b1be71c8806aaa07547) | `` automatic update `` |
| [`d46453dc`](https://github.com/nix-community/NUR/commit/d46453dcb1bd9aec9ecfa8a0ad8027308c643606) | `` automatic update `` |
| …

chore(flake/nur): `bacaa8bc` -> `ccc244cf`

---

flake.lock

| [`192e23af`](https://github.com/nix-community/emacs-overlay/commit/192e23af90504ef6514d9255f8ee006d47909e09) | `` Updated emacs ``        |
| [`bbfdf3d5`](https://github.com/nix-community/emacs-overlay/commit/bbfdf3d5e9add63f15fa4444fb0fc61adbd11237) | `` Updated melpa ``        |
| [`9454543c`](https://github.com/nix-community/emacs-overlay/commit/9454543c4d5e1bda8ee810e1c498031f08b16908) | `` Updated elpa ``         |
| [`56546e3c`](https://github.com/nix-community/emacs-overlay/commit/56546e3cf5eabc382dd6a …

chore(flake/emacs-overlay): `c3d788a4` -> `192e23af`

---

flake.lock

| [`4bf696bd`](https://github.com/nix-community/NUR/commit/4bf696bd6382375d823656324ccd33c2037c20f9) | `` automatic update `` |
| [`cffaf8c8`](https://github.com/nix-community/NUR/commit/cffaf8c87a877a77f790cfef31e2ad916939a708) | `` automatic update `` |
| [`7e3beaca`](https://github.com/nix-community/NUR/commit/7e3beacae3fbe1bb6657057d1af31f209a2f1ce0) | `` automatic update `` |
| [`546e675e`](https://github.com/nix-community/NUR/commit/546e675eb1d9a332dc04e8fb3ecc0a35b8101572) | `` automatic update `` |
| …

chore(flake/nur): `ccc244cf` -> `4bf696bd`

---

flake.lock

| [`b1a7ee96`](https://github.com/Gerg-L/spicetify-nix/commit/b1a7ee96a64b1755a7ddd46b3e73c5442a76e45f) | `` CI update 2024-02-18 (#76) `` |

chore(flake/spicetify-nix): `06d03b87` -> `b1a7ee96`

---

flake.lock

| Commit                                                                                         | Message                                                                                            |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| [`ac637ef2`](https://github.com/NixOS/nixpkgs/commit/ac637ef21ecc2f0a1a0987fe9ce1d7f0d7f42fca) | `` Revert "openobserve: 0.7.2 -> 0.8.1" ``                                                         |
| [`51e918d4`](https://github.com/NixOS/nixpkgs/commit/51e918d474e2a69e5de0c2295556c32b84a57c8b) | `` uv: 0.1.3 -> 0.1.4 ``                                                                           | …

chore(flake/nixpkgs): `28d6a724` -> `35c5863c`

---

flake.lock

| [`6c7eca7e`](https://github.com/nix-community/emacs-overlay/commit/6c7eca7e41d5d47a0777b045a125a6f076b70c34) | `` Updated emacs ``        |
| [`e3b3b271`](https://github.com/nix-community/emacs-overlay/commit/e3b3b271caf7a4664b51e1a25c16e5a69fe70036) | `` Updated melpa ``        |
| [`af022425`](https://github.com/nix-community/emacs-overlay/commit/af02242510319d4dcb895f4de83b74b461b9cbda) | `` Updated elpa ``         |
| [`4337f34d`](https://github.com/nix-community/emacs-overlay/commit/4337f34dae4a0dc335398 …

chore(flake/emacs-overlay): `192e23af` -> `6c7eca7e`

---

flake.lock

| Commit                                                                                           | Message                                                                 |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`301b48b7`](https://github.com/hyprwm/Hyprland/commit/301b48b74087cc59753ffa144b215540e6f82831) | `` renderer: fix invalid damage accumulation with invalid buffer_age `` |
| [`fae47ef4`](https://github.com/hyprwm/Hyprland/commit/fae47ef462d1d7969afe001070839391ba6dbaa8) | `` config: fix errors in default config ``                              |
| [`5fc0b772`](https://github.com/hyprwm/Hyprland/commit/5fc0b772c72ce23f3d31fec31fa3688f7ed1afff) …

chore(flake/hyprland): `683a4b07` -> `301b48b7`

---

flake.lock

| [`17352eb2`](https://github.com/nix-community/nix-index-database/commit/17352eb241a8d158c4ac523b19d8d2a6c8efe127) | `` update packages.nix to release 2024-02-18-030707 `` |
| [`c52e2960`](https://github.com/nix-community/nix-index-database/commit/c52e2960c521613ba8ca180f476ea064e47db48e) | `` flake.lock: Update ``                               |

chore(flake/nix-index-database): `0cb43457` -> `17352eb2`

---

flake.lock

| Commit                                                                                                      | Message                                   |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`11edf9ca`](https://github.com/nix-community/home-manager/commit/11edf9cad78cce49d09436c8d725ae36b65671dc) | `` flake.lock: Update ``                  |
| [`309465d2`](https://github.com/nix-community/home-manager/commit/309465d20993095a1c6ee2d7eda6ef3588f165ff) | `` Translate using Weblate (Ukrainian) `` |
| [`7671ec19`](https://github.com/nix-community/home-manager/commit/7671ec1931daee86161c8da1115515447667545e) | `` Translate using Weblate (Swedish) ``   |
| …

chore(flake/home-manager): `3d6791b3` -> `11edf9ca`

---

flake.lock

| Commit                                                                                      | Message                          |
| ------------------------------------------------------------------------------------------- | -------------------------------- |
| [`aa4df097`](https://github.com/viperML/nh/commit/aa4df097654cdeb15aa74aabd72863a6fb30c7e6) | `` fix rev ``                    |
| [`7db2d78d`](https://github.com/viperML/nh/commit/7db2d78ddb8be087544c54a384891b459e3ae88f) | `` Sync package with nixpkgs' `` |

chore(flake/nh): `36eba281` -> `aa4df097`

---

flake.lock

| [`e70958c9`](https://github.com/Gerg-L/spicetify-nix/commit/e70958c9943b7ed2f20b60c8f09a886eaeea3c2d) | `` CI update 2024-02-20 (#78) `` |
| [`976fbe62`](https://github.com/Gerg-L/spicetify-nix/commit/976fbe62df40bd2e3d956f2cd428fdcc92e37fc8) | `` CI update 2024-02-19 (#77) `` |

chore(flake/spicetify-nix): `b1a7ee96` -> `e70958c9`

---

flake.lock

| [`eca18f04`](https://github.com/nix-community/emacs-overlay/commit/eca18f048a96d077a72881ced8949e1e8dcee4b5) | `` Updated emacs ``        |
| [`7b175193`](https://github.com/nix-community/emacs-overlay/commit/7b1751931dee4af2f8ca14c3958b45c2704ba4ee) | `` Updated melpa ``        |
| [`6879e098`](https://github.com/nix-community/emacs-overlay/commit/6879e098c576b2e386fe84a464a5a4bad5bff41e) | `` Updated elpa ``         |
| [`db8898a6`](https://github.com/nix-community/emacs-overlay/commit/db8898a6db80f8dc07056 …

chore(flake/emacs-overlay): `5d4f6efc` -> `eca18f04`

---

flake.lock

| [`b878d82e`](https://github.com/nix-community/NUR/commit/b878d82e0bee71857863aab9e94a95d6ba3cfa00) | `` automatic update `` |
| [`8376fb9d`](https://github.com/nix-community/NUR/commit/8376fb9d580aceae3f717a31b9d897aeb427de49) | `` automatic update `` |
| [`30083548`](https://github.com/nix-community/NUR/commit/30083548b4ac11731dee0d101c4717bd6005fa9e) | `` automatic update `` |
| [`1b9b8c8d`](https://github.com/nix-community/NUR/commit/1b9b8c8d29f7327e3adf76f9a0d413b2fced9e81) | `` automatic update `` |
| …

chore(flake/nur): `e0f255fb` -> `b878d82e`

---

flake.lock

| Commit                                                                                           | Message                                                               |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------- |
| [`13d98548`](https://github.com/hyprwm/Hyprland/commit/13d985489788fa5349b3457d6eb1c19bad8f37e9) | `` xdgpopup: fix UAF because of an invalid listener connection ``     |
| [`cd73dda1`](https://github.com/hyprwm/Hyprland/commit/cd73dda16e0e2e3008c87115b34b7c6e054ff5a8) | `` sessionLock: send preferred fractional scale ``                    |
| [`02c9a2d7`](https://github.com/hyprwm/Hyprland/commit/02c9a2d769dc3ae5efb942ad16578eee45a6f6dd) | `` …

chore(flake/hyprland): `69a4f08d` -> `13d98548`

---

flake.lock

| Commit                                                                                               | Message                  |
| ---------------------------------------------------------------------------------------------------- | ------------------------ |
| [`e5046212`](https://github.com/numtide/treefmt-nix/commit/e504621290a1fd896631ddbc5e9c16f4366c9f65) | `` add jsonfmt (#158) `` |

chore(flake/treefmt-nix): `ac599dab` -> `e5046212`

---

flake.lock

| Commit                                                                                         | Message                                                                     |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`a725d72c`](https://github.com/NixOS/nixpkgs/commit/a725d72ca650d398dffab3d78186dc1aa65e853d) | `` pkgs.gptscript: init at 0.1.1 ``                                         |
| [`256f2c6f`](https://github.com/NixOS/nixpkgs/commit/256f2c6fceef0cf24ca2d97afad4abbe202d35ec) | `` Revert "python311Packages.ical: 6.1.1 -> 7.0.0" ``                       |
| [`2af49615`](https://github.com/NixOS/nixpkgs/commit/2af496159e45a0f171e3bfc57fe8f5e1ed5d0 …

chore(flake/nixpkgs): `35c5863c` -> `fa15b53d`

---

flake.lock

| [`192aa9b1`](https://github.com/nix-community/NUR/commit/192aa9b134f867b6811ecd0444e994ef941648db) | `` automatic update `` |
| [`88034533`](https://github.com/nix-community/NUR/commit/8803453381137566c1bc1d91f4c3f8775680a601) | `` automatic update `` |
| [`deb67c14`](https://github.com/nix-community/NUR/commit/deb67c142317827d32256bb0df1fc96be237a177) | `` automatic update `` |
| [`63862fa4`](https://github.com/nix-community/NUR/commit/63862fa406a392b70265a065269d0f5bb9126050) | `` automatic update `` |
| …

chore(flake/nur): `b878d82e` -> `192aa9b1`

---

flake.lock

| Commit                                                                                                      | Message                                                 |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`4ee704cb`](https://github.com/nix-community/home-manager/commit/4ee704cb13a5a7645436f400b9acc89a67b9c08a) | `` xscreensaver: add package option ``                  |
| [`ae7a3b51`](https://github.com/nix-community/home-manager/commit/ae7a3b5137ca3522f2802b3183de8fe5287b13d2) | `` hyprland: fix reloading ``                           |
| [`4e6d25a5`](https://github.com/nix-community/home-manager/commit/4e6d25a51bb3035af7db54cc8f7fcac23e9467dc) | `` …

chore(flake/home-manager): `517601b3` -> `4ee704cb`

---

flake.lock

| Commit                                                                                                       | Message                                                                     |
| ------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`299398be`](https://github.com/nix-community/emacs-overlay/commit/299398be3c27d885cf17ff8310944b307a1449e9) | `` Updated emacs ``                                                         |
| [`92a5d3e7`](https://github.com/nix-community/emacs-overlay/commit/92a5d3e756ba99247a2dbe9d1d43e924318a4770) | `` Updated melpa ``                                                         |
| …

chore(flake/emacs-overlay): `eca18f04` -> `299398be`

---

flake.lock

| [`dc12e982`](https://github.com/Gerg-L/spicetify-nix/commit/dc12e982d81512e658d9ca4e30cdf5b846a8c160) | `` CI update 2024-02-24 (#81) `` |
| [`e63a1a2a`](https://github.com/Gerg-L/spicetify-nix/commit/e63a1a2a1d215e6a39f41c59d65a81d02806309a) | `` CI update 2024-02-22 (#80) `` |
| [`c19e1d31`](https://github.com/Gerg-L/spicetify-nix/commit/c19e1d31b497929c16fdc16b211db01d6cc61289) | `` CI update 2024-02-21 (#79) `` |

chore(flake/spicetify-nix): `e70958c9` -> `dc12e982`

---

flake.lock

| Commit                                                                                               | Message                    |
| ---------------------------------------------------------------------------------------------------- | -------------------------- |
| [`36fd6923`](https://github.com/numtide/treefmt-nix/commit/36fd6923c122a983bc3915692e6cb3ff341ef083) | `` add fantomas (#159) ``  |
| [`8bffa0f5`](https://github.com/numtide/treefmt-nix/commit/8bffa0f55a0429837ebaaf9fe55114df21e15129) | `` flake update ``         |
| [`6e11dcbe`](https://github.com/numtide/treefmt-nix/commit/6e11dcbed37d527eb614bc26e5aa4f4ab93fffc2) | `` add nixfmt-rfc-style `` |

chore(flake/treefmt-nix): `e5046212` -> `36fd6923`

---

flake.lock

| Commit                                                                                           | Message                                                                                           |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------- |
| [`f534ac3f`](https://github.com/hyprwm/Hyprland/commit/f534ac3fc462d8af923d2a1ab8ef58f62639a1ea) | `` hyprctl: add missing newline in error case of missing `HYPRLAND_INSTANCE_SIGNATURE` (#4832) `` |
| [`9103af31`](https://github.com/hyprwm/Hyprland/commit/9103af317ec7c6d46d4be561eee855d5337c9e8c) | `` hyprctl: ignore non-lock files for instances `` …

chore(flake/hyprland): `d9757b61` -> `f534ac3f`

---

flake.lock

| [`c37cffdd`](https://github.com/NixOS/nixpkgs/commit/c37cffdda5ccc4999593c78c67db37b8f8d0ecde) | `` urlwatch: cherry-pick lxml 5 compatibility fix ``                       |
| [`4dbe5e70`](https://github.com/NixOS/nixpkgs/commit/4dbe5e70abe5f35508ef34060eac49cf73d1083a) | `` python312Packages.oelint-parser: 3.2.1 -> 3.2.2 ``                      |
| [`51945608`](https://github.com/NixOS/nixpkgs/commit/519456082e43c2f9445537e24697fb4e5e9039a3) …

chore(flake/nixpkgs): `fa15b53d` -> `6d8aba54`

---

flake.lock

| [`88cb60b6`](https://github.com/nix-community/emacs-overlay/commit/88cb60b6c44861e422302371c0761a89377cf2c7) | `` Updated emacs ``        |
| [`b0ff39b2`](https://github.com/nix-community/emacs-overlay/commit/b0ff39b2ecfd233a8117dd95dd1b1bfd926714ae) | `` Updated melpa ``        |
| [`f0b399a4`](https://github.com/nix-community/emacs-overlay/commit/f0b399a48ad970fbaabb0a171b103b066285054c) | `` Updated flake inputs `` |
| [`a9db0bff`](https://github.com/nix-community/emacs-overlay/commit/a9db0bffddf142648d9fc …

chore(flake/emacs-overlay): `299398be` -> `88cb60b6`

---

flake.lock

| Commit                                                                                           | Message                                                                                        |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------- |
| [`b39dcfa4`](https://github.com/hyprwm/Hyprland/commit/b39dcfa497f84486569bf862092dfcfadbfd8747) | `` refactor: move a few things to desktop/ ``                                                  |
| [`4bff762d`](https://github.com/hyprwm/Hyprland/commit/4bff762d9733ba7334cd37b995cf51552cc80be0) | `` xwaylandmgr: don't read xwayland surface from unmapped xwayland ``                          |
| …

chore(flake/hyprland): `f534ac3f` -> `b39dcfa4`

---

flake.lock

| Commit                                                                                             | Message                            |
| -------------------------------------------------------------------------------------------------- | ---------------------------------- |
| [`74be1009`](https://github.com/nix-community/NUR/commit/74be1009198dc18d3c974d85f7660e6e6c1c8184) | `` automatic update ``             |
| [`0168a848`](https://github.com/nix-community/NUR/commit/0168a84850c8770adb26fd4bf8a3b4bf9103932a) | `` automatic update ``             |
| [`fbe8df1c`](https://github.com/nix-community/NUR/commit/fbe8df1c13fd8e63e35c2c4654104661eb1fbbed) | `` automatic update ``             |
| [`2b3b8752`](https://github.com/nix-community/NUR/commit/2b3b8752d1bd83b66b38163685f686ba8f3d1924) …

chore(flake/nur): `192aa9b1` -> `74be1009`

---

flake.lock

| Commit                                                                                                       | Message             |
| ------------------------------------------------------------------------------------------------------------ | ------------------- |
| [`5e278b16`](https://github.com/nix-community/emacs-overlay/commit/5e278b16d982831f1b81669d26649454c1a37981) | `` Updated emacs `` |
| [`187e5acf`](https://github.com/nix-community/emacs-overlay/commit/187e5acf9468f9403e7ce4d7876d682d4c347596) | `` Updated melpa `` |
| [`24c73905`](https://github.com/nix-community/emacs-overlay/commit/24c73905454662533a7a4295787d6e241632bb01) | `` Updated elpa ``  |

chore(flake/emacs-overlay): `88cb60b6` -> `5e278b16`

---

flake.lock

| Commit                                                                                              | Message                  |
| --------------------------------------------------------------------------------------------------- | ------------------------ |
| [`b7643f71`](https://github.com/sodiboo/niri-flake/commit/b7643f71110dbc8619b2be27298130622c58dc30) | `` flake.lock: Update `` |

chore(flake/niri): `0dd6715b` -> `b7643f71`

---

flake.lock

| Commit                                                                                         | Message                                                                                      |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| [`57789e56`](https://github.com/NixOS/nixpkgs/commit/57789e56918f454069e7ed991276a184041cbd13) | `` prometheus-alertmanager: 0.26.0 -> 0.27.0 (#292230) ``                                    |
| [`c29ae2c8`](https://github.com/NixOS/nixpkgs/commit/c29ae2c846e0d6dcfb2b8fc3699b2fa36e184f38) | `` ocamlPackages.caqti: 1.9.1 → 2.1.1 ``                                                     |
| …

chore(flake/nixpkgs): `6d8aba54` -> `57789e56`

---

flake.lock

| Commit                                                                                                    | Message                                                               |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`d470342a`](https://github.com/nix-community/lanzaboote/commit/d470342af6fb149ee5a7685f2ec3a984ddc68112) | `` tests: remove custom OVMF overrides ``                             |
| [`7df500bd`](https://github.com/nix-community/lanzaboote/commit/7df500bd1cc911932f9c3a7cd2eb6c071764f0c4) | `` readme: add mention of "Window UEFI Mode" needed on some boards `` |
| [`e2e8059d`](https://github.com/nix-community/lanzaboote/commit/e2e805 …

chore(flake/lanzaboote): `e761c7ee` -> `eeb45682`

---

flake.lock

| Commit                                                                                               | Message                              |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`093f82e5`](https://github.com/numtide/treefmt-nix/commit/093f82e5707bb6f14ee38a742748f9fb4ab1488e) | `` feat(programs): add opa (#162) `` |

chore(flake/treefmt-nix): `e497a9dd` -> `093f82e5`

---

flake.lock

| Commit                                                                                           | Message                                                                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------- |
| [`acf0b536`](https://github.com/hyprwm/Hyprland/commit/acf0b536a643bd5c87cd6097f5c94b4041797c15) | `` xwayland: disable initial focus for xwayland dialogs (#4936) ``               |
| [`1762e9c6`](https://github.com/hyprwm/Hyprland/commit/1762e9c6ec0140a35e79b0f4c88cce003b05ced5) | `` renderer: respect forceNoBlur when rendering small surface windows (#4932) `` |
| [`964f1a43`](https://github.com/hyprwm/Hyprland/commit/964f1a4 …

chore(flake/hyprland): `7ce781e8` -> `acf0b536`

---

flake.lock

| Commit                                                                                               | Message                                                            |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`9c57261c`](https://github.com/numtide/treefmt-nix/commit/9c57261c71871d2208a6dd4394774cca226c6dbc) | `` fix(programs): leptosfmt does not touch files anymore (#166) `` |
| [`783cb44b`](https://github.com/numtide/treefmt-nix/commit/783cb44b0a0a1b02eba7fee58f3b606fbbf1519a) | `` feat(programs): add dos2unix (#165) ``                          |

chore(flake/treefmt-nix): `e7a277c5` -> `9c57261c`

---

flake.lock

| [`f97c89ae`](https://github.com/Gerg-L/spicetify-nix/commit/f97c89aebd7076cce03c56466269cabb3d7c75f5) | `` CI update 2024-03-09 (#95) `` |
| [`8a3bcc8f`](https://github.com/Gerg-L/spicetify-nix/commit/8a3bcc8f4be5366aed588c8181874f40e7822291) | `` CI update 2024-03-08 (#94) `` |
| [`542ef89b`](https://github.com/Gerg-L/spicetify-nix/commit/542ef89b09568ed8c324281e9afeafa05619a5e9) | `` CI update 2024-03-07 (#93) `` |

chore(flake/spicetify-nix): `15aa1288` -> `f97c89ae`

---

flake.lock

| Commit                                                                                                            | Message                                  |
| ----------------------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`56335944`](https://github.com/nix-community/nix-index-database/commit/56335944627b7360c31da13c73aa521d996637d8) | `` Document nix-locate usage. Fix #79 `` |
| [`c46d85da`](https://github.com/nix-community/nix-index-database/commit/c46d85da736e6b2563cf1f284f7e054bd87b9b38) | `` readme: Mic92 -> nix-community ``     |

chore(flake/nix-index-database): `93554c04` -> `2ad5ebce`

---

flake.lock

| [`91cc2004`](https://github.com/nix-community/NUR/commit/91cc200411377bd61e63526d925a82be50dc9d7f) | `` automatic update `` |
| [`0fcbd140`](https://github.com/nix-community/NUR/commit/0fcbd140884d31178bfeae69998e7472b53de304) | `` automatic update `` |
| [`cf1e9b0e`](https://github.com/nix-community/NUR/commit/cf1e9b0e085368cc489c765f285f1d07c2ec8d36) | `` automatic update `` |
| [`414e2ef3`](https://github.com/nix-community/NUR/commit/414e2ef360397c9e024d09dda6de78455d2e00b2) | `` automatic update `` |
| …

chore(flake/nur): `c10daa69` -> `91cc2004`

---

flake.lock

| Commit                                                                                                      | Message                                                   |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`b0b0c3d9`](https://github.com/nix-community/home-manager/commit/b0b0c3d94345050a7f86d1ebc6c56eea4389d030) | `` targets/generic-linux: use xdg path for defexpr ``     |
| [`16311f1d`](https://github.com/nix-community/home-manager/commit/16311f1d3c518656f680b7d09e29e37826f9802e) | `` borgmatic: add option for pattern matching ``          |
| [`17431970`](https://github.com/nix-community/home-manager/commit/17431970b4ebc75a92657101ccffcfc9e1f9d8f0) | …

chore(flake/home-manager): `23ff9821` -> `b0b0c3d9`

---

flake.lock

| [`9b54befb`](https://github.com/chaotic-cx/nyx/commit/9b54befbe7993ed2abe91f4d76e259b3e8f9d922) | `` Bump 20240307-1 (#619) ``    |
| [`ecc8d401`](https://github.com/chaotic-cx/nyx/commit/ecc8d401f3534069a9f0a5d113df9ca32b468a4a) | `` failures: update ``          |
| [`9beea6da`](https://github.com/chaotic-cx/nyx/commit/9beea6da7ef55f30d6fd4979594b3a1223cebe6e) | `` nixpkgs: bump to 20240307 `` |
| [`85e60c9c`](https://github.com/chaotic-cx/nyx/commit/85e60c9ce043b7e190574c0c4b397f53082611db) | `` Bump 20240306-1 (#618) `` …

chore(flake/chaotic): `70b0b272` -> `9b54befb`

---

flake.lock

| Commit                                                                                      | Message                                      |
| ------------------------------------------------------------------------------------------- | -------------------------------------------- |
| [`9f4529ad`](https://github.com/viperML/nh/commit/9f4529adfb95781f82307cf5e87419d736485c1b) | `` modify update arg based on Nix version `` |
| [`1073bcd7`](https://github.com/viperML/nh/commit/1073bcd7e134f07eddf1d2e4619ec4a012a8e712) | `` fix --update on newer nix versions ``     |
| [`b9368e38`](https://github.com/viperML/nh/commit/b9368e38dccc665e0335a2a4c6ab2ba9be6c2302) | `` fix typo ``                               |
| [`f7458d3f`](https://github.com/viperML/nh/commit/f7458d3f9f0249dd73faaef24421184fb …

chore(flake/nh): `3f148b0c` -> `393cffa0`

---

flake.lock

| [`a01be1e4`](https://github.com/Gerg-L/spicetify-nix/commit/a01be1e4a3cd210cfb9e486b61b4c53ac04e8283) | `` CI update 2024-03-16 (#103) `` |

chore(flake/spicetify-nix): `e306cc70` -> `a01be1e4`

---

flake.lock

| Commit                                                                                                      | Message                                   |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`206f457f`](https://github.com/nix-community/home-manager/commit/206f457fffdb9a73596a4cb2211a471bd305243d) | `` prezto: be caseSensitive by default `` |

chore(flake/home-manager): `c781b28a` -> `206f457f`

---

flake.lock

| Commit                                                                                           | Message                                                                                   |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------- |
| [`0387528c`](https://github.com/hyprwm/Hyprland/commit/0387528c56c4d9faf93946cbc9426973de6ef61b) | `` master: fix moving fullscreen workspace and remove duplicate code (#5131) ``           |
| [`0e87a08e`](https://github.com/hyprwm/Hyprland/commit/0e87a08e15c023325b64920d9e1159f38a090695) | `` renderer: disable surface adjustments for misaligned reported when manual resizing ``  |
| …

chore(flake/hyprland): `c4f52d19` -> `0387528c`

---

flake.lock

| Commit                                                                                      | Message                                                                               |
| ------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`60c019a9`](https://github.com/viperML/nh/commit/60c019a930e1718f1c5b6638f16dc221bf667d61) | `` Add comment to raise interest into https://github.com/NixOS/nixpkgs/pull/294923 `` |

chore(flake/nh): `393cffa0` -> `60c019a9`

---

flake.lock

| Commit                                                                                             | Message                       |
| -------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`585df78a`](https://github.com/nix-community/NUR/commit/585df78aeb0bf632a4370891de15a4b99070f1a3) | `` automatic update ``        |
| [`cbb38b5c`](https://github.com/nix-community/NUR/commit/cbb38b5c51960bbc785a85a9ed827104c80b64e0) | `` automatic update ``        |
| [`e826440f`](https://github.com/nix-community/NUR/commit/e826440f924a69c254ae92a14d0c3c2076f30707) | `` automatic update ``        |
| [`476c8bb0`](https://github.com/nix-community/NUR/commit/476c8bb001802513f934a105544a936e03734941) | `` fix order `` …

chore(flake/nur): `223ac289` -> `585df78a`

---

flake.lock

| Commit                                                                                          | Message                                                       |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`1520b69f`](https://github.com/chaotic-cx/nyx/commit/1520b69fa40d96c5e95b6e0da65831d3c7130fb0) | `` failures: update ``                                        |
| [`2a4d2101`](https://github.com/chaotic-cx/nyx/commit/2a4d2101e26a2d2c0713cb8767c17c586bb68913) | `` nix-flake-schemas_git: fix source repository URL (#647) `` |
| [`a68e1385`](https://github.com/chaotic-cx/nyx/commit/a68e13853eb32439cbc84a251e11262d3121012f) | `` nixpkgs: bump to 20240323 `` …

chore(flake/chaotic): `2952a351` -> `1520b69f`

---

flake.lock

| Commit                                                                                                     | Message            |
| ---------------------------------------------------------------------------------------------------------- | ------------------ |
| [`0f783e55`](https://github.com/LudovicoPiero/nixpackages/commit/0f783e55828bc067f8f9d4c4634dff1b7d835cf9) | `` ci: whoopsie `` |

chore(flake/ludovico-nixpkgs): `9e46b0ae` -> `0f783e55`

---

flake.lock

| Commit                                                                                          | Message                                              |
| ----------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`bec5e460`](https://github.com/chaotic-cx/nyx/commit/bec5e460d3fcfccac029088c395f4f629c800957) | `` failures: update; alacritty_git: fix cargoHash `` |
| [`81b72ea5`](https://github.com/chaotic-cx/nyx/commit/81b72ea525ae5d4d6633707d63afb302c9b683f3) | `` nixpkgs: bump to 20240328 ``                      |

chore(flake/chaotic): `c98e4768` -> `bec5e460`

---

flake.lock

| Commit                                                                                         | Message                                                                            |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`bc5ee2b8`](https://github.com/NixOS/nixpkgs/commit/bc5ee2b8f8c1b6a0f1e80a103ccd77febe85f8cc) | `` treewide: Switch markdown placeholder from "..." to <...> ``                    |
| [`fcc95ff8`](https://github.com/NixOS/nixpkgs/commit/fcc95ff8172cc68a0d2d52aa1e8ef2120d2904ec) | `` treewide: Fix all Nix ASTs in all markdown files ``                             |
| [`bc77c7a9`](https://github.com/NixOS/nixpkgs/commit/bc77c7a97 …

chore(flake/nixpkgs-unstable): `38760f86` -> `c99b6678`

---

flake.lock

| [`619dd15c`](https://github.com/nix-community/emacs-overlay/commit/619dd15c78edea5b3236c841f25a03d77f260154) | `` Updated emacs ``        |
| [`89b9788c`](https://github.com/nix-community/emacs-overlay/commit/89b9788ca819ee2f25606c2df4825612bdc8d9ac) | `` Updated melpa ``        |
| [`57bef37f`](https://github.com/nix-community/emacs-overlay/commit/57bef37f7da3ab0f1c5924aa7e19fdf09d6d9618) | `` Updated flake inputs `` |

chore(flake/emacs-overlay): `593fd771` -> `619dd15c`

---

flake.lock

| Commit                                                                                           | Message                                                                               |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------- |
| [`1cc9a443`](https://github.com/hyprwm/Hyprland/commit/1cc9a44318e53a34f41cc36483502de985b88cf8) | `` input: Fix incorrect keyboard focus taken when no window was present (#5337) ``    |
| [`5e8c25d4`](https://github.com/hyprwm/Hyprland/commit/5e8c25d498ed5cb7852ae74a876b0c138a62d59d) | `` core: match all workspace rules instead of the first one only (#5340) ``           |
| …

chore(flake/hyprland): `187caf41` -> `1cc9a443`

---

flake.lock

| Commit                                                                                      | Message                                            |
| ------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`37cbf2f9`](https://github.com/divnix/std/commit/37cbf2f9cadfdbf0a96d22881d8aa383d5bfdd67) | `` chore: fix typo on contribution instructions `` |

chore(flake/std): `da4a16c8` -> `37cbf2f9`

---

flake.lock

| [`3af43c7b`](https://github.com/Gerg-L/spicetify-nix/commit/3af43c7b8a12c4cdd9616880fae088599cb03df3) | `` CI update 2024-03-30 (#117) `` |
| [`90bc3a84`](https://github.com/Gerg-L/spicetify-nix/commit/90bc3a849967067ae15e93856ef44540b2ff483f) | `` CI update 2024-03-29 (#116) `` |

chore(flake/spicetify-nix): `f1153c20` -> `3af43c7b`

---

flake.lock

| Commit                                                                                                       | Message                     |
| ------------------------------------------------------------------------------------------------------------ | --------------------------- |
| [`b58ea7d9`](https://github.com/nix-community/emacs-overlay/commit/b58ea7d9c253d9eea3bbf4d5153a9f1f7bc21722) | `` Updated elpa ``          |
| [`33f182c7`](https://github.com/nix-community/emacs-overlay/commit/33f182c768a59d1a403bd00f1f1614a0bc3595ef) | `` Updated nongnu ``        |
| [`ccd0043a`](https://github.com/nix-community/emacs-overlay/commit/ccd0043a3fb5758b0d17a92e907872cdc4f63ab7) | `` Updated elpa ``          |
| [`f8ad90d4`](https://github.com/nix-community/emacs-overlay/commit/f8ad90d467e2a48c …

chore(flake/emacs-overlay): `619dd15c` -> `b58ea7d9`

---

flake.lock

| Commit                                                                                         | Message                                                                                        |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| [`59bccda1`](https://github.com/NixOS/nixpkgs/commit/59bccda1532d677d5f69f07d677489f3a995b744) | `` Revert "stdenv: add meta.repository field" ``                                               |
| [`0e8bcaa6`](https://github.com/NixOS/nixpkgs/commit/0e8bcaa661f602db11bbe8347fb46bb271e8e58b) | `` Revert "stdenv/check-meta: Don't create new environments when computing meta.repository" `` |
| …

chore(flake/nixpkgs-unstable): `c99b6678` -> `35fde999`

---

flake.lock

| [`f6e7011c`](https://github.com/Gerg-L/spicetify-nix/commit/f6e7011c90d78637aaa89e97d4c2e9fd3fdea383) | `` CI update 2024-04-04 (#121) `` |
| [`cf1e607f`](https://github.com/Gerg-L/spicetify-nix/commit/cf1e607f72578698167fe3f83414ef0a7d2d0fe6) | `` CI update 2024-04-03 (#120) `` |

chore(flake/spicetify-nix): `b7ae0dd1` -> `f6e7011c`

---

flake.lock

| [`d8c28bca`](https://github.com/nix-community/emacs-overlay/commit/d8c28bca43275f1503a029cc73629cd1aa585af7) | `` Updated emacs ``        |
| [`3a2a6fd5`](https://github.com/nix-community/emacs-overlay/commit/3a2a6fd5bbfe5066377afcae6e001698e5dcdf81) | `` Updated melpa ``        |
| [`46294460`](https://github.com/nix-community/emacs-overlay/commit/462944602d2eaa43bf51b958e7f453887e9ba3c1) | `` Updated elpa ``         |
| [`7480617f`](https://github.com/nix-community/emacs-overlay/commit/7480617fd05f6ed921ee8 …

chore(flake/emacs-overlay): `5dee04f5` -> `d8c28bca`

---

flake.lock

| Commit                                                                                           | Message                                                                |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------- |
| [`b7d71bc0`](https://github.com/hyprwm/Hyprland/commit/b7d71bc0e1084bc1a296ae906503709a74fde4d9) | `` keybinds: fix spammy warning ``                                     |
| [`9cf56306`](https://github.com/hyprwm/Hyprland/commit/9cf563065ad5069baea1472b665b56bdcbde3776) | `` layouts: add missing include ``                                     |
| [`36a8ae9b`](https://github.com/hyprwm/Hyprland/commit/36a8ae9bda4c2e150707e7ee0cb13ef3e8841728) | `` …

chore(flake/hyprland): `fc0a7af7` -> `b7d71bc0`

---

flake.lock

| Commit                                                                                         | Message                                                                       |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`36cac1a5`](https://github.com/NixOS/nixpkgs/commit/36cac1a5f09457ce7c52c24bfe1dd96f962950ad) | `` raycast: add passthru.updateScript ``                                      |
| [`cb860be4`](https://github.com/NixOS/nixpkgs/commit/cb860be46180e66b7d921e361f5406080a3fcbe9) | `` python312Packages.pyeapi: use nixfmt ``                                    |
| [`2f12e41d`](https://github.com/NixOS/nixpkgs/commit/2f12e41de3d4823823adb3231de94 …

chore(flake/nixpkgs-unstable): `5476cea4` -> `d9b45d7e`

---

flake.lock

| [`3f2a8fea`](https://github.com/NixOS/nixpkgs/commit/3f2a8fea9275c059c3bbd1de1cc417732a8ea316) | `` python311Packages.types-requests: 2.31.0.20240403 -> 2.31.0.20240406 `` |
| [`aad2a8af`](https://github.com/NixOS/nixpkgs/commit/aad2a8af943b0f1d31cc53ada83437fc1386ae5d) | `` gprbuild: add comment on headerpad_max_install_names ``                 |
| [`e599123b`](https://github.com/NixOS/nixpkgs/commit/e599123b09749b9be4271fd7709abfbe7f62b392) …

chore(flake/nixpkgs-unstable): `ca565875` -> `d9d5b4dc`

---

flake.lock

| Commit                                                                                           | Message                                                                                                   |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| [`9f1604e4`](https://github.com/hyprwm/Hyprland/commit/9f1604e4b0afec40cfa9bc095d6613a7f749b2c1) | `` input: Dont set active monitor when simulating mouse movement (#5465) ``                               |
| [`e80bccad`](https://github.com/hyprwm/Hyprland/commit/e80bccad513d0761cbb83038478fce72ddc51c01) | `` master: fix workspace orientation not being restored after workspace …

chore(flake/hyprland): `24734fbf` -> `9f1604e4`

---

flake.lock

| [`5d141af6`](https://github.com/nix-community/emacs-overlay/commit/5d141af64a57b0cfdf12a4c4156ecd44ae802057) | `` Updated elpa ``         |
| [`57048e83`](https://github.com/nix-community/emacs-overlay/commit/57048e832be022087f098c998f9b4d3481a1ccf5) | `` Updated emacs ``        |
| [`d6438783`](https://github.com/nix-community/emacs-overlay/commit/d6438783e19983886e460462b2f114a34b7a6d74) | `` Updated melpa ``        |
| [`015a0575`](https://github.com/nix-community/emacs-overlay/commit/015a05757ddf4c5d0f10c …

chore(flake/emacs-overlay): `1c772b55` -> `5d141af6`

---

flake.lock

| Commit                                                                                           | Message                                                                  |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------ |
| [`b1a94302`](https://github.com/hyprwm/Hyprland/commit/b1a94302897ae559c877471f7d365651bcd24ad4) | `` inhibitor: always destroy on window unmap ``                          |
| [`e0a7cf5c`](https://github.com/hyprwm/Hyprland/commit/e0a7cf5c3006e9b7acd26551f14ef7b06d5a11ab) | `` master: fix full height when all windows master (#5549) ``            |
| [`185a3b48`](https://github.com/hyprwm/Hyprland/commit/185a3b48814cc4a1afbf32a69792a6161c4038c …

chore(flake/hyprland): `303b9956` -> `b1a94302`

---

flake.lock

| [`15ad397c`](https://github.com/Gerg-L/spicetify-nix/commit/15ad397c3e1397e4e8f5151f74a606976bbc570c) | `` CI update 2024-04-11 (#128) `` |

chore(flake/spicetify-nix): `d87a2d41` -> `15ad397c`

---

flake.lock

| Commit                                                                                                     | Message      |
| ---------------------------------------------------------------------------------------------------------- | ------------ |
| [`6ce00080`](https://github.com/LudovicoPiero/nixpackages/commit/6ce0008094502733f3590ef5c2abc33fc0c0516d) | `` Update `` |

chore(flake/ludovico-nixpkgs): `4615a972` -> `6ce00080`

---

flake.lock

| [`705fbd14`](https://github.com/nix-community/emacs-overlay/commit/705fbd143cc7ee5899525003feda2267e23b4bd6) | `` Updated emacs ``        |
| [`0d45d704`](https://github.com/nix-community/emacs-overlay/commit/0d45d7041fa75d5312d3cf4abd4be2cd66533796) | `` Updated melpa ``        |
| [`1e87f115`](https://github.com/nix-community/emacs-overlay/commit/1e87f11534fab2ae74551cb394e0916d5ab47fa6) | `` Updated elpa ``         |
| [`50620dc0`](https://github.com/nix-community/emacs-overlay/commit/50620dc0fe98d1b97032e …

chore(flake/emacs-overlay): `1bff8265` -> `705fbd14`

---

flake.lock

| Commit                                                                                         | Message                                                                                               |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------- |
| [`084ce1ee`](https://github.com/NixOS/nixpkgs/commit/084ce1ee888100b00f6a884dc88c8e960154673e) | `` Revert "nixos/getty: add option to autologin once per boot" ``                                     |
| [`3b26d563`](https://github.com/NixOS/nixpkgs/commit/3b26d563c53acd716d5c15a0c7b0ff126a2a1625) | `` Build Nixpkgs manual when nixdoc changes `` …

chore(flake/nixpkgs-unstable): `ca74eb22` -> `681d4a87`

---

flake.lock

| Commit                                                                                         | Message                             |
| ---------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`5fe89bc9`](https://github.com/NixOS/nixpkgs/commit/5fe89bc95dc792594446c435036815c3ffecb466) | `` afio: darwin build ``            |
| [`078dca4b`](https://github.com/NixOS/nixpkgs/commit/078dca4b1e60f1fcd6f6f0c5017e76d532032c62) | `` aewan: fix darwin build ``       |
| [`403c17e4`](https://github.com/NixOS/nixpkgs/commit/403c17e488fd6570964d627fa055ba4186a89f80) | `` flint: remove mpir dependency `` |
| [`c495c40f`](https://github.com/NixOS/nixpkgs/commit/c495c40f15a1466562161783b2f2cd0ac119fdf7) | `` …

chore(flake/nixpkgs-master): `d9110b97` -> `1973d842`

---

flake.lock

| [`a2c63373`](https://github.com/Gerg-L/spicetify-nix/commit/a2c6337326c7e22b337b1907a869bc5490e911da) | `` CI update 2024-04-12 (#129) `` |

chore(flake/spicetify-nix): `15ad397c` -> `a2c63373`

---

flake.lock

| Commit                                                                                                       | Message              |
| ------------------------------------------------------------------------------------------------------------ | -------------------- |
| [`d97f4109`](https://github.com/nix-community/emacs-overlay/commit/d97f41093894dd5e2d2548fe1e67e0b556a4f250) | `` Updated emacs ``  |
| [`39dc9983`](https://github.com/nix-community/emacs-overlay/commit/39dc9983ae9a65f12b4cbb7a80f4586aa6c78b51) | `` Updated melpa ``  |
| [`86055b72`](https://github.com/nix-community/emacs-overlay/commit/86055b7247d4b9192ae3bb4c087de5786c9789ba) | `` Updated elpa ``   |
| [`c0172f74`](https://github.com/nix-community/emacs-overlay/commit/c0172f7428f7b594721351c394471b4c45dbee8e) | `` …

chore(flake/emacs-overlay): `705fbd14` -> `d97f4109`

---

flake.lock

| Commit                                                                                           | Message                                           |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`0c513ba9`](https://github.com/hyprwm/Hyprland/commit/0c513ba91bd73106be99e35b1a020d24e5ae874a) | `` CI: fix packaging ``                           |
| [`dd6fdf49`](https://github.com/hyprwm/Hyprland/commit/dd6fdf49d9deebfe792ab5cd0332432249922fa9) | `` window: always unref workspace on unmap ``     |
| [`ddcdb56f`](https://github.com/hyprwm/Hyprland/commit/ddcdb56f2c7dab026a047379aaff4e30acff7414) | `` CI: fix arch ``                                |
| …

chore(flake/hyprland): `b1a94302` -> `0c513ba9`

---

flake.lock

| [`9f440671`](https://github.com/nix-community/emacs-overlay/commit/9f4406718ada7af83892e17355ef7fd202c20897) | `` Updated emacs ``        |
| [`e84bd87d`](https://github.com/nix-community/emacs-overlay/commit/e84bd87de2cf761c359dc6931c76326cde33e8d2) | `` Updated melpa ``        |
| [`aa451ac0`](https://github.com/nix-community/emacs-overlay/commit/aa451ac08eb3330749f75c4aa33c26e90d0362b2) | `` Updated elpa ``         |
| [`2c7ff266`](https://github.com/nix-community/emacs-overlay/commit/2c7ff266de758a5fd1a29 …

chore(flake/emacs-overlay): `d97f4109` -> `9f440671`

---

flake.lock

| [`19afc01e`](https://github.com/NixOS/nixpkgs/commit/19afc01e857c02a13ded2d88796afe99f0d493f0) | `` cargo-deny: 0.14.20 -> 0.14.21 ``                                       |
| [`8d3a38e8`](https://github.com/NixOS/nixpkgs/commit/8d3a38e8b19bdd6bf2a2274c91697cd315de0403) | `` NixOS Integration tests: Re-enable for macOS ``                         |
| [`c6a0404e`](https://github.com/NixOS/nixpkgs/commit/c6a0404e3e1ec5fe3705d5f3cf16562763d6f513) …

chore(flake/nixpkgs-unstable): `681d4a87` -> `037735eb`

---

flake.lock

| Commit                                                                                         | Message                                                                        |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| [`6a8ed263`](https://github.com/NixOS/nixpkgs/commit/6a8ed263b8f8661fcfd1d9d2056f9b7154c81258) | `` python312Packages.snakemake-interface-executor-plugins: 9.1.0 -> 9.1.1 ``   |
| [`a8fe1602`](https://github.com/NixOS/nixpkgs/commit/a8fe160216fa928972e8d51457e45cf8a7721eb8) | `` python312Packages.python-telegram-bot: 21.0.1 -> 21.1 ``                    |
| [`d76c4a6d`](https://github.com/NixOS/nixpkgs/commit/d76c4a6d8afcfa06c4e2cc849 …

chore(flake/nixpkgs-master): `1973d842` -> `cfd6b5fc`

---

flake.lock

| Commit                                                                                                     | Message                                          |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`72bd8e69`](https://github.com/LudovicoPiero/nixpackages/commit/72bd8e695fcdc85a7869d432c13ed803decaf4a9) | `` iosevka-q: 29.1.0 -> 29.2.0 ``                |
| [`bc2963f1`](https://github.com/LudovicoPiero/nixpackages/commit/bc2963f1e33a7fe8b5fc9ccad9d7def0b2ae314c) | `` chore(flake/nixpkgs): 4cba8b53 -> 1042fd8b `` |

chore(flake/ludovico-nixpkgs): `6ce00080` -> `72bd8e69`

---

flake.lock

| Commit                                                                                                      | Message                                                      |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`8fdf3295`](https://github.com/nix-community/home-manager/commit/8fdf329526f06886b53b94ddf433848a0d142984) | `` neovim: enable use of external package manager (#5225) `` |
| [`40ab43ae`](https://github.com/nix-community/home-manager/commit/40ab43ae98cb3e6f07eaeaa3f3ed56d589da21b0) | `` foot: set PATH in server's systemd unit file ``           |

chore(flake/home-manager): `31357486` -> `8fdf3295`

---

flake.lock

| Commit                                                                                         | Message                                                                                                                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------- |
| [`1dd996e5`](https://github.com/NixOS/nixpkgs/commit/1dd996e59a5e67694b7a252aacba71a88d51b41e) | `` aichat: 0.15.0 -> 0.16.0 ``                                                                                                  |
| [`6bb72e79`](https://github.com/NixOS/nixpkgs/commit/6bb72e79f7dc29fab08fed730b5b7fe7df031a9e) | `` tootik: …

chore(flake/nixpkgs-master): `cfd6b5fc` -> `1dd996e5`

---

flake.lock

| [`76210fdb`](https://github.com/Gerg-L/spicetify-nix/commit/76210fdb7c5f432d8708590466e21b558dd04cdd) | `` CI update 2024-04-13 (#130) `` |

chore(flake/spicetify-nix): `a2c63373` -> `76210fdb`

---

flake.lock

| Commit                                                                                         | Message                                                                        |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| [`6a8ed263`](https://github.com/NixOS/nixpkgs/commit/6a8ed263b8f8661fcfd1d9d2056f9b7154c81258) | `` python312Packages.snakemake-interface-executor-plugins: 9.1.0 -> 9.1.1 ``   |
| [`a8fe1602`](https://github.com/NixOS/nixpkgs/commit/a8fe160216fa928972e8d51457e45cf8a7721eb8) | `` python312Packages.python-telegram-bot: 21.0.1 -> 21.1 ``                    |
| [`d76c4a6d`](https://github.com/NixOS/nixpkgs/commit/d76c4a6d8afcfa06c4e2cc849 …

chore(flake/nixpkgs-unstable): `037735eb` -> `cfd6b5fc`

---

flake.lock

| Commit                                                                                           | Message                                                                   |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------- |
| [`9e4b2efe`](https://github.com/hyprwm/Hyprland/commit/9e4b2efe7e24f7b21faefbd50a88f25b5185bc35) | `` cmake: Some small cmake cleanups (#5572) ``                            |
| [`d9650144`](https://github.com/hyprwm/Hyprland/commit/d96501442fb3bbec129e74e26f379898f15881e2) | `` core: Fix double special workspace (#5574) ``                          |
| [`582d6233`](https://github.com/hyprwm/Hyprland/commit/582d6233c802327fea45a14d146e7cbab5f …

chore(flake/hyprland): `0c513ba9` -> `9e4b2efe`

---

flake.lock

| [`ea70f9df`](https://github.com/nix-community/emacs-overlay/commit/ea70f9df1ff67d1b37abd0893959ff315a599517) | `` Updated melpa ``        |
| [`86e121f2`](https://github.com/nix-community/emacs-overlay/commit/86e121f22763f18336d18980dd5d9a1d554a6874) | `` Updated elpa ``         |
| [`4163cf55`](https://github.com/nix-community/emacs-overlay/commit/4163cf558682e33b06b3ceaada03161d687edaf7) | `` Updated nongnu ``       |
| [`cedcee8e`](https://github.com/nix-community/emacs-overlay/commit/cedcee8ed57f4f715e487 …

chore(flake/emacs-overlay): `9f440671` -> `ea70f9df`

---

flake.lock

| Commit                                                                                         | Message                                                                                    |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`e2cd8a7a`](https://github.com/NixOS/nixpkgs/commit/e2cd8a7a2b1f508fedbfebfacd03a3036f32ac88) | `` editorconfig-core-c: 0.12.5 -> 0.12.7 ``                                                |
| [`d5793186`](https://github.com/NixOS/nixpkgs/commit/d5793186e8b239fe551839c3162c26873709e799) | `` python3Packages.sev-snp-measure: init at 0.0.9 (#303158) ``                             |
| …

chore(flake/nixpkgs-master): `1dd996e5` -> `a2a0f5f6`

---

flake.lock

| Commit                                                                                           | Message                                |
| ------------------------------------------------------------------------------------------------ | -------------------------------------- |
| [`61fe4718`](https://github.com/hyprwm/Hyprland/commit/61fe47189b885058157b23326118627ae61f3746) | `` build: update asan patch (#5562) `` |

chore(flake/hyprland): `9e4b2efe` -> `61fe4718`

---

flake.lock

| Commit                                                                                                     | Message                              |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`fd2f8ad0`](https://github.com/LudovicoPiero/nixpackages/commit/fd2f8ad01c54af1afa2ed107c8b76951578476d6) | `` sarasa-gothic: 1.0.9 -> 1.0.10 `` |

chore(flake/ludovico-nixpkgs): `72bd8e69` -> `fd2f8ad0`

---

flake.lock

| Commit                                                                                         | Message                                                                                                                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------- |
| [`e9e9bc94`](https://github.com/NixOS/nixpkgs/commit/e9e9bc94505ad57db4e6179127979ad76d065d52) | `` pspg: 5.8.2 -> 5.8.3 ``                                                                                                      |
| [`8945f3e5`](https://github.com/NixOS/nixpkgs/commit/8945f3e5ff3aec60dba4103bd682e89ddf14cc32) | `` …

chore(flake/nixpkgs-unstable): `cfd6b5fc` -> `e546289e`

---

flake.lock

| Commit                                                                                                       | Message             |
| ------------------------------------------------------------------------------------------------------------ | ------------------- |
| [`fb0a8410`](https://github.com/nix-community/emacs-overlay/commit/fb0a841062d30d512632144a0b8f429d3d83c9c1) | `` Updated emacs `` |

chore(flake/emacs-overlay): `ea70f9df` -> `fb0a8410`

---

flake.lock

| Commit                                                                                         | Message                                                                                           |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| [`ed817f46`](https://github.com/NixOS/nixpkgs/commit/ed817f469939a238181fa4872e082af4ad8c7499) | `` xcaddy: 0.3.5 -> 0.4.0 ``                                                                      |
| [`d59720a7`](https://github.com/NixOS/nixpkgs/commit/d59720a710244803b2152c370736246a1d3689d6) | `` doc/release-notes: mention Lomiri availability ``                                              |
| …

chore(flake/nixpkgs-master): `a2a0f5f6` -> `1f54fa2d`

---

flake.lock

| Commit                                                                                          | Message                  |
| ----------------------------------------------------------------------------------------------- | ------------------------ |
| [`226062b4`](https://github.com/Mic92/sops-nix/commit/226062b47fe0e2130ba3ee9f4f1c880dc815cf87) | `` flake.lock: Update `` |

chore(flake/sops-nix): `538c114c` -> `226062b4`

---

flake.lock

| Commit                                                                                                      | Message                                              |
| ----------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`9f32c66a`](https://github.com/nix-community/home-manager/commit/9f32c66a51d05e6d4ec0dea555bbff9135749ec7) | `` k9s: configuration files in Darwin without XDG `` |
| [`76a1650c`](https://github.com/nix-community/home-manager/commit/76a1650c45df8ed130e66eeeb8275a149562c4c5) | `` k9s: fix typos in configuration file names ``     |
| [`630a0992`](https://github.com/nix-community/home-manager/commit/630a0992b3627c64e34f179fab68e3d48c6991c0) | `` nushell: fix …

chore(flake/home-manager): `8fdf3295` -> `9f32c66a`

---

flake.lock

| [`c0302297`](https://github.com/Gerg-L/spicetify-nix/commit/c03022978f2ebbd3a7cf950de97f96ddfcd29bf3) | `` CI update 2024-04-14 (#131) `` |

chore(flake/spicetify-nix): `76210fdb` -> `c0302297`

---

flake.lock

| [`f92b1cf3`](https://github.com/nix-community/emacs-overlay/commit/f92b1cf3105eb9eab992e585861a762ad8cb0037) | `` Updated elpa ``         |
| [`5b014959`](https://github.com/nix-community/emacs-overlay/commit/5b014959f1634723bfce7bf137a181031b1c6e7c) | `` Updated flake inputs `` |
| [`8a3f1e57`](https://github.com/nix-community/emacs-overlay/commit/8a3f1e574aa11b3f0aee99bcb453b56c8d6f1ac7) | `` Updated emacs ``        |
| [`6cfac69a`](https://github.com/nix-community/emacs-overlay/commit/6cfac69a49d02b9886968 …

chore(flake/emacs-overlay): `fb0a8410` -> `f92b1cf3`

---

flake.lock

| Commit                                                                                         | Message                                                                                           |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| [`be86ca7e`](https://github.com/NixOS/nixpkgs/commit/be86ca7e0e5320b7a42711b88c1b32cafce7fef1) | `` cargo-temp: 0.2.19 -> 0.2.20 ``                                                                |
| [`57f408c5`](https://github.com/NixOS/nixpkgs/commit/57f408c562d6fc17aaa60a16573d741ba5a3e0e4) | `` pace: init at 0.15.2 ``                                                                        |
| …

chore(flake/nixpkgs-unstable): `e546289e` -> `5f81b281`

---

flake.lock

| Commit                                                                                                      | Message                                               |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`1c43dcfa`](https://github.com/nix-community/home-manager/commit/1c43dcfac48a2d622797f7ab741670fdbcf8f609) | `` ci: bump peaceiris/actions-gh-pages from 3 to 4 `` |
| [`59d50bc5`](https://github.com/nix-community/home-manager/commit/59d50bc582bdf439df096a9ae1781e6c9c8a7523) | `` espanso: enable module on darwin ``                |

chore(flake/home-manager): `9f32c66a` -> `1c43dcfa`

---

flake.lock

| Commit                                                                                            | Message                                                               |
| ------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`2c8e04e5`](https://github.com/numtide/devshell/commit/2c8e04e5c29299bec53c2e5a73da0f9afa8dabb5) | `` init compatibility with: nix bundle, nix run, lib.getExe (#306) `` |

chore(flake/devshell): `2d45b54c` -> `2c8e04e5`

---

flake.lock

| Commit                                                                                           | Message                                                                  |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------ |
| [`ccbdce7c`](https://github.com/hyprwm/Hyprland/commit/ccbdce7c8528781020b39ddf4498277df5e5e78d) | `` input: send an empty relative event after constraint motion events `` |
| [`3dbf8e93`](https://github.com/hyprwm/Hyprland/commit/3dbf8e936e5646d2e935509399f430fec850398a) | `` cursor: add hyprcursor loggers ``                                     |
| [`d1c2d524`](https://github.com/hyprwm/Hyprland/commit/d1c2d524a0f0e92783d707b7e6552ac74075146 …

chore(flake/hyprland): `67f47fbd` -> `ccbdce7c`

---

flake.lock

| [`1f760d9c`](https://github.com/Gerg-L/spicetify-nix/commit/1f760d9c0963d672e59d06e39b5e489819022cd1) | `` CI update 2024-04-15 (#132) `` |

chore(flake/spicetify-nix): `c0302297` -> `1f760d9c`

---

flake.lock

| Commit                                                                                                       | Message             |
| ------------------------------------------------------------------------------------------------------------ | ------------------- |
| [`cf218237`](https://github.com/nix-community/emacs-overlay/commit/cf218237d0d80f1ec8109677ebc82ded2ca84c43) | `` Updated emacs `` |
| [`ef7430cd`](https://github.com/nix-community/emacs-overlay/commit/ef7430cdf20c9d82d75ca9331ecc0f8f3115da3c) | `` Updated melpa `` |
| [`5e8cb839`](https://github.com/nix-community/emacs-overlay/commit/5e8cb83995ca355ebed239e66ec4b078f595a1b3) | `` Updated elpa ``  |
| [`61264683`](https://github.com/nix-community/emacs-overlay/commit/612646835968f663fd0e8f1a21ef52b5d0b88c57) | `` Updated …

chore(flake/emacs-overlay): `f92b1cf3` -> `cf218237`

---

flake.lock

| Commit                                                                                         | Message                                                                               |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`7801483a`](https://github.com/NixOS/nixpkgs/commit/7801483ab9e2587bdeef6cc5d7da7e7e499851e1) | `` fluxcd: convert hashes to SRI ``                                                   |
| [`e1728ff7`](https://github.com/NixOS/nixpkgs/commit/e1728ff7f53cc75f4ae228faae9088452d7063b3) | `` fluxcd: use SRI hash in update script ``                                           |
| …

chore(flake/nixpkgs-master): `1f54fa2d` -> `7d7fedce`

---

flake.lock

| Commit                                                                                         | Message                                                                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`b941d525`](https://github.com/NixOS/nixpkgs/commit/b941d525061a6e4f43882318225799c901f1ad40) | `` jasmin-compiler: 2023.06.2 → 2023.06.3 ``                                    |
| [`4b6f17a8`](https://github.com/NixOS/nixpkgs/commit/4b6f17a8a68cea10a618681a8163fbc02d30e1cc) | `` dune_3: 3.14.2 -> 3.15.0 ``                                                  |
| [`e91467c3`](https://github.com/NixOS/nixpkgs/commit/e91467c3ac90158d56bed …

chore(flake/nixpkgs-unstable): `5f81b281` -> `b941d525`

---

flake.lock

| Commit                                                                                          | Message                                   |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`cc535d07`](https://github.com/Mic92/sops-nix/commit/cc535d07cbcdd562bcca418e475c7b1959cefa4b) | `` remove all uses of lib.mdDoc (#532) `` |

chore(flake/sops-nix): `226062b4` -> `cc535d07`

---

flake.lock

| Commit                                                                                           | Message                                                                    |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`fe7b748e`](https://github.com/hyprwm/Hyprland/commit/fe7b748eb668136dd0558b7c8279bfcd7ab4d759) | `` props: bump version to 0.39.1 ``                                        |
| [`eeca50e3`](https://github.com/hyprwm/Hyprland/commit/eeca50e3dcf472d92431f0f06151a76c453c865e) | `` hyprpm: err out on missing runtime deps ``                              |
| [`9a66514e`](https://github.com/hyprwm/Hyprland/commit/9a66514e26319e41c8661f57097a73b …

chore(flake/hyprland): `ccbdce7c` -> `fe7b748e`

---

flake.lock

| Commit                                                                                                              | Message                  |
| ------------------------------------------------------------------------------------------------------------------- | ------------------------ |
| [`bb449215`](https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/bb44921534a9cee9635304fdb876c1b3ec3a8f61) | `` flake.lock: update `` |

chore(flake/xdph): `2d2fb547` -> `bb449215`

---

flake.lock

| Commit                                                                                         | Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`3ad65e9f`](https://github.com/NixOS/nixpkgs/commit/3ad65e9f48fd31c89121feb6e9c582ff7e4bb664) | `` oh-my-zsh: 2023-11-29 -> 2024-04-12 (#303737) ``                          |
| [`354e22ca`](https://github.com/NixOS/nixpkgs/commit/354e22ca6bc0f86d461e49bfa3ed5ba3e2eaeb0a) | `` vscode-extensions.timonwong.shellcheck: move to a directory ``            |
| [`3e435829`](https://github.com/NixOS/nixpkgs/commit/3e4358290ca54fa1503217b21fd825335 …

chore(flake/nixpkgs-unstable): `b941d525` -> `3ad65e9f`

---

flake.lock

| [`502906af`](https://github.com/nix-community/emacs-overlay/commit/502906af674eae890790ec48cad959d42dc2f040) | `` Updated emacs ``        |
| [`10b148d3`](https://github.com/nix-community/emacs-overlay/commit/10b148d3b245cd8abf3064c9ed4470125b0d5816) | `` Updated melpa ``        |
| [`63221ee3`](https://github.com/nix-community/emacs-overlay/commit/63221ee331da17e5c14e6682224218573bdc3951) | `` Updated elpa ``         |
| [`433c5449`](https://github.com/nix-community/emacs-overlay/commit/433c54490f99473a5fb9d …

chore(flake/emacs-overlay): `cf218237` -> `502906af`

---

flake.lock

| Commit                                                                                         | Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`06c817b2`](https://github.com/NixOS/nixpkgs/commit/06c817b2acf67a707a1df00032d22311641deee8) | `` s6-rc: use --replace-fail for cross substitutions ``                      |
| [`4b46c7e8`](https://github.com/NixOS/nixpkgs/commit/4b46c7e8eb051752d5a43b985e3c76f9fe0aeb7c) | `` s6-linux-init: fix cross compilation ``                                   |
| [`3ad65e9f`](https://github.com/NixOS/nixpkgs/commit/3ad65e9f48fd31c89121feb6e9c582ff7 …

chore(flake/nixpkgs-master): `7d7fedce` -> `4231f20d`

---

flake.lock

| Commit                                                                                           | Message                                                                    |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- |
| [`78b04c3a`](https://github.com/hyprwm/Hyprland/commit/78b04c3a76614015a6f79f7b3c0e4ebe05548594) | `` hyprctl: fix activewindow request not showing workspace name (#5623) `` |
| [`e57a2d7e`](https://github.com/hyprwm/Hyprland/commit/e57a2d7ec87ae775828ea8628ef4eeafce8e6e70) | `` keybindmgr: add optional `silent` suffix to `movewindow`. (#5597) ``    |
| [`e8e02e81`](https://github.com/hyprwm/Hyprland/commit/e8e02e81e84bb04efa0c926361ec80c …

chore(flake/hyprland): `fe7b748e` -> `78b04c3a`

---

flake.lock

| [`fdc292b9`](https://github.com/Gerg-L/spicetify-nix/commit/fdc292b94f7a2137b710f175e7954feac30e8a9f) | `` CI update 2024-04-17 (#134) `` |

chore(flake/spicetify-nix): `578ceee6` -> `fdc292b9`

---

flake.lock

| Commit                                                                                        | Message                                  |
| --------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`e5c6c31e`](https://github.com/NixOS/nixfmt/commit/e5c6c31e8315d46b02237ae42d0b2f58c89c650b) | `` Fix duplicate Nixpkgs diff comment `` |

chore(flake/nixfmt): `3cb264c8` -> `87c4879b`

---

flake.lock

| [`208d00a7`](https://github.com/nix-community/emacs-overlay/commit/208d00a7f96d920a153ab90f257357e1aa1d6d77) | `` Updated emacs ``        |
| [`68b08d5c`](https://github.com/nix-community/emacs-overlay/commit/68b08d5cd11d3c005f017ca2199c5164362d26d1) | `` Updated melpa ``        |
| [`57295046`](https://github.com/nix-community/emacs-overlay/commit/57295046afe433216a389f73b1bcd351de852842) | `` Updated elpa ``         |
| [`03342208`](https://github.com/nix-community/emacs-overlay/commit/0334220804cb13f86e1e7 …

chore(flake/emacs-overlay): `502906af` -> `208d00a7`

---

flake.lock

| Commit                                                                                         | Message                                                                        |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| [`23e6179e`](https://github.com/NixOS/nixpkgs/commit/23e6179e7d06c4c8bfd95678b0f6dabccd2d0849) | `` linux_latest-libre: 19527 -> 19536 ``                                       |
| [`2234f0fa`](https://github.com/NixOS/nixpkgs/commit/2234f0fa7849671e4885e1af489ebec477828f9d) | `` linux_5_15: 5.15.155 -> 5.15.156 ``                                         |
| [`a943f8eb`](https://github.com/NixOS/nixpkgs/commit/a943f8ebc090c12af0aa4b3b4 …

chore(flake/nixpkgs-master): `4231f20d` -> `d205596f`

---

flake.lock

| [`c087ebcc`](https://github.com/Gerg-L/spicetify-nix/commit/c087ebccf75e3db5b902b574304b39103c75f8d2) | `` CI update 2024-04-18 (#135) `` |

chore(flake/spicetify-nix): `fdc292b9` -> `c087ebcc`

---

flake.lock

| Commit                                                                                                     | Message                                          |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`69fd13a2`](https://github.com/LudovicoPiero/nixpackages/commit/69fd13a2529159ed2b9ed7df6930cca3921042dd) | `` chore(flake/nixpkgs): cfd6b5fc -> 5672bc9d `` |
| [`5e0524a7`](https://github.com/LudovicoPiero/nixpackages/commit/5e0524a7069ca1a85771332b0046e6e2c790f3c7) | `` Update ``                                     |

chore(flake/ludovico-nixpkgs): `5cbb6f46` -> `69fd13a2`

---

flake.lock

| Commit                                                                                                      | Message                                                  |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`178e2689`](https://github.com/nix-community/home-manager/commit/178e26895b3aef028a00a32fb7e7ed0fc660645c) | `` home-manager: error out on missing option argument `` |
| [`f46814ec`](https://github.com/nix-community/home-manager/commit/f46814ec7cbef9c2aef18ca1cbe89f2bb1e8c394) | `` treewide: prefer the official wiki ``                 |
| [`93b917d4`](https://github.com/nix-community/home-manager/commit/93b917d49f0b2ab75ff91e17573e112b95fdd95c) | `` …

chore(flake/home-manager): `fa8c16e2` -> `178e2689`

---

flake.lock

| Commit                                                                                          | Message                                                                               |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`b94c6edb`](https://github.com/Mic92/sops-nix/commit/b94c6edbb8355756c53efc8ca3874c63622f287a) | `` fix symlink directory not existing ``                                              |
| [`6b259336`](https://github.com/Mic92/sops-nix/commit/6b259336bd009e8a056ea740e75e6ac95e0f0c1f) | `` Lint fixes (#539) ``                                                               |
| …

chore(flake/sops-nix): `cc535d07` -> `b94c6edb`

---

flake.lock

| Commit                                                                                           | Message                                            |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| [`82222342`](https://github.com/hyprwm/Hyprland/commit/82222342f10a7eff0ec9be972153e740d0f95213) | `` shaders: Use sin-less hash for noise (#5607) `` |

chore(flake/hyprland): `78b04c3a` -> `82222342`

---

flake.lock

| Commit                                                                                         | Message                                                                         |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`083e90af`](https://github.com/NixOS/nixpkgs/commit/083e90af2f6c20e14e464efb56bb343d095eb7c8) | `` python312Packages.findpython: 0.6.0 -> 0.6.1 ``                              |
| [`95eca14c`](https://github.com/NixOS/nixpkgs/commit/95eca14cb709bad9603dbf18e5fab0e43d55b66c) | `` slither-analyzer: 0.10.1 -> 0.10.2 ``                                        |
| [`77e8d6f0`](https://github.com/NixOS/nixpkgs/commit/77e8d6f0583d251b8f645 …

chore(flake/nixpkgs-unstable): `edd8117b` -> `bc279bba`

---

flake.lock

| Commit                                                                                            | Message                                                               |
| ------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`6dee0dd5`](https://github.com/numtide/devshell/commit/6dee0dd58da5054b9c403a47b14ba87b7966f2f9) | `` feat(tests): test packagesFrom with a null in buildInputs ``       |
| [`cbd803c7`](https://github.com/numtide/devshell/commit/cbd803c76bd1df4aedef30bcbb82e83818282a67) | `` fix(modules > devshell): filter out non-derivation dependencies `` |

chore(flake/devshell): `2c8e04e5` -> `12e91474`

---

flake.lock

| Commit                                                                                          | Message                                                  |
| ----------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`a929a011`](https://github.com/Mic92/sops-nix/commit/a929a011a09db735abc45a8a45d1ff7fdee62755) | `` update vendorHash ``                                  |
| [`d63d2a0f`](https://github.com/Mic92/sops-nix/commit/d63d2a0fdfcbd5e24d5a19e97cd1ed3d78b6418d) | `` Bump golang.org/x/net from 0.21.0 to 0.23.0 ``        |
| [`6ef5c647`](https://github.com/Mic92/sops-nix/commit/6ef5c647a4f38f5608a63fdc80a58bf772b11be8) | `` drop docs unpinned ways of installing sops-nix ``     |
| …

chore(flake/sops-nix): `b94c6edb` -> `a929a011`

---

flake.lock

| Commit                                                                                         | Message                                                                                                              |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------- |
| [`f1e8e483`](https://github.com/NixOS/nixpkgs/commit/f1e8e4837d258a15a5564fdaadc436bee2c38f87) | `` coqPackages.CoLoR: 1.8.4 → 1.8.5 ``                                                                               |
| [`4237fee2`](https://github.com/NixOS/nixpkgs/commit/4237fee22db7ee89d831e671073d9e2ab36dc59a) | `` Revert "icu: refactor to avoid runtime …

chore(flake/nixpkgs-unstable): `bc279bba` -> `193037db`

---

flake.lock

| Commit                                                                                        | Message                                                             |
| --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| [`27f80162`](https://github.com/NixOS/nixfmt/commit/27f80162729de92c77337ba96304ca91df9d41de) | `` treefmt: Ensure all Haskell files are formatted with fourmolu `` |
| [`c697c0a7`](https://github.com/NixOS/nixfmt/commit/c697c0a7a9406639acaf9a3325b896c777525261) | `` treefmt: Ensure all Nix files are formatted ``                   |
| [`c60836d4`](https://github.com/NixOS/nixfmt/commit/c60836d413dd8dcf0d059aaff4d33b8cc5dea567) | `` Add treefmt, empty config …

chore(flake/nixfmt): `87c4879b` -> `a8b578d1`

---

flake.lock

| Commit                                                                                                      | Message                                                       |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`6a171bfd`](https://github.com/nix-community/home-manager/commit/6a171bfd84ee9b3df83f6eb76dab042219978439) | `` kconfig: add module ``                                     |
| [`1f305c36`](https://github.com/nix-community/home-manager/commit/1f305c363ecd7c6505f03fc7baba15505f3aa630) | `` remmina: add module ``                                     |
| [`31c77dcc`](https://github.com/nix-community/home-manager/commit/31c77dcc2e4b6b9f73df0e7eaa89 …

chore(flake/home-manager): `178e2689` -> `6a171bfd`

---

flake.lock

| Commit                                                                                                     | Message                                          |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`30513442`](https://github.com/LudovicoPiero/nixpackages/commit/30513442798cad6907051f14922e7f16a633d9dd) | `` chore(flake/nixpkgs): 5672bc9d -> 66adc1e4 `` |
| [`53799f09`](https://github.com/LudovicoPiero/nixpackages/commit/53799f09bd260904c5180b2357d12d284df87e16) | `` Update ``                                     |

chore(flake/ludovico-nixpkgs): `69fd13a2` -> `30513442`

---

flake.lock

| Commit                                                                                           | Message                                                                                       |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------- |
| [`4d0a6352`](https://github.com/hyprwm/Hyprland/commit/4d0a63523751a590a521fd873f770825023069ae) | `` workspace: Add 'v' flag for workspace selector that counts only visible windows (#5628) `` |

chore(flake/hyprland): `82222342` -> `4d0a6352`

---

flake.lock

| Commit                                                                                         | Message                                                                                                              |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------- |
| [`45a89f4e`](https://github.com/NixOS/nixpkgs/commit/45a89f4ea3ccb6dc08b06f746a968992464d410f) | `` eog: add `jxl` support ``                                                                                         |
| [`0518f07b`](https://github.com/NixOS/nixpkgs/commit/0518f07b8e2cbc41b588add9cf8a41a3f7d0411d) | `` gnome: add `jxl` thumbnails and wallpapers …

chore(flake/nixpkgs-master): `1b7469ab` -> `45a89f4e`

---

flake.lock

| [`0be1306b`](https://github.com/nix-community/emacs-overlay/commit/0be1306bf44aedaf54642c4dc9bbbc210267dcd7) | `` Updated melpa ``        |
| [`7600854b`](https://github.com/nix-community/emacs-overlay/commit/7600854b9d7d7e4a897638a1df6ea2275682a8ab) | `` Updated elpa ``         |
| [`a8692d4e`](https://github.com/nix-community/emacs-overlay/commit/a8692d4e570e93061d2bbe10af4a1590afe82e15) | `` Updated emacs ``        |
| [`d66e33b9`](https://github.com/nix-community/emacs-overlay/commit/d66e33b94492c5e897729 …

chore(flake/emacs-overlay): `925e7b36` -> `0be1306b`

---

flake.lock

| [`43adac8c`](https://github.com/Gerg-L/spicetify-nix/commit/43adac8c911bb335f51ea2698f3a24c73c28ca36) | `` CI update 2024-04-19 (#136) `` |

chore(flake/spicetify-nix): `c087ebcc` -> `43adac8c`

---

flake.lock

| Commit                                                                                                     | Message                                                                                                 |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| [`05d4a869`](https://github.com/privatevoid-net/nix-super/commit/05d4a86923ed8633b3f1c72239b58770b57366bb) | `` libcmd/modify-installables: build overrideValues differently ``                                      |
| [`1e28a137`](https://github.com/privatevoid-net/nix-super/commit/1e28a13720bf0f64ec3e86d34ede4aa0d4be023f) | `` libcmd: attrs -> attrs() `` …

chore(flake/nix-super): `afffb665` -> `05d4a869`
