- flake.lock
| [`61cdc7fb`](https://github.com/chaotic-cx/nyx/commit/61cdc7fbcf5678d50913b4888f50b9affc068e9d) | `` Bump 20231125-2 (#451) `` |
| [`27206bce`](https://github.com/chaotic-cx/nyx/commit/27206bce9a469ff2c20333943cefb19bb3778c27) | `` Bump 20231125-1 (#450) `` |
> chore(flake/chaotic): `b52e938a` -> `61cdc7fb`

- flake.lock
| Commit                                                                                                     | Message                                                                     |
| ---------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`21359472`](https://github.com/privatevoid-net/nix-super/commit/213594721ace2b2e2dcf3d57615178a2c1690aa4) | `` gitignore: Also ignore .DS_Store ``                                      |
| [`54b68476`](https://github.com/privatevoid-net/nix-super/commit/54b684765519dee1e74dca71605f8e7f6c8b0a25) | `` doc: fix machine-specific capabilities leaking ``                        |
| …
> chore(flake/nix-super): `4f4d3a53` -> `c076362d`

- .github/mergify.yml
- .github/workflows/flake-update.yml
This change has been made by @LudovicoPiero from Mergify config editor.
> ci(Mergify): configuration update

- flake.lock
| [`5a9ea054`](https://github.com/chaotic-cx/nyx/commit/5a9ea054d7905d2264cbec76181ca48193d6dab9) | `` Bump 20231205-1 (#466) `` |
> chore(flake/chaotic): `bd466e00` -> `5a9ea054`

- flake.lock
| Commit                                                                                             | Message                    |
| -------------------------------------------------------------------------------------------------- | -------------------------- |
| [`784c8293`](https://github.com/nix-community/NUR/commit/784c8293dc4f19f89a812f6d745aff28d47d24d9) | `` automatic update ``     |
| [`a663c76c`](https://github.com/nix-community/NUR/commit/a663c76cc6b32cd341f6d0c649015d18384c3cbf) | `` automatic update ``     |
| [`fc7246b1`](https://github.com/nix-community/NUR/commit/fc7246b150c77137ae239cd9b2252e607a64b933) | `` automatic update ``     |
| [`b1588af9`](https://github.com/nix-community/NUR/commit/b1588af9f3e7509e180ff10db4fac4443c238ae5) | `` automatic update ``     |
| …
> chore(flake/nur): `1d374446` -> `784c8293`

- flake.lock
| Commit                                                                                          | Message                                                            |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`3662460d`](https://github.com/chaotic-cx/nyx/commit/3662460dde402c02a6ca2ea3a073af01e9e85a0b) | `` linux_cachyos: 6.6.6 -> 6.6.7 (#492) ``                         |
| [`e460f59e`](https://github.com/chaotic-cx/nyx/commit/e460f59ed124457c444dfa4031f503bd7ea4b07b) | `` ci/single-bump: fix push ``                                     |
| [`99aeab57`](https://github.com/chaotic-cx/nyx/commit/99aeab57ef5c4c2f4e0b17744833f39fa7a2e7aa) | `` build(deps): bump …
> chore(flake/chaotic): `479bf876` -> `3662460d`

- pkgs/_sources/generated.json
- pkgs/_sources/generated.nix
> Nvfetcher update

- flake.lock
| [`778e166a`](https://github.com/chaotic-cx/nyx/commit/778e166a2a77a42f5f32eff590b0be60f0daf562) | `` Bump 20231225-1 (#504) ``    |
| [`908c560f`](https://github.com/chaotic-cx/nyx/commit/908c560f28e6dcf8f3d6800f0b656df84a8ac5e1) | `` Bump 20231224-1 (#503) ``    |
| [`683cfffd`](https://github.com/chaotic-cx/nyx/commit/683cfffdde1736bcc45936e243f220a2c0f5dc89) | `` nixpkgs: bump to 20231224 `` |
> chore(flake/chaotic): `69a7b82c` -> `778e166a`

- .github/mergify.yml
- flake.lock
| Commit                                                                                                    | Message                                             |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`872f9f3e`](https://github.com/nix-community/lanzaboote/commit/872f9f3ea8b2359e31efa5916dbb3b09d3cbf97c) | `` fix(deps): update rust crate anyhow to 1.0.76 `` |
> chore(flake/lanzaboote): `9186a778` -> `47032189`

- flake.lock
| Commit                                                                                           | Message                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`191fa587`](https://github.com/hyprwm/Hyprland/commit/191fa587f4daf9f3bf3e3f791de9e2dc5e95a459) | `` windowrules: add initialTitle and initialClass (#4259) ``                |
| [`9fb50252`](https://github.com/hyprwm/Hyprland/commit/9fb50252d3a128466e80bfc2fb67b45dc923ad41) | `` special: move floating windows along with the workspace ``               |
| [`bfb4d66c`](https://github.com/hyprwm/Hyprland/commit/bfb4d66c8144a36f2c52530f10a …
> chore(flake/hyprland): `2c2ff4b6` -> `191fa587`

- flake.lock
| [`c56ab874`](https://github.com/nix-community/NUR/commit/c56ab874a3d53b630e946536612e748a7cd9f2f4) | `` automatic update `` |
| [`0529839a`](https://github.com/nix-community/NUR/commit/0529839a62a15cda326e38353f9c10a4efa01d60) | `` automatic update `` |
| [`a46e51e4`](https://github.com/nix-community/NUR/commit/a46e51e4007f5149ad968b9fea4e1ede810e9d4f) | `` automatic update `` |
| [`a5413575`](https://github.com/nix-community/NUR/commit/a5413575b81cb56dce59556c7abd06471ea48079) | `` automatic update `` |
| …
> chore(flake/nur): `74bee334` -> `c56ab874`

- flake.lock
| Commit                                                                                          | Message                                                          |
| ----------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`18e8728c`](https://github.com/chaotic-cx/nyx/commit/18e8728c4bd5a227d65f6dbe90715d0234d30b4a) | `` nixpkgs: bump to 20240120 ``                                  |
| [`756b7cbf`](https://github.com/chaotic-cx/nyx/commit/756b7cbf9bc4941c0c380fd3ce40c04e11b864d7) | `` schemas: skip throw (oops) ``                                 |
| [`cbfef4e8`](https://github.com/chaotic-cx/nyx/commit/cbfef4e8e8b21f5b5d6f1f002234bee9a9fa6f2f) | `` schemas: skip throw `` …
> chore(flake/chaotic): `d2a46921` -> `18e8728c`

- flake.lock
| Commit                                                                                             | Message                             |
| -------------------------------------------------------------------------------------------------- | ----------------------------------- |
| [`81804f94`](https://github.com/nix-community/NUR/commit/81804f94bec0198d25a2d2fd9359a46e5d618637) | `` automatic update ``              |
| [`236b614c`](https://github.com/nix-community/NUR/commit/236b614c4c91c07e1239dff02e91377bf305354f) | `` automatic update ``              |
| [`191ffd0d`](https://github.com/nix-community/NUR/commit/191ffd0db0f2050bd43b3e11ab9c95ebce3f5887) | `` automatic update ``              |
| [`5209d1f0`](https://github.com/nix-community/NUR/commit/5209d1f058c7f5c062dd1e9f7c6c6c923ad4 …
> chore(flake/nur): `2a7a1576` -> `81804f94`

- flake.lock
| Commit                                                                                           | Message                                                                                                  |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------------------------- |
| [`3e93fdf7`](https://github.com/hyprwm/Hyprland/commit/3e93fdf7794416272430300426a62497d9d0b835) | `` opengl: use texBox for rendering background texture ``                                                |
| [`bc7e488a`](https://github.com/hyprwm/Hyprland/commit/bc7e488a4c7a4bfdd7bce66265fe8aea516fd2ed) | `` monitor: clear output state after usage `` …
> chore(flake/hyprland): `791e1b96` -> `3e93fdf7`

- flake.lock
| Commit                                                                                                    | Message                                            |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`26bc3272`](https://github.com/nix-community/lanzaboote/commit/26bc32726cfa84a2a1a2f6c5f6560d336434782e) | `` chore(deps): lock file maintenance ``           |
| [`53fc3ad7`](https://github.com/nix-community/lanzaboote/commit/53fc3ad7fb1248aa9b985c7d17a5b8ae1f44ed49) | `` fix(deps): update all dependencies ``           |
| [`5de0b3e5`](https://github.com/nix-community/lanzaboote/commit/5de0b3e54a05aaf0faa3ab42fea5ac09008109aa) | `` stub: rename sections for UKI …
> chore(flake/lanzaboote): `f2bc0af5` -> `96181a46`

- flake.lock
| [`20813cd3`](https://github.com/chaotic-cx/nyx/commit/20813cd335222931394914d24cda8f7ea958fe28) | `` Bump 20240217-1 (#592) ``    |
| [`b345699a`](https://github.com/chaotic-cx/nyx/commit/b345699a5fb460094e6ad8e9ddc224f81a7c7ce8) | `` nixpkgs: bump to 20240215 `` |
| [`c1f948fb`](https://github.com/chaotic-cx/nyx/commit/c1f948fbb002459bfa805dfee70f6e9927eaf594) | `` nixpkgs: bump to 20240215 `` |
> chore(flake/chaotic): `a1350f6b` -> `20813cd3`

- flake.lock
| Commit                                                                                          | Message                              |
| ----------------------------------------------------------------------------------------------- | ------------------------------------ |
| [`b217bc2f`](https://github.com/chaotic-cx/nyx/commit/b217bc2f0e351e4c78f79d2d84af58bef02f47cc) | `` Bump 20240218-1 (#595) ``         |
| [`33756832`](https://github.com/chaotic-cx/nyx/commit/33756832601b7e302d274f7d881f990c11ff4359) | `` i915 driver on mesa-git (#594) `` |
> chore(flake/chaotic): `20813cd3` -> `b217bc2f`

- flake.lock
| Commit                                                                                                    | Message                                  |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`78374106`](https://github.com/nix-community/lanzaboote/commit/78374106eae28013c28950fcd680f1059e6b99ff) | `` fix(deps): update all dependencies `` |
| [`6cfed923`](https://github.com/nix-community/lanzaboote/commit/6cfed923dbc398bccf5dbeb70fbcb80876975f46) | `` chore(deps): lock file maintenance `` |
> chore(flake/lanzaboote): `098f0194` -> `73fec693`

- flake.lock
| Commit                                                                                          | Message                                                          |
| ----------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`4730981f`](https://github.com/chaotic-cx/nyx/commit/4730981fd98f9f7c7c14f641973196fb838a28ab) | `` Bump 20240224-1 (#601) ``                                     |
| [`183d1cc0`](https://github.com/chaotic-cx/nyx/commit/183d1cc026a47171ef0eea98db5d133cec10457a) | `` mesa_git: add patch from MR2767 ``                            |
| [`37b3df56`](https://github.com/chaotic-cx/nyx/commit/37b3df564cdf9ac0e535e7092e37691701639a4e) | `` conduit_git: migrate to …
> chore(flake/chaotic): `bcc38cf3` -> `4730981f`

- flake.lock
| Commit                                                                                           | Message                                                                            |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------- |
| [`c4f52d19`](https://github.com/hyprwm/Hyprland/commit/c4f52d19792696b8b297877b9152bd86d0f4624b) | `` master: fix invalid config usage ``                                             |
| [`38576d65`](https://github.com/hyprwm/Hyprland/commit/38576d651a9a7edcf5d7b782a2f415c8a1f0f4e6) | `` renderer: adjust surface dimensions for oversized not-yet ackd surface sizes `` |
| …
> chore(flake/hyprland): `981296f1` -> `c4f52d19`

- flake.lock
| [`73e16a06`](https://github.com/chaotic-cx/nyx/commit/73e16a06baf8a9bb273a131b10b142f620c2b610) | `` Bump 20240316-1 (#632) `` |
> chore(flake/chaotic): `4417bbe3` -> `73e16a06`

- flake.lock
| Commit                                                                                           | Message                                                             |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------- |
| [`187caf41`](https://github.com/hyprwm/Hyprland/commit/187caf4187ffc16ec159b1a5b15657a18dfc05e1) | `` layers: don't change workspace on layer restore focus (#5308) `` |
| [`647d5a4f`](https://github.com/hyprwm/Hyprland/commit/647d5a4ffc08ee654eb3ce951977789b1385a7f8) | `` layers: fix bottom slide animation (#5307) ``                    |
> chore(flake/hyprland): `25718754` -> `187caf41`

- flake.lock
| Commit                                                                                          | Message                                     |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------- |
| [`7cc62824`](https://github.com/chaotic-cx/nyx/commit/7cc6282416833f2dea96f97f516aceadbf406404) | `` linux_cachyos: 6.8.1 -> 6.8.2 (#659) ``  |
| [`54c7a73f`](https://github.com/chaotic-cx/nyx/commit/54c7a73ff54314f56e40f99b9247760dcedffa15) | `` Bump 20240329-1 (#658) ``                |
| [`6608f9c3`](https://github.com/chaotic-cx/nyx/commit/6608f9c31c45b6966d5b6e6c08c41b7204c3ae23) | `` firedragon: 11.10.5 -> 11.11.2 (#652) `` |
> chore(flake/chaotic): `bec5e460` -> `7cc62824`

- flake.lock
| Commit                                                                                                     | Message                                                                                                       |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
| [`a748f7a2`](https://github.com/LudovicoPiero/nixpackages/commit/a748f7a257943783500f35d3d1d06ab74a852171) | `` whitesur-gtk-theme: 9739d7c08379c624b7e4c7fb662ba151dbfe34f0 → 5d6eadca2bd7031afe3308fc6c1bda1b92181c72 `` |
| [`f22c2346`](https://github.com/LudovicoPiero/nixpackages/commit/f22c2346ed4e28d9e846a08067b2dd6a1249cd4f) | `` …
> chore(flake/ludovico-nixpkgs): `0f783e55` -> `a748f7a2`

- flake.lock
| Commit                                                                                                     | Message                                                                                           |
| ---------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| [`628be772`](https://github.com/LudovicoPiero/nixpackages/commit/628be77284fc85697f1f2a5d679673d3549a57b9) | `` chore(flake/nixpkgs): d8fe5e6c -> 08b9151e ``                                                  |
| [`c1ef9abd`](https://github.com/LudovicoPiero/nixpackages/commit/c1ef9abd057f269ec9ede7e3af31773e20ce4e03) | `` ci: daily-bump: change commiter `` …
> chore(flake/ludovico-nixpkgs): `17ea9c3c` -> `628be772`

- flake.lock
| Commit                                                                                           | Message                                                              |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [`67f47fbd`](https://github.com/hyprwm/Hyprland/commit/67f47fbdccd639502a76ccb3552a23df37f19ef8) | `` [gha] Nix: update wlroots ``                                      |
| [`043a40cd`](https://github.com/hyprwm/Hyprland/commit/043a40cd7a7fc122fbf17075de680fd7b79e4281) | `` deps: update wlroots (#5592) ``                                   |
| [`fd7ea4f2`](https://github.com/hyprwm/Hyprland/commit/fd7ea4f27c8a596d1b72101ab4c0eca5b5b60ed5) | `` …
> chore(flake/hyprland): `61fe4718` -> `67f47fbd`
